import { Routes } from '@angular/router';
import { authGuard } from './core/auth.guard';
import { ewAgencyGuard } from './core/ew-agency.guard';

export const routes: Routes = [
  { path: 'login', loadComponent: () => import('./pages/login.component').then(m => m.LoginComponent) },

  // ---- PUBLIC portal (citizen-facing, no auth) — mirrors Laravel's public routes ----
  {
    path: '',
    loadComponent: () => import('./pages/public/public-layout.component').then(m => m.PublicLayoutComponent),
    children: [
      { path: '', pathMatch: 'full', loadComponent: () => import('./pages/public/landing.component').then(m => m.LandingComponent) },
      { path: 'about', loadComponent: () => import('./pages/public/about.component').then(m => m.AboutComponent) },
      { path: 'portal', loadComponent: () => import('./pages/public/public-portal.component').then(m => m.PublicLivePortalComponent) },
      { path: 'subscribe', loadComponent: () => import('./pages/public/subscribe.component').then(m => m.SubscribeComponent) },
      { path: 'education', loadComponent: () => import('./pages/public/education.component').then(m => m.EducationComponent) },
      { path: 'hazard-calendar', loadComponent: () => import('./pages/public/hazard-calendar.component').then(m => m.HazardCalendarComponent) },
      { path: 'inform-risk', loadComponent: () => import('./pages/public/inform-explorer.component').then(m => m.PublicInformExplorerComponent) },
      { path: 'inform-education', loadComponent: () => import('./pages/public/inform-education.component').then(m => m.PublicInformEducationComponent) },
      { path: 'education/hazard/:name', loadComponent: () => import('./pages/public/hazard-hub.component').then(m => m.HazardHubComponent) },
      { path: 'education/:id', loadComponent: () => import('./pages/public/education.component').then(m => m.EducationComponent) },
      { path: 'threats/:id', loadComponent: () => import('./pages/public/threat-detail.component').then(m => m.ThreatDetailComponent) },
      { path: 'news/:slug', loadComponent: () => import('./pages/public/news-article.component').then(m => m.NewsArticleComponent) },
      { path: 'incident/:id', loadComponent: () => import('./pages/public/incident-snapshot.component').then(m => m.IncidentSnapshotComponent) },
      { path: 'publications', loadComponent: () => import('./pages/public/publications.component').then(m => m.PublicationsComponent) },
      { path: 'publications/:type', loadComponent: () => import('./pages/public/publications.component').then(m => m.PublicationsComponent) },
      { path: 'publications/:type/:id', loadComponent: () => import('./pages/public/publication-detail.component').then(m => m.PublicationDetailComponent) },
    ],
  },
  { path: 'home', canActivate: [authGuard], loadComponent: () => import('./pages/module-hub.component').then(m => m.ModuleHubComponent) },
  { path: 'access-denied', canActivate: [authGuard], loadComponent: () => import('./pages/access-denied.component').then(m => m.AccessDeniedComponent) },
  { path: 'm/budget-finance/budgets', canActivate: [authGuard], loadComponent: () => import('./pages/finance/budget-finance.component').then(m => m.BudgetFinanceComponent) },
  { path: 'm/budget-finance/budgets/:id', canActivate: [authGuard], loadComponent: () => import('./pages/finance/budget-detail.component').then(m => m.BudgetDetailComponent) },
  { path: 'm/preparedness/early-warnings', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/early-warnings.component').then(m => m.EarlyWarningsComponent) },
  { path: 'm/preparedness/early-warnings/engine', redirectTo: 'm/preparedness/early-warnings', pathMatch: 'full' },
  { path: 'm/preparedness/early-warnings/new-bulletin', canActivate: [authGuard, ewAgencyGuard], loadComponent: () => import('./pages/preparedness/ew-alert-map.component').then(m => m.EwAlertMapComponent) },
  { path: 'm/preparedness/early-warnings/eocc-bulletin', canActivate: [authGuard, ewAgencyGuard], loadComponent: () => import('./pages/preparedness/generated-bulletins.component').then(m => m.GeneratedBulletinsComponent) },
  // Native EW entity consoles (the full authoring → impact → dissemination → monitoring flow).
  { path: 'm/preparedness/early-warnings/mow', canActivate: [authGuard, ewAgencyGuard], loadComponent: () => import('./pages/preparedness/ew-agencies/mow-flood.component').then(m => m.MowFloodComponent) },
  { path: 'm/preparedness/early-warnings/gst', canActivate: [authGuard, ewAgencyGuard], loadComponent: () => import('./pages/preparedness/ew-agencies/gst-geo.component').then(m => m.GstGeoComponent) },
  { path: 'm/preparedness/early-warnings/moh', canActivate: [authGuard, ewAgencyGuard], loadComponent: () => import('./pages/preparedness/ew-agencies/moh-health.component').then(m => m.MohHealthComponent) },
  { path: 'm/preparedness/early-warnings/moa', canActivate: [authGuard, ewAgencyGuard], loadComponent: () => import('./pages/preparedness/ew-agencies/moa-drought.component').then(m => m.MoaDroughtComponent) },
  { path: 'm/preparedness/early-warnings/nemc', canActivate: [authGuard, ewAgencyGuard], loadComponent: () => import('./pages/preparedness/ew-agencies/nemc-air.component').then(m => m.NemcAirComponent) },
  { path: 'm/preparedness/early-warnings/mlf', canActivate: [authGuard, ewAgencyGuard], loadComponent: () => import('./pages/preparedness/ew-agencies/mlf-livestock.component').then(m => m.MlfLivestockComponent) },
  { path: 'm/preparedness/early-warnings/consolidated', canActivate: [authGuard, ewAgencyGuard], loadComponent: () => import('./pages/preparedness/ew-agencies/dmd-consolidated.component').then(m => m.DmdConsolidatedComponent) },
  { path: 'm/preparedness/early-warnings/scanner', canActivate: [authGuard, ewAgencyGuard], loadComponent: () => import('./pages/preparedness/disaster-scanner.component').then(m => m.DisasterScannerComponent) },
  { path: 'm/preparedness/evacuation-centers', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/evacuation-centers.component').then(m => m.EvacuationCentersComponent) },
  { path: 'm/preparedness/evacuation-centers/create', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/evacuation-center-create.component').then(m => m.EvacuationCenterCreateComponent) },
  { path: 'm/preparedness/warehouses', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/warehouses.component').then(m => m.WarehousesComponent) },
  { path: 'm/preparedness/warehouses/create', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/warehouse-create.component').then(m => m.WarehouseCreateComponent) },
  { path: 'm/preparedness/inventory', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/inventory.component').then(m => m.InventoryComponent) },
  { path: 'm/preparedness/inventory/create', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/inventory-create.component').then(m => m.InventoryCreateComponent) },
  { path: 'm/preparedness/temporary-warehouses', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/temporary-warehouses.component').then(m => m.TemporaryWarehousesComponent) },
  { path: 'm/preparedness/temporary-warehouses/create', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/temporary-warehouse-create.component').then(m => m.TemporaryWarehouseCreateComponent) },
  { path: 'm/preparedness/trainings', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/training-plans.component').then(m => m.TrainingPlansComponent) },
  { path: 'm/preparedness/trainings/create', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/training-plan-create.component').then(m => m.TrainingPlanCreateComponent) },
  { path: 'm/preparedness/alert-subscriptions', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/alert-subscriptions.component').then(m => m.AlertSubscriptionsComponent) },
  { path: 'm/preparedness/anticipatory-plans', canActivate: [authGuard], loadComponent: () => import('./pages/response/anticipatory-plans.component').then(m => m.AnticipatoryPlansComponent) },
  { path: 'm/preparedness/contingency-plans', canActivate: [authGuard], loadComponent: () => import('./pages/response/contingency-plans.component').then(m => m.ContingencyPlansComponent) },
  { path: 'm/preparedness/alert-subscriptions/create', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/alert-subscription-create.component').then(m => m.AlertSubscriptionCreateComponent) },
  { path: 'm/prevention-mitigation/dashboard', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/mitigation-dashboard.component').then(m => m.MitigationDashboardComponent) },
  { path: 'm/prevention-mitigation/risk-mapping', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/gis-map.component').then(m => m.GisMapComponent) },
  { path: 'm/prevention-mitigation/risk-index', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/inform/risk-index.component').then(m => m.RiskIndexComponent) },
  { path: 'm/prevention-mitigation/hazards', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/hazards.component').then(m => m.HazardsComponent) },
  { path: 'm/prevention-mitigation/hazards/create', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/hazard-create.component').then(m => m.HazardCreateComponent) },
  { path: 'm/prevention-mitigation/hazards/:id/edit', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/hazard-edit.component').then(m => m.HazardEditComponent) },
  { path: 'm/prevention-mitigation/measures', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/measures.component').then(m => m.MeasuresComponent) },
  { path: 'm/prevention-mitigation/measures/create', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/measure-create.component').then(m => m.MeasureCreateComponent) },
  { path: 'm/prevention-mitigation/measures/:id/edit', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/measure-create.component').then(m => m.MeasureCreateComponent) },
  { path: 'm/prevention-mitigation/risk-assessments', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/risk-assessments.component').then(m => m.RiskAssessmentsComponent) },
  { path: 'm/prevention-mitigation/risk-assessments/create', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/risk-assessment-form.component').then(m => m.RiskAssessmentFormComponent) },
  { path: 'm/prevention-mitigation/risk-assessments/:id/edit', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/risk-assessment-form.component').then(m => m.RiskAssessmentFormComponent) },
  { path: 'm/prevention-mitigation/infrastructure', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/infrastructure.component').then(m => m.InfrastructureComponent) },
  { path: 'm/prevention-mitigation/infrastructure/create', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/infrastructure-create.component').then(m => m.InfrastructureCreateComponent) },
  { path: 'm/prevention-mitigation/infrastructure/:id/edit', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/infrastructure-edit.component').then(m => m.InfrastructureEditComponent) },
  { path: 'm/prevention-mitigation/past-disasters', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/past-disasters.component').then(m => m.PastDisastersComponent) },
  { path: 'm/prevention-mitigation/past-disasters/create', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/past-disaster-create.component').then(m => m.PastDisasterCreateComponent) },
  { path: 'm/prevention-mitigation/past-disasters/:id/edit', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/past-disaster-edit.component').then(m => m.PastDisasterEditComponent) },
  { path: 'm/stakeholder-portal/coordination', canActivate: [authGuard], loadComponent: () => import('./pages/response/stakeholder-coordination.component').then(m => m.StakeholderCoordinationComponent) },
  { path: 'm/stakeholder-portal/directory', canActivate: [authGuard], loadComponent: () => import('./pages/stakeholder/stakeholders.component').then(m => m.StakeholdersComponent) },
  { path: 'm/stakeholder-portal/donations', canActivate: [authGuard], loadComponent: () => import('./pages/response/stakeholder-donations.component').then(m => m.StakeholderDonationsComponent) },
  { path: 'm/stakeholder-portal/open-needs', canActivate: [authGuard], loadComponent: () => import('./pages/response/open-needs.component').then(m => m.OpenNeedsComponent) },
  { path: 'm/stakeholder-portal/support-needs', canActivate: [authGuard], loadComponent: () => import('./pages/response/support-needs.component').then(m => m.SupportNeedsComponent) },
  { path: 'm/stakeholder-portal/early-warnings', canActivate: [authGuard], loadComponent: () => import('./pages/preparedness/early-warnings.component').then(m => m.EarlyWarningsComponent) },
  { path: 'm/stakeholder-portal/one-health', canActivate: [authGuard], loadComponent: () => import('./pages/onehealth/events.component').then(m => m.OhEventsComponent) },
  { path: 'm/content-management/educational-content', canActivate: [authGuard], loadComponent: () => import('./pages/content/educational-content.component').then(m => m.EducationalContentComponent) },
  { path: 'm/reports-analytics/repository', canActivate: [authGuard], loadComponent: () => import('./pages/reports/repository-events.component').then(m => m.RepositoryEventsComponent) },
  { path: 'm/reports-analytics/repository/:id', canActivate: [authGuard], loadComponent: () => import('./pages/reports/repository-event-detail.component').then(m => m.RepositoryEventDetailComponent) },
  { path: 'm/reports-analytics/analytics', canActivate: [authGuard], loadComponent: () => import('./pages/reports/sendai-analytics.component').then(m => m.SendaiAnalyticsComponent) },
  { path: 'm/reports-analytics/early-warning-management', canActivate: [authGuard], loadComponent: () => import('./pages/reports/ew-management.component').then(m => m.EwManagementComponent) },
  { path: 'm/reports-analytics/incident-reports', canActivate: [authGuard], loadComponent: () => import('./pages/reports/incident-reports.component').then(m => m.IncidentReportsComponent) },
  { path: 'm/reports-analytics/resource-reports', canActivate: [authGuard], loadComponent: () => import('./pages/reports/resource-reports.component').then(m => m.ResourceReportsComponent) },
  { path: 'm/reports-analytics/gis-map', canActivate: [authGuard], loadComponent: () => import('./pages/mitigation/gis-map.component').then(m => m.GisMapComponent) },
  { path: 'm/user-management/approval-workflows', canActivate: [authGuard], loadComponent: () => import('./pages/settings/approval-workflows.component').then(m => m.ApprovalWorkflowsComponent) },
  { path: 'm/user-management/resource-settings', canActivate: [authGuard], loadComponent: () => import('./pages/settings/resource-catalogue.component').then(m => m.ResourceCatalogueComponent) },
  { path: 'm/user-management/incident-types', canActivate: [authGuard], data: { tab: 'types' }, loadComponent: () => import('./pages/response/settings.component').then(m => m.ResponseSettingsComponent) },
  { path: 'm/user-management/users', canActivate: [authGuard], loadComponent: () => import('./pages/settings/user-management.component').then(m => m.UserManagementComponent) },
  { path: 'm/user-management/locations', canActivate: [authGuard], loadComponent: () => import('./pages/settings/location-management.component').then(m => m.LocationManagementComponent) },
  { path: 'm/user-management/roles', canActivate: [authGuard], loadComponent: () => import('./pages/settings/roles-permissions.component').then(m => m.RolesPermissionsComponent) },
  { path: 'm/content-management/translations', canActivate: [authGuard], loadComponent: () => import('./pages/settings/translations.component').then(m => m.TranslationsComponent) },
  { path: 'm/content-management/hazard-monitor', canActivate: [authGuard], loadComponent: () => import('./pages/content/threat-monitor.component').then(m => m.ThreatMonitorComponent) },
  { path: 'm/content-management/awareness', canActivate: [authGuard], loadComponent: () => import('./pages/content/education-materials.component').then(m => m.EducationMaterialsComponent) },
  { path: 'm/content-management/agencies', canActivate: [authGuard], loadComponent: () => import('./pages/content/agencies.component').then(m => m.AgenciesComponent) },
  // Publications item manages the same disaster_risk_frameworks as Risk Frameworks — alias to that screen
  { path: 'm/content-management/publications', canActivate: [authGuard], loadComponent: () => import('./pages/content/frameworks.component').then(m => m.FrameworksComponent) },
  { path: 'm/content-management/news', canActivate: [authGuard], loadComponent: () => import('./pages/content/portal-news.component').then(m => m.PortalNewsComponent) },
  { path: 'm/content-management/portal-management', canActivate: [authGuard], loadComponent: () => import('./pages/content/portal-management.component').then(m => m.PortalManagementComponent) },
  { path: 'm/content-management/frameworks', canActivate: [authGuard], loadComponent: () => import('./pages/content/frameworks.component').then(m => m.FrameworksComponent) },
  { path: 'm/content-management/frameworks/create', canActivate: [authGuard], loadComponent: () => import('./pages/content/framework-form.component').then(m => m.FrameworkFormComponent) },
  { path: 'm/content-management/frameworks/:id/edit', canActivate: [authGuard], loadComponent: () => import('./pages/content/framework-form.component').then(m => m.FrameworkFormComponent) },
  { path: 'm/one-health/dashboard', canActivate: [authGuard], loadComponent: () => import('./pages/onehealth/dashboard.component').then(m => m.OhDashboardComponent) },
  { path: 'm/one-health/events', canActivate: [authGuard], loadComponent: () => import('./pages/onehealth/events.component').then(m => m.OhEventsComponent) },
  { path: 'm/one-health/report-event', canActivate: [authGuard], data: { openCreate: true }, loadComponent: () => import('./pages/onehealth/events.component').then(m => m.OhEventsComponent) },
  { path: 'm/one-health/directives', canActivate: [authGuard], loadComponent: () => import('./pages/onehealth/directives.component').then(m => m.OhDirectivesComponent) },
  { path: 'm/one-health/directives/:id', canActivate: [authGuard], loadComponent: () => import('./pages/onehealth/directive-show.component').then(m => m.OhDirectiveShowComponent) },
  { path: 'm/one-health/dissemination', canActivate: [authGuard], loadComponent: () => import('./pages/onehealth/disseminations.component').then(m => m.OhDisseminationsComponent) },
  { path: 'm/one-health/dissemination/:id', canActivate: [authGuard], loadComponent: () => import('./pages/onehealth/dissemination-show.component').then(m => m.OhDisseminationShowComponent) },
  { path: 'm/one-health/events/:id/actions', canActivate: [authGuard], loadComponent: () => import('./pages/onehealth/action-tracking.component').then(m => m.OhActionTrackingComponent) },
  { path: 'm/one-health/events/:id', canActivate: [authGuard], loadComponent: () => import('./pages/onehealth/event-show.component').then(m => m.OhEventShowComponent) },
  { path: 'm/response/incidents', canActivate: [authGuard], loadComponent: () => import('./pages/response/incidents.component').then(m => m.ResponseIncidentsComponent) },
  { path: 'm/response/incidents/create', canActivate: [authGuard], loadComponent: () => import('./pages/response/incident-form.component').then(m => m.IncidentFormComponent) },
  { path: 'm/response/incidents/:id/edit', canActivate: [authGuard], loadComponent: () => import('./pages/response/incident-form.component').then(m => m.IncidentFormComponent) },
  { path: 'm/response/incidents/:id', canActivate: [authGuard], loadComponent: () => import('./pages/response/incident-show.component').then(m => m.IncidentShowComponent) },
  { path: 'm/response/approvals', canActivate: [authGuard], loadComponent: () => import('./pages/response/approvals.component').then(m => m.ResponseApprovalsComponent) },
  { path: 'm/response/dispatch', canActivate: [authGuard], loadComponent: () => import('./pages/response/dispatch-console.component').then(m => m.DispatchConsoleComponent) },
  { path: 'm/response/resource-dispatch', canActivate: [authGuard], loadComponent: () => import('./pages/response/dispatch-console.component').then(m => m.DispatchConsoleComponent) },
  { path: 'm/response/dispatch-approvals', canActivate: [authGuard], data: { tab: 'approvals' }, loadComponent: () => import('./pages/response/dispatch-console.component').then(m => m.DispatchConsoleComponent) },
  { path: 'm/response/procurement', canActivate: [authGuard], data: { tab: 'procurement' }, loadComponent: () => import('./pages/response/dispatch-console.component').then(m => m.DispatchConsoleComponent) },
  { path: 'm/response/warehouse-ops', canActivate: [authGuard], loadComponent: () => import('./pages/response/warehouse-ops.component').then(m => m.WarehouseOpsComponent) },
  { path: 'm/response/donations', canActivate: [authGuard], loadComponent: () => import('./pages/response/stakeholder-donations.component').then(m => m.StakeholderDonationsComponent) },
  { path: 'm/response/support-needs', canActivate: [authGuard], loadComponent: () => import('./pages/response/support-needs.component').then(m => m.SupportNeedsComponent) },
  { path: 'm/response/assessments', canActivate: [authGuard], loadComponent: () => import('./pages/response/assessments.component').then(m => m.AssessmentsComponent) },
  { path: 'm/response/assessments/create', canActivate: [authGuard], loadComponent: () => import('./pages/response/assessment-form.component').then(m => m.AssessmentFormComponent) },
  { path: 'm/response/assessments/:id', canActivate: [authGuard], loadComponent: () => import('./pages/response/assessment-show.component').then(m => m.AssessmentShowComponent) },
  { path: 'm/recovery/needs-assessment', canActivate: [authGuard], data: { mode: 'needs' }, loadComponent: () => import('./pages/response/assessments.component').then(m => m.AssessmentsComponent) },
  { path: 'm/recovery/damage-assessments', canActivate: [authGuard], data: { mode: 'report' }, loadComponent: () => import('./pages/response/assessments.component').then(m => m.AssessmentsComponent) },
  { path: 'm/recovery/relief-distributions', canActivate: [authGuard], loadComponent: () => import('./pages/recovery/relief-distributions.component').then(m => m.ReliefDistributionsComponent) },
  { path: 'm/recovery/recovery-programs', canActivate: [authGuard], loadComponent: () => import('./pages/recovery/recovery-programs.component').then(m => m.RecoveryProgramsComponent) },
  { path: 'm/recovery/projects', canActivate: [authGuard], loadComponent: () => import('./pages/recovery/strategic-projects.component').then(m => m.StrategicProjectsComponent) },
  { path: 'm/recovery/lessons', canActivate: [authGuard], loadComponent: () => import('./pages/recovery/knowledge-repository.component').then(m => m.KnowledgeRepositoryComponent) },
  { path: 'm/content-management/communication-center', canActivate: [authGuard], loadComponent: () => import('./pages/content/communication-center.component').then(m => m.CommunicationCenterComponent) },
  // SMS & Email management are now tabs inside the Communication Center — old links redirect there (no duplicate screens).
  { path: 'm/content-management/sms-management', redirectTo: 'm/content-management/communication-center', pathMatch: 'full' },
  { path: 'm/content-management/email-management', redirectTo: 'm/content-management/communication-center', pathMatch: 'full' },
  { path: 'm/response/tasks', canActivate: [authGuard], loadComponent: () => import('./pages/response/tasks.component').then(m => m.TasksComponent) },
  { path: 'm/response/communication', canActivate: [authGuard], loadComponent: () => import('./pages/response/communication.component').then(m => m.CommunicationComponent) },
  { path: 'm/response/dashboard', canActivate: [authGuard], loadComponent: () => import('./pages/response/dashboards.component').then(m => m.ResponseDashboardComponent) },
  { path: 'm/response/eocc', canActivate: [authGuard], loadComponent: () => import('./pages/response/dashboards.component').then(m => m.EoccBoardComponent) },
  { path: 'm/response/coordination', canActivate: [authGuard], loadComponent: () => import('./pages/response/command-center.component').then(m => m.CommandCenterComponent) },
  { path: 'm/response/executive-watch', canActivate: [authGuard], loadComponent: () => import('./pages/response/executive-watch.component').then(m => m.ExecutiveWatchComponent) },
  { path: 'm/response/declarations', canActivate: [authGuard], loadComponent: () => import('./pages/response/declarations.component').then(m => m.DeclarationsComponent) },
  { path: 'm/response/public-reports', canActivate: [authGuard], loadComponent: () => import('./pages/response/public-reports.component').then(m => m.PublicReportsComponent) },
  { path: 'm/response/resource-approvals', canActivate: [authGuard], loadComponent: () => import('./pages/response/resource-allocations.component').then(m => m.ResourceAllocationsComponent) },
  { path: 'm/:slug/:item', canActivate: [authGuard], loadComponent: () => import('./pages/screen.component').then(m => m.ScreenComponent) },
  { path: 'm/:slug', canActivate: [authGuard], loadComponent: () => import('./pages/screen.component').then(m => m.ScreenComponent) },
  { path: '**', redirectTo: 'home' },
];
