/**
 * NDRF 2026 Annex 1 — Damage, Loss and Needs Assessment tool — as a data-driven schema.
 * ONE definition drives BOTH the sector keying form and the generated annex document, so
 * the printed output can never drift from what the form captured. Field labels follow the
 * official instrument (formal register); answers are stored per section as {key: value}.
 */

export interface DlnaField {
  key: string;
  label: string;
  type: 'yn' | 'ynp' | 'text' | 'textarea' | 'number' | 'select' | 'multi' | 'rows' | 'heading';
  options?: string[];
  columns?: { key: string; label: string; type?: 'text' | 'number' }[];
  /** Render/print only when another answer matches (the annex's "If yes, ..." rows). */
  showIf?: { key: string; equals: string };
  hint?: string;
}

export interface DlnaSection {
  key: string;
  no: number;
  title: string;
  fields: DlnaField[];
}

const DAMAGE_LEVELS = ['Completely damaged', 'Partially damaged', 'Marginally affected (inaccessible)', 'No damage'];

export const DLNA_SECTIONS: DlnaSection[] = [
  {
    key: 'people', no: 2, title: 'Information on Affected People', fields: [
      { key: 'h_hh', label: 'Households affected by the disaster', type: 'heading' },
      { key: 'hh_total', label: 'Households — total', type: 'number' },
      { key: 'hh_male_headed', label: 'Male-headed households', type: 'number' },
      { key: 'hh_female_headed', label: 'Female-headed households', type: 'number' },
      { key: 'h_people', label: 'People affected by the disaster', type: 'heading' },
      { key: 'children_total', label: 'Children — total', type: 'number' },
      { key: 'children_female', label: 'Children — female', type: 'number' },
      { key: 'children_male', label: 'Children — male', type: 'number' },
      { key: 'under5_total', label: 'Children under 5 years — total', type: 'number' },
      { key: 'under5_female', label: 'Children under 5 — female', type: 'number' },
      { key: 'under5_male', label: 'Children under 5 — male', type: 'number' },
      { key: 'adult_total', label: 'Adults — total', type: 'number' },
      { key: 'adult_female', label: 'Adults — female', type: 'number' },
      { key: 'adult_male', label: 'Adults — male', type: 'number' },
      { key: 'pregnant_women', label: 'Pregnant women', type: 'number' },
      { key: 'lactating_women', label: 'Lactating women', type: 'number' },
      { key: 'elderly_total', label: 'Elderly — total', type: 'number' },
      { key: 'disabilities', label: 'People with disability (by type)', type: 'rows',
        columns: [{ key: 'type', label: 'Type of disability' }, { key: 'total', label: 'Total', type: 'number' },
          { key: 'female', label: 'Female', type: 'number' }, { key: 'male', label: 'Male', type: 'number' }],
        hint: 'Physically / Visually / Hearing / Intellectually impaired, Albinism, Multiple, Other' },
      { key: 'h_displacement', label: 'Displacement and relocation', type: 'heading' },
      { key: 'displaced', label: 'Have people been displaced / relocated?', type: 'yn' },
      { key: 'relocation_sites', label: 'Name of relocation sites / camp', type: 'text', showIf: { key: 'displaced', equals: 'Yes' } },
      { key: 'relocated_total', label: 'People relocated — total', type: 'number', showIf: { key: 'displaced', equals: 'Yes' } },
      { key: 'relocated_men', label: 'Relocated — men', type: 'number', showIf: { key: 'displaced', equals: 'Yes' } },
      { key: 'relocated_women', label: 'Relocated — women', type: 'number', showIf: { key: 'displaced', equals: 'Yes' } },
      { key: 'relocated_children_5_17', label: 'Relocated — children 5–17', type: 'number', showIf: { key: 'displaced', equals: 'Yes' } },
      { key: 'relocated_children_u5', label: 'Relocated — children below 5', type: 'number', showIf: { key: 'displaced', equals: 'Yes' } },
      { key: 'hosted_where', label: 'Where are they hosted?', type: 'multi',
        options: ['Friends/relatives’ houses', 'Church/Mosque', 'School', 'Other public building', 'Open space'],
        showIf: { key: 'displaced', equals: 'Yes' } },
      { key: 'host_support', label: 'Are they being supported by the host communities?', type: 'yn', showIf: { key: 'displaced', equals: 'Yes' } },
      { key: 'host_support_type', label: 'If yes, how / what type of support?', type: 'text', showIf: { key: 'host_support', equals: 'Yes' } },
      { key: 'host_support_duration', label: 'For how long (weeks, months)?', type: 'text', showIf: { key: 'host_support', equals: 'Yes' } },
      { key: 'h_loss', label: 'General degree of loss and damage at household level', type: 'heading' },
      { key: 'loss_completely', label: 'Households completely destroyed', type: 'number' },
      { key: 'loss_partially', label: 'Households partially destroyed', type: 'number' },
      { key: 'loss_marginally', label: 'Households marginally affected (loss of some assets)', type: 'number' },
    ],
  },
  {
    key: 'nfi', no: 3, title: 'Non-Food Items', fields: [
      { key: 'nfi_needs', label: 'Non-food item needs', type: 'rows',
        columns: [{ key: 'item', label: 'Item' }, { key: 'quantity', label: 'Quantity needed', type: 'number' },
          { key: 'remarks', label: 'Remarks' }],
        hint: 'e.g. tarpaulins, blankets, kitchen sets, jerry cans, solar lamps, dignity kits' },
      { key: 'nfi_notes', label: 'Notes on non-food items already distributed or pledged', type: 'textarea' },
    ],
  },
  {
    key: 'wash', no: 4, title: 'Water, Sanitation and Hygiene', fields: [
      { key: 'h_water', label: 'Water', type: 'heading' },
      { key: 'water_access', label: 'Do people have access to safe and clean water?', type: 'yn' },
      { key: 'water_sources', label: 'What are the water sources?', type: 'text' },
      { key: 'water_distance_km', label: 'Estimated distance to the nearest water source (km)', type: 'number' },
      { key: 'water_system_affected', label: 'Has the water supply system / sources been affected by the disaster?', type: 'yn' },
      { key: 'water_points_sufficient', label: 'Are there sufficient water supply points (taps, kiosks, wells) for the population?', type: 'yn' },
      { key: 'water_distribution', label: 'Is the water distribution system functional?', type: 'ynp' },
      { key: 'water_capacity_vs_pre', label: 'Current capacity of the water supply system compared to pre-emergency capacity', type: 'text' },
      { key: 'water_storage', label: 'Are there water storage facilities?', type: 'yn' },
      { key: 'water_storage_condition', label: 'If yes, mention and identify their condition', type: 'text', showIf: { key: 'water_storage', equals: 'Yes' } },
      { key: 'water_damage_scale', label: 'Scale of damage to water facilities', type: 'select',
        options: ['Minor damage', 'Moderate damage', 'Severe damage'] },
      { key: 'water_tested', label: 'Has the water been tested for quality (e.g. bacterial contamination)?', type: 'yn' },
      { key: 'water_test_results', label: 'If yes, what are the results?', type: 'text', showIf: { key: 'water_tested', equals: 'Yes' } },
      { key: 'water_treated', label: 'Is the water being treated for safety (chlorination, filtration)?', type: 'yn' },
      { key: 'purification_supplies', label: 'Are adequate water purification tablets/solutions available for households?', type: 'yn' },
      { key: 'contamination_risk', label: 'Is there any risk of water contamination?', type: 'yn' },
      { key: 'contamination_sources', label: 'If yes, main sources of contamination (floods, sewage, industrial waste…)', type: 'text', showIf: { key: 'contamination_risk', equals: 'Yes' } },
      { key: 'waterborne_outbreak', label: 'Significant occurrence/increase of water-related disease outbreak since the disaster?', type: 'yn' },
      { key: 'outbreak_diseases', label: 'If yes, select', type: 'multi', options: ['Cholera', 'Dysentery', 'Typhoid', 'Other'],
        showIf: { key: 'waterborne_outbreak', equals: 'Yes' } },
      { key: 'h_sanitation', label: 'Sanitation', type: 'heading' },
      { key: 'sewage_damage', label: 'Is there any damage to sewage systems?', type: 'yn' },
      { key: 'sewage_scale', label: 'If yes, at what scale?', type: 'select',
        options: ['Completely damaged', 'Partially damaged', 'Marginally (inaccessible) affected'],
        showIf: { key: 'sewage_damage', equals: 'Yes' } },
      { key: 'hazardous_sewage', label: 'Hazardous sewage conditions (overflowing pits, damaged pipes) posing public-health risk?', type: 'yn' },
      { key: 'hazardous_sewage_explain', label: 'If yes, explain', type: 'text', showIf: { key: 'hazardous_sewage', equals: 'Yes' } },
      { key: 'sewage_measures', label: 'Emergency measures in place for sewage overflow / wastewater disposal', type: 'textarea' },
      { key: 'latrines', label: 'Available latrines — type and number', type: 'rows',
        columns: [{ key: 'type', label: 'Type' }, { key: 'number', label: 'Number', type: 'number' }],
        hint: 'Indirect pit-pour flush with pan and pipe / Direct pit / Common community latrine / Open space' },
      { key: 'latrine_condition', label: 'Condition of the latrines', type: 'select',
        options: ['Fully functional', 'Needs repair', 'Non-functional'] },
      { key: 'latrines_disabled', label: 'Are latrines accessible for people with disabilities?', type: 'yn' },
      { key: 'latrines_vulnerable', label: 'Do latrines meet the needs of vulnerable populations (elderly, children, disabled)?', type: 'yn' },
      { key: 'latrines_separated', label: 'Are latrines for men and women separated?', type: 'yn' },
      { key: 'h_hygiene', label: 'Hygiene', type: 'heading' },
      { key: 'mhm_facilities', label: 'Are menstrual hygiene management (MHM) facilities in place?', type: 'yn' },
      { key: 'nappies', label: 'Are there nappies/diapers for babies?', type: 'yn' },
    ],
  },
  {
    key: 'health', no: 5, title: 'Health', fields: [
      { key: 'facilities', label: 'Functioning health facilities in the area', type: 'rows',
        columns: [{ key: 'type', label: 'Type of health facility' }, { key: 'functioning', label: 'Functioning (Yes/No)' },
          { key: 'number', label: 'Number', type: 'number' }, { key: 'distance_km', label: 'Distance from disaster area (km)', type: 'number' }],
        hint: 'Regional Hospital / District Hospital / Dispensary / Private clinic / Temporary field medical post' },
      { key: 'health_access', label: 'Do people have access to health facilities?', type: 'yn' },
      { key: 'accessible_list', label: 'Which health facilities are accessible? (list)', type: 'textarea' },
      { key: 'facilities_nonfunctional', label: 'Facilities damaged and non-functional after the disaster', type: 'number' },
      { key: 'facilities_inaccessible', label: 'Facilities not damaged but inaccessible', type: 'number' },
      { key: 'facility_resources', label: 'Functional health facilities have the following resources/services', type: 'multi',
        options: ['Vaccines', 'Medical staff', 'Community Health Workers (CHWs)', 'Essential medicine',
          'Childbirth', 'Emergency kit / Trauma kit', 'Space for isolation'] },
      { key: 'epidemic_risk', label: 'Is there a risk of an epidemic/outbreak?', type: 'yn' },
      { key: 'epidemic_type', label: 'If yes, which type?', type: 'multi',
        options: ['Respiratory Infections', 'Contact Diseases', 'Droplet Infections'],
        showIf: { key: 'epidemic_risk', equals: 'Yes' } },
      { key: 'epidemic_diseases', label: 'Mention the disease(s)', type: 'text', showIf: { key: 'epidemic_risk', equals: 'Yes' } },
      { key: 'h_deceased', label: 'Management of deceased individuals', type: 'heading' },
      { key: 'morgue_facilities', label: 'Mortuary/morgue facilities — number', type: 'number' },
      { key: 'mortuary_staff', label: 'Available mortuary staff', type: 'yn' },
      { key: 'burial_sites', label: 'Available public burial sites', type: 'yn' },
      { key: 'burial_teams', label: 'Trained burial teams', type: 'yn' },
      { key: 'urgent_health_needs', label: 'What are the urgent health needs?', type: 'textarea' },
    ],
  },
  {
    key: 'food', no: 6, title: 'Food Security and Livelihood', fields: [
      { key: 'h_distribution', label: 'Food distribution', type: 'heading' },
      { key: 'food_assistance', label: 'Is food assistance already provided in the affected area?', type: 'yn' },
      { key: 'foods_provided', label: 'If yes, what foods are being provided?', type: 'multi',
        options: ['Cereals (rice, maize/maize flour)', 'Pulses (beans, peas)', 'Cooking oil', 'Salt', 'Sugar'],
        showIf: { key: 'food_assistance', equals: 'Yes' } },
      { key: 'food_fortified', label: 'Is the food fortified?', type: 'yn', showIf: { key: 'food_assistance', equals: 'Yes' } },
      { key: 'fortified_which', label: 'If yes, what food is fortified?', type: 'text', showIf: { key: 'food_fortified', equals: 'Yes' } },
      { key: 'h_consumption', label: 'Food consumption', type: 'heading' },
      { key: 'consumption_change', label: 'On average, has the quantity of food people are eating changed since the crisis?', type: 'select',
        options: ['More food consumed', 'Same amount consumed', 'Less food consumed'] },
      { key: 'groups_less', label: 'If less, which population groups are consuming less food?', type: 'multi',
        options: ['Children under 5 years', 'School-aged children and adolescents (5–19 years)',
          'Pregnant and breastfeeding women', 'Adults (non-pregnant, non-breastfeeding)', 'All household members'],
        showIf: { key: 'consumption_change', equals: 'Less food consumed' } },
      { key: 'why_less', label: 'Why are people consuming less food?', type: 'textarea', showIf: { key: 'consumption_change', equals: 'Less food consumed' } },
      { key: 'h_availability', label: 'Food availability and access', type: 'heading' },
      { key: 'hh_with_stocks', label: 'People/households currently with food stocks', type: 'number' },
      { key: 'stock_duration_days', label: 'Estimated total duration of coverage (days)', type: 'number' },
      { key: 'market_access', label: 'Do households have access to markets?', type: 'yn' },
      { key: 'market_distance', label: 'If yes, walking time/distance to the nearest market (hrs/km)', type: 'text', showIf: { key: 'market_access', equals: 'Yes' } },
      { key: 'market_affected', label: 'Has access to the market been affected by the disaster?', type: 'yn' },
      { key: 'market_affected_how', label: 'If yes, how?', type: 'text', showIf: { key: 'market_affected', equals: 'Yes' } },
      { key: 'urgent_food_needs', label: 'What are the urgent food item needs?', type: 'textarea' },
      { key: 'h_nutrition', label: 'Nutrition', type: 'heading' },
      { key: 'malnutrition', label: 'Is there evidence of malnutrition?', type: 'yn' },
      { key: 'malnutrition_severity', label: 'If yes, moderate or severe?', type: 'select', options: ['Moderate', 'Severe'],
        showIf: { key: 'malnutrition', equals: 'Yes' } },
      { key: 'creni', label: 'Are there Intensive Nutritional Rehabilitation Centres (CRENI)?', type: 'yn' },
      { key: 'crena', label: 'Are there Outpatient Nutritional Rehabilitation Centres (CRENA)?', type: 'yn' },
      { key: 'centres_affected', label: 'Were the Nutritional Rehabilitation Centres affected by the disaster?', type: 'yn' },
      { key: 'centres_affected_how', label: 'If yes, how? State number affected', type: 'text', showIf: { key: 'centres_affected', equals: 'Yes' } },
      { key: 'urgent_nutrition_needs', label: 'What are the urgent nutritional needs?', type: 'textarea' },
      { key: 'nutrition_source', label: 'Source of nutrition information', type: 'text' },
    ],
  },
  {
    key: 'education', no: 7, title: 'Education', fields: [
      { key: 'spaces_affected', label: 'Are there learning spaces affected by the disaster?', type: 'yn' },
      { key: 'schools_affected', label: 'Number of schools affected', type: 'rows',
        columns: [{ key: 'level', label: 'Level' }, { key: 'number', label: 'Number affected', type: 'number' },
          { key: 'out_of_total', label: 'Out of total', type: 'number' }],
        hint: 'Pre-Primary School / Primary School / Secondary School / College/University' },
      { key: 'students_teachers_affected', label: 'Are there students/teachers affected by the disaster?', type: 'yn' },
      { key: 'students_total', label: 'Students affected — total', type: 'number', showIf: { key: 'students_teachers_affected', equals: 'Yes' } },
      { key: 'students_female', label: 'Students — female', type: 'number', showIf: { key: 'students_teachers_affected', equals: 'Yes' } },
      { key: 'students_male', label: 'Students — male', type: 'number', showIf: { key: 'students_teachers_affected', equals: 'Yes' } },
      { key: 'students_disabled', label: 'Students — with disability', type: 'number', showIf: { key: 'students_teachers_affected', equals: 'Yes' } },
      { key: 'teachers_total', label: 'Teachers affected — total', type: 'number', showIf: { key: 'students_teachers_affected', equals: 'Yes' } },
      { key: 'teachers_female', label: 'Teachers — female', type: 'number', showIf: { key: 'students_teachers_affected', equals: 'Yes' } },
      { key: 'teachers_male', label: 'Teachers — male', type: 'number', showIf: { key: 'students_teachers_affected', equals: 'Yes' } },
      { key: 'building_damage', label: 'Level of damage to school buildings', type: 'select', options: DAMAGE_LEVELS },
      { key: 'equipment_damage', label: 'Level of damage to equipment and educational material', type: 'select',
        options: ['Totally damaged', 'Partially damaged', 'No damage'] },
      { key: 'classes_suspended', label: 'Have any schools suspended classes due to the disaster?', type: 'yn' },
      { key: 'suspended_pre', label: 'Suspended — pre-primary schools', type: 'number', showIf: { key: 'classes_suspended', equals: 'Yes' } },
      { key: 'suspended_primary', label: 'Suspended — primary schools', type: 'number', showIf: { key: 'classes_suspended', equals: 'Yes' } },
      { key: 'suspended_secondary', label: 'Suspended — secondary schools', type: 'number', showIf: { key: 'classes_suspended', equals: 'Yes' } },
      { key: 'suspended_college', label: 'Suspended — universities/colleges', type: 'number', showIf: { key: 'classes_suspended', equals: 'Yes' } },
      { key: 'no_access', label: 'Are there students without access to school after the disaster?', type: 'yn' },
      { key: 'no_access_female', label: 'If yes — female', type: 'number', showIf: { key: 'no_access', equals: 'Yes' } },
      { key: 'no_access_male', label: 'If yes — male', type: 'number', showIf: { key: 'no_access', equals: 'Yes' } },
      { key: 'no_access_reason', label: 'What could be the reason?', type: 'textarea', showIf: { key: 'no_access', equals: 'Yes' } },
      { key: 'alt_places', label: 'Are there buildings or alternative places for learning (open spaces, church, mosque)?', type: 'yn' },
      { key: 'alt_places_mention', label: 'If yes, mention', type: 'text', showIf: { key: 'alt_places', equals: 'Yes' } },
      { key: 'stress_evidence', label: 'Evidence that teachers and students have stress, trauma or other psychological challenges?', type: 'yn' },
      { key: 'recreation', label: 'Are there opportunities for children to engage in recreation or extracurricular activities?', type: 'yn' },
      { key: 'psych_programs', label: 'Existing programmes providing psychological support in schools / learning spaces?', type: 'yn' },
      { key: 'psych_programs_mention', label: 'If yes, mention', type: 'text', showIf: { key: 'psych_programs', equals: 'Yes' } },
    ],
  },
  {
    key: 'protection', no: 8, title: 'Protection', fields: [
      { key: 'shelters_near', label: 'Are there available shelters near the affected area?', type: 'yn' },
      { key: 'shelters_separated', label: 'Are shelters separated for marginalized/vulnerable groups?', type: 'yn' },
      { key: 'vulnerable_identified', label: 'Have marginalized/vulnerable groups been identified?', type: 'yn' },
      { key: 'vulnerable_groups', label: 'If yes, which ones?', type: 'rows',
        columns: [{ key: 'group', label: 'Group (e.g. children <5)' }, { key: 'age', label: 'Age' }, { key: 'sex', label: 'Sex' }],
        showIf: { key: 'vulnerable_identified', equals: 'Yes' } },
      { key: 'protection_risks', label: 'Is there protection against risks/threats?', type: 'yn' },
      { key: 'law_enforcement', label: 'Are law enforcement agencies, NGOs or individuals providing protection to children and other vulnerable groups?', type: 'yn' },
      { key: 'discrimination', label: 'Existence of discrimination / marginalization?', type: 'yn' },
      { key: 'discrimination_mention', label: 'If yes, mention', type: 'text', showIf: { key: 'discrimination', equals: 'Yes' } },
      { key: 'family_separated', label: 'Individuals separated from family members?', type: 'yn' },
      { key: 'family_separated_who', label: 'If yes, mention (mother, child, father…)', type: 'text', showIf: { key: 'family_separated', equals: 'Yes' } },
      { key: 'barriers', label: 'Barriers for marginalized groups (women/elderly/children) with specific needs to access basic services?', type: 'yn' },
      { key: 'gbv_risk', label: 'Risks of GBV / child-abuse occurrence?', type: 'yn' },
      { key: 'tension_factors', label: 'What factors increase tensions?', type: 'textarea' },
      { key: 'reporting_aware', label: 'Are people aware of how and where to report protection concerns?', type: 'yn' },
      { key: 'safe_channels', label: 'Safe and confidential reporting channels (incl. sexual exploitation and abuse)?', type: 'yn' },
      { key: 'h_mhpss', label: 'Mental health and psychosocial issues', type: 'heading' },
      { key: 'mhpss_disruption', label: 'Evidence of daily life disrupted by psychosocial symptoms (anxiety, suicides, failure to eat/sleep, alcohol/drug abuse, GBV, child abuse)?', type: 'yn' },
      { key: 'mhpss_disruption_mention', label: 'If yes, mention', type: 'text', showIf: { key: 'mhpss_disruption', equals: 'Yes' } },
      { key: 'mhpss_trained', label: 'Is the district MHPSS team trained to provide services?', type: 'yn' },
      { key: 'mhpss_engaged', label: 'Is the MHPSS team actively providing services to the affected population?', type: 'yn' },
      { key: 'welfare_officers', label: 'Social Welfare Officers / mental-health experts available to support MHPSS response', type: 'number' },
    ],
  },
  {
    key: 'infrastructure', no: 9, title: 'Building, Infrastructure and Settlements / Land Use', fields: [
      { key: 'gov_buildings', label: 'Government buildings affected (mention)', type: 'textarea' },
      { key: 'community_buildings', label: 'Community/public buildings affected (churches, mosques, temples…)', type: 'textarea' },
      { key: 'buildings_completely', label: 'Buildings completely damaged — number', type: 'number' },
      { key: 'buildings_partially', label: 'Buildings partially damaged — number', type: 'number' },
      { key: 'roads', label: 'Roads damaged/destroyed', type: 'rows',
        columns: [{ key: 'location', label: 'Location' }, { key: 'km', label: 'KM', type: 'number' }, { key: 'condition', label: 'Condition' }] },
      { key: 'railway_location', label: 'Railways damaged — location', type: 'text' },
      { key: 'railway_km', label: 'Railways damaged — KM', type: 'number' },
      { key: 'railway_working', label: 'Is the railway still working?', type: 'yn' },
      { key: 'bridges', label: 'Bridges damaged/collapsed', type: 'rows',
        columns: [{ key: 'location', label: 'Location' }, { key: 'isolated', label: 'Village/street isolated' }] },
      { key: 'comm_damage', label: 'Damage to communication networks', type: 'select', options: DAMAGE_LEVELS },
      { key: 'electricity_damage', label: 'Damage to electricity network', type: 'select', options: DAMAGE_LEVELS },
      { key: 'telecom_damage', label: 'Damage to telecommunication network', type: 'select', options: DAMAGE_LEVELS },
      { key: 'plots_affected', label: 'Plots affected (residential/hotels/industry/farms…) — total', type: 'number' },
      { key: 'alt_land_temp', label: 'Availability of alternative land for temporary settlements?', type: 'yn' },
      { key: 'alt_land_temp_acres', label: 'If yes, how many acres?', type: 'number', showIf: { key: 'alt_land_temp', equals: 'Yes' } },
      { key: 'alt_land_perm', label: 'Availability of alternative land for permanent settlements?', type: 'yn' },
      { key: 'alt_land_perm_acres', label: 'If yes, how many acres?', type: 'number', showIf: { key: 'alt_land_perm', equals: 'Yes' } },
      { key: 'hazard_area_props', label: 'Properties/buildings in areas previously identified as hazardous / disaster-prone?', type: 'yn' },
      { key: 'blocked_waterways', label: 'Defined waterways blocked by settlements/houses?', type: 'yn' },
      { key: 'escape_routes', label: 'Identified and demarcated escape routes, emergency/assembly points?', type: 'yn' },
    ],
  },
  {
    key: 'environment', no: 10, title: 'Environment', fields: [
      { key: 'general_effect', label: 'How has this disaster affected the environment in general?', type: 'textarea' },
      { key: 'air_pollutants', label: 'Pollutants, dust or chemical releases affecting air quality?', type: 'yn' },
      { key: 'respiratory_risk', label: 'If yes, respiratory health risks for humans and wildlife?', type: 'yn', showIf: { key: 'air_pollutants', equals: 'Yes' } },
      { key: 'debris', label: 'Sudden accumulation of debris, including hazardous materials?', type: 'yn' },
      { key: 'wildlife_displaced', label: 'Wildlife displaced, increasing risk of human–wildlife conflict?', type: 'yn' },
      { key: 'zoonotic', label: 'Concerns about zoonotic diseases due to closer proximity to wildlife?', type: 'yn' },
      { key: 'cooking_energy', label: 'Rank the most used cooking energy sources in the locality', type: 'rows',
        columns: [{ key: 'source', label: 'Source' }, { key: 'rank', label: 'Rank', type: 'number' }],
        hint: 'Wood / Charcoal / Gas / Other' },
      { key: 'chem_facilities', label: 'Disaster damaged chemical plants, fuel storage or waste facilities, spreading hazardous materials?', type: 'yn' },
      { key: 'leaks', label: 'Chemical leaks or oil spills from damaged facilities?', type: 'yn' },
      { key: 'coastal_pollution', label: 'If yes, has pollution affected coastal areas, marine life or nearby communities?', type: 'yn', showIf: { key: 'leaks', equals: 'Yes' } },
      { key: 'waste_mgmt', label: 'How is waste being managed to prevent water and soil contamination?', type: 'textarea' },
      { key: 'hazardous_disposal', label: 'Adequate facilities for safely disposing of hazardous waste?', type: 'yn' },
      { key: 'blocked_waterways_flood', label: 'Has the disaster blocked waterways, creating potential flood risks?', type: 'yn' },
      { key: 'wetlands_damaged', label: 'Sensitive areas like wetlands or natural habitats damaged?', type: 'yn' },
    ],
  },
  {
    key: 'rcce', no: 11, title: 'Risk Communication and Community Engagement', fields: [
      { key: 'rcce_initiated', label: 'Was risk communication and community engagement initiated after the disaster?', type: 'yn' },
      { key: 'community_heard', label: 'Has the community heard news or information related to the disaster?', type: 'yn' },
      { key: 'channels', label: 'Most preferred channels of communication', type: 'multi',
        options: ['Radio', 'TV', 'Community Health Worker', 'Religious Leader', 'Other'] },
      { key: 'channel_other', label: 'Other channel — specify', type: 'text' },
      { key: 'aware_measures', label: 'Are community members aware of protective measures for the disaster?', type: 'yn' },
      { key: 'aware_measures_mention', label: 'If yes, mention', type: 'text', showIf: { key: 'aware_measures', equals: 'Yes' } },
    ],
  },
  {
    key: 'assistance', no: 12, title: 'Assistance Already Obtained and Outstanding Risks', fields: [
      { key: 'assistance_obtained', label: 'What assistance has already been obtained?', type: 'rows',
        columns: [{ key: 'category', label: 'Category' }, { key: 'assistance', label: 'Assistance obtained' }],
        hint: 'Search and rescue / Shelter / Food security & livelihoods / Education / Nutrition / Health / Building & infrastructure / Water and sanitation / Protection / Other' },
      { key: 'other_risks', label: 'What other risks are posed by the current disaster?', type: 'textarea' },
      { key: 'other_responses', label: 'Mention other current responses to the disaster', type: 'textarea' },
    ],
  },
];

/** Answer → display string for the generated annex document. */
export function dlnaDisplay(field: DlnaField, value: any): string {
  if (value === null || value === undefined || value === '' || (Array.isArray(value) && !value.length)) { return '—'; }
  if (Array.isArray(value)) { return value.join(', '); }
  return String(value);
}
