-- INFORM core schema for the DMIS platform (PostgreSQL).

-- The indicator REGISTRY (data-driven model: add a parameter = insert a row, no code change).
create table public.inform_indicator (
    id            varchar(64) primary key,
    dimension     varchar(64),
    category      varchar(128),
    component     varchar(128),
    owner         varchar(32),                 -- owning institution acronym
    keyed_at      varchar(16),                 -- National | Adm1 | Adm2 | Council  (native resolution)
    transform     varchar(24)  default 'None', -- None | Logarithm | Exponential
    resolved_min  double precision,            -- frozen reference range (not recomputed)
    resolved_max  double precision,
    sign          varchar(24),                 -- Increase Risk | Decrease Risk
    weight        double precision default 1,  -- 1 = normal SADC; advanced baskets carry weights
    use_flag      varchar(8)   default 'Yes',
    tier          varchar(16)  default 'normal',-- normal | advanced
    denominator   varchar(64)  default 'None',
    outlier       varchar(8)   default 'No',
    fence_lo      double precision,
    fence_hi      double precision,
    name          varchar(256)
);

-- Administrative areas (national / region / district / council), reconciled to official PMO council codes.
create table public.inform_area (
    code          varchar(32) primary key,     -- INFORM area code (e.g. C001) or pcode
    name          varchar(160),
    level         varchar(16),                  -- national | region | district | council
    parent_code   varchar(32),
    council_code  varchar(40),                  -- official PMO council_code (councils only)
    region        varchar(96)
);

-- A keyed indicator value at its native resolution; values resolve DOWN to councils at compute time.
create table public.inform_indicator_value (
    id            bigint generated by default as identity primary key,
    indicator_id  varchar(64) references public.inform_indicator(id),
    area_code     varchar(32),
    level         varchar(16),                  -- the resolution this value is keyed at
    raw_value     double precision,             -- natural unit (the operator keys this)
    value_0_10    double precision,             -- the locked standardiser output
    submitted_by  varchar(128),
    owner         varchar(32),
    status        varchar(16) default 'approved',
    is_latest     boolean     default true,
    ts            timestamp   default current_timestamp,
    approved_by   varchar(128),                 -- who signed off (separate from the keyer, not concatenated)
    approved_at   timestamp,
    version       bigint      default 0          -- JPA optimistic lock (concurrent-approve guard)
);
create index ix_inform_value on public.inform_indicator_value (indicator_id, area_code, is_latest);
create index ix_inform_ind_owner on public.inform_indicator (owner);
create index ix_inform_ind_tier on public.inform_indicator (tier);
create unique index ux_inform_value_latest on public.inform_indicator_value (indicator_id, area_code) where is_latest;
