-- The existing risk_assessments table (create 2025_06_03_130933 + enhanced 2025_09_17_224519 +
-- SRS 2025_09_18_064809), mirrored for the local database with the enum CHECK constraints Laravel's
-- enum() generates. IF NOT EXISTS keeps production untouched.
CREATE TABLE IF NOT EXISTS public.risk_assessments (
    id BIGSERIAL PRIMARY KEY,
    assessment_code VARCHAR(255),
    plan_type VARCHAR(255),
    assessment_title VARCHAR(255) NOT NULL,
    hazard_id BIGINT NOT NULL REFERENCES public.hazards(id) ON DELETE CASCADE,
    location_name VARCHAR(255) NOT NULL,
    district_council VARCHAR(255),
    ward VARCHAR(255),
    village VARCHAR(255),
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    population_at_risk INTEGER,
    households_affected INTEGER,
    vulnerable_groups JSON,
    risk_level VARCHAR(255) NOT NULL,
    likelihood VARCHAR(255) NOT NULL,
    severity_of_impact VARCHAR(255) NOT NULL,
    risk_matrix JSON,
    impact_description TEXT,
    economic_impact NUMERIC(15,2),
    critical_infrastructure JSON,
    environmental_impact JSON,
    existing_controls TEXT,
    early_warning_systems TEXT,
    evacuation_plan TEXT,
    stakeholders JSON,
    recommended_actions TEXT,
    mitigation_budget NUMERIC(15,2),
    funding_source VARCHAR(255),
    assessment_date DATE NOT NULL,
    assessed_by VARCHAR(255),
    review_date DATE,
    assessment_status VARCHAR(255) NOT NULL DEFAULT 'draft'
        CHECK (assessment_status IN ('draft', 'under_review', 'approved', 'published')),
    approved_by BIGINT,
    approved_date TIMESTAMPTZ,
    attachments JSON,
    maps_coordinates JSON,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    priority_level INTEGER,
    lessons_learned TEXT,
    coverage_regions JSON,
    sectors JSON,
    timeframe VARCHAR(255),
    risk_maps JSON,
    hazard_maps JSON,
    media_files JSON,
    knowledge_type VARCHAR(255)
        CHECK (knowledge_type IN ('case_study', 'best_practice', 'lesson_learned', 'research_report', 'technical_guide')),
    narrative_description TEXT,
    key_lessons JSON,
    implementation_period VARCHAR(255),
    challenges_encountered TEXT,
    success_factors TEXT,
    recommendations TEXT,
    awareness_type VARCHAR(255),
    target_audience VARCHAR(255),
    education_planning JSON,
    category_tags JSON,
    author VARCHAR(255),
    visibility_level VARCHAR(255) NOT NULL DEFAULT 'internal'
        CHECK (visibility_level IN ('public', 'restricted', 'internal')),
    delivery_channels JSON,
    is_post_disaster BOOLEAN NOT NULL DEFAULT FALSE,
    repository_entry_id VARCHAR(255) UNIQUE,
    historical_data JSON,
    submitted_for_approval_at TIMESTAMPTZ,
    reviewed_at TIMESTAMPTZ,
    reviewed_by BIGINT,
    review_comments TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    version_history JSON,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS risk_assessments_assessment_code_index ON public.risk_assessments (assessment_code);
CREATE INDEX IF NOT EXISTS risk_assessments_risk_level_index ON public.risk_assessments (risk_level);
CREATE INDEX IF NOT EXISTS risk_assessments_assessment_status_index ON public.risk_assessments (assessment_status);
