-- Institution registry, policy-role M&E scoping and disaster-management glossary.
-- The provided stakeholder workbooks are imported by the local reference seeder into the existing
-- agencies/stakeholders registries. This migration adds the governance fields those imports need, and adds
-- policy-derived sector indicators so an MDA focal can enter/control only indicators matching its mandate.

alter table public.agencies
    add column if not exists institution_class varchar(120),
    add column if not exists institution_subclass varchar(160),
    add column if not exists sector_tags text,
    add column if not exists disaster_roles jsonb not null default '[]'::jsonb,
    add column if not exists me_required boolean not null default false,
    add column if not exists source_register varchar(160),
    add column if not exists source_file varchar(255),
    add column if not exists source_sheet varchar(160),
    add column if not exists source_row integer,
    add column if not exists source_reference text,
    add column if not exists policy_role_code varchar(90),
    add column if not exists role_summary text;

alter table public.stakeholders
    add column if not exists institution_class varchar(120),
    add column if not exists institution_subclass varchar(160),
    add column if not exists sector_tags text,
    add column if not exists disaster_roles jsonb not null default '[]'::jsonb,
    add column if not exists me_required boolean not null default false,
    add column if not exists source_register varchar(160),
    add column if not exists source_file varchar(255),
    add column if not exists source_sheet varchar(160),
    add column if not exists source_row integer,
    add column if not exists source_reference text,
    add column if not exists policy_role_code varchar(90),
    add column if not exists role_summary text;

create index if not exists idx_agencies_institution_class on public.agencies(institution_class);
create index if not exists idx_agencies_sector_tags on public.agencies using gin(to_tsvector('simple', coalesce(sector_tags,'')));
create index if not exists idx_stakeholders_institution_class on public.stakeholders(institution_class);
create index if not exists idx_stakeholders_sector_tags on public.stakeholders using gin(to_tsvector('simple', coalesce(sector_tags,'')));

alter table public.me_indicator_catalog
    add column if not exists applicable_sectors text,
    add column if not exists applicable_institution_classes text,
    add column if not exists policy_role_code varchar(90),
    add column if not exists policy_role_source text,
    add column if not exists role_summary text;

create index if not exists idx_me_indicator_applicable_sectors
    on public.me_indicator_catalog using gin(to_tsvector('simple', coalesce(applicable_sectors,'')));

create table if not exists public.institution_policy_roles (
    id bigserial primary key,
    role_code varchar(90) not null unique,
    actor_label_en varchar(255) not null,
    actor_label_sw varchar(255),
    institution_class varchar(120),
    sector_tags text,
    responsibility_en text not null,
    responsibility_sw text,
    default_indicator_codes text,
    source_reference text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.disaster_glossary_terms (
    id bigserial primary key,
    term_en varchar(180) not null,
    term_sw varchar(180) not null,
    definition_en text,
    definition_sw text,
    source_reference text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (term_en, term_sw)
);

with roles(role_code, actor_label_en, actor_label_sw, institution_class, sector_tags,
           responsibility_en, responsibility_sw, default_indicator_codes, source_reference) as (
  values
    ('POLICY_PMO_DMD', 'Ministry responsible for disaster management', 'Wizara yenye dhamana ya usimamizi wa maafa',
     'Ministry', 'Disaster Management Coordination',
     'Oversee, coordinate and facilitate implementation of the National Disaster Management Policy, including stakeholder coordination, EOCC readiness, response equipment and national M&E.',
     'Kusimamia, kuratibu na kuwezesha utekelezaji wa Sera ya Taifa ya Usimamizi wa Maafa, ikijumuisha uratibu wa wadau, utayari wa EOCC, vifaa vya kukabiliana na maafa na Ufuatiliaji na Tathmini ya kitaifa.',
     'PMO_SP_2026_2031_MILESTONE,PMO_EOCC_READINESS,POLICY_STAKEHOLDER_PLATFORM_COORDINATED',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.1'),
    ('POLICY_PORALG', 'Ministry responsible for Regional Administration and Local Government Authorities',
     'Wizara yenye dhamana ya Tawala za Mikoa na Serikali za Mitaa', 'Ministry', 'Regional/LGA Governance',
     'Link regional secretariats and LGAs with the disaster-management ministry; ensure DRR, preparedness plans, risk assessments and budgets are integrated into regional and LGA plans.',
     'Kuunganisha Sekretarieti za Mikoa na Mamlaka za Serikali za Mitaa na wizara yenye dhamana ya maafa; kuhakikisha tathmini za hatari, mikakati, mipango ya utayari na bajeti zinajumuishwa kwenye mipango ya mikoa na halmashauri.',
     'POLICY_PORALG_LGA_DRR_INTEGRATION,REG_EOC_OPERATIONAL,LGA_PREPAREDNESS_PLAN',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.2'),
    ('POLICY_FINANCE', 'Ministry responsible for Finance', 'Wizara yenye dhamana ya fedha',
     'Ministry', 'Finance/Risk Financing',
     'Facilitate availability and proper use of financial resources for disaster-management interventions.',
     'Kuwezesha upatikanaji na matumizi sahihi ya rasilimali fedha kwa ajili ya hatua za usimamizi wa maafa.',
     'POLICY_FINANCE_DRR_FUNDS_AVAILABLE,MDA_SECTOR_DRR_BUDGET,PMO_NDMF_DISBURSEMENT',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.3'),
    ('POLICY_PLANNING', 'Ministry responsible for Planning', 'Wizara yenye dhamana ya mipango',
     'Ministry', 'National Planning',
     'Ensure disaster-management issues are integrated into national development plans, programmes and projects.',
     'Kuhakikisha masuala ya usimamizi wa maafa yanajumuishwa katika mipango, programu na miradi ya maendeleo ya Taifa.',
     'POLICY_PLANNING_DRR_INTEGRATED,NAT_FY_TCVMP_CONSIDERED',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.4'),
    ('POLICY_HEALTH', 'Ministry responsible for Health', 'Wizara yenye dhamana ya afya',
     'Ministry', 'Health',
     'Coordinate health and medical services during disasters; control disease outbreaks; conduct health-sector risk assessment, mitigation strategies, preparedness plans and budget allocation.',
     'Kuratibu huduma za afya na tiba wakati wa maafa; kudhibiti milipuko ya magonjwa; kufanya tathmini za hatari za sekta ya afya, mikakati ya kupunguza madhara, mipango ya utayari na mgao wa fedha.',
     'POLICY_HEALTH_MEDICAL_SERVICES,POLICY_HEALTH_OUTBREAK_CONTROL,POLICY_HEALTH_RISK_PLAN_BUDGET',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.5'),
    ('POLICY_LIVESTOCK_FISHERIES', 'Ministry responsible for Livestock and Fisheries',
     'Wizara yenye dhamana ya mifugo na uvuvi', 'Ministry', 'Livestock/Fisheries',
     'Coordinate livestock disease-outbreak control and water/pasture availability before, during and after hazards; prepare sector risk mitigation strategies.',
     'Kuratibu udhibiti wa milipuko ya magonjwa ya mifugo na upatikanaji wa maji na malisho kabla, wakati na baada ya majanga; kuandaa mikakati ya kisekta ya kupunguza hatari.',
     'POLICY_LIVESTOCK_DISEASE_CONTROL,POLICY_LIVESTOCK_RISK_STRATEGY',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.7'),
    ('POLICY_AGRICULTURE', 'Ministry responsible for Agriculture', 'Wizara yenye dhamana ya kilimo',
     'Ministry', 'Agriculture/Food Security',
     'Oversee food security before, during and after disasters; conduct agriculture-sector risk assessment, mitigation strategies, preparedness plans and budget allocation.',
     'Kusimamia usalama wa chakula kabla, wakati na baada ya maafa; kufanya tathmini za hatari za sekta ya kilimo, mikakati ya kupunguza madhara, mipango ya utayari na mgao wa fedha.',
     'POLICY_AGRICULTURE_FOOD_SECURITY,POLICY_AGRICULTURE_RISK_PLAN_BUDGET',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.8'),
    ('POLICY_WORKS_TRANSPORT', 'Ministries responsible for Works and Transport',
     'Wizara zenye dhamana ya ujenzi na uchukuzi', 'Ministry', 'Infrastructure/Transport',
     'Ensure resilient infrastructure design, rehabilitation and reconstruction; strengthen transport safety and sector risk strategies for air, land and maritime hazards.',
     'Kuhakikisha usanifu, ukarabati na ujenzi upya wa miundombinu stahimilivu; kuimarisha usalama wa usafiri na mikakati ya hatari za sekta ya anga, nchi kavu na majini.',
     'POLICY_INFRA_RESILIENT_DESIGN,POLICY_TRANSPORT_SAFETY_RISK_PLAN',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.9-5.1.10'),
    ('POLICY_ENVIRONMENT', 'Ministry responsible for Environment', 'Wizara yenye dhamana ya mazingira',
     'Ministry', 'Environment/Natural Resources',
     'Integrate environmental conservation, climate-change interventions and disaster-risk indicators into environmental impact assessments and sector plans.',
     'Kujumuisha uhifadhi wa mazingira, hatua za mabadiliko ya tabianchi na viashiria vya hatari za maafa kwenye tathmini za athari kwa mazingira na mipango ya kisekta.',
     'POLICY_ENVIRONMENT_DRR_EIA,POLICY_ENVIRONMENT_CLIMATE_INTEGRATION',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.12'),
    ('POLICY_WATER', 'Ministry responsible for Water', 'Wizara yenye dhamana ya maji',
     'Ministry', 'Water/WASH',
     'Ensure resilient water infrastructure, rehabilitate water systems affected by disasters, provide safe water to victims and strengthen flood monitoring and early-warning dissemination.',
     'Kuhakikisha miundombinu ya maji ni stahimilivu, kukarabati mifumo ya maji iliyoathiriwa na maafa, kutoa maji salama kwa waathirika na kuimarisha ufuatiliaji wa mafuriko na usambazaji wa tahadhari.',
     'POLICY_WATER_RESILIENT_INFRA,POLICY_WATER_FLOOD_EARLY_WARNING',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.13'),
    ('POLICY_LANDS', 'Ministry responsible for Lands', 'Wizara yenye dhamana ya ardhi',
     'Ministry', 'Land Use/Urban Planning',
     'Guide land-use planning and settlement in safe areas, integrate disaster-risk assessments into land-use and urban development, and allocate funds for mitigation.',
     'Kutoa miongozo ya matumizi ya ardhi na upangaji wa makazi salama, kujumuisha tathmini za hatari za maafa kwenye matumizi ya ardhi na maendeleo ya miji, na kutenga fedha za kupunguza madhara.',
     'POLICY_LANDS_RISK_IN_LAND_USE,POLICY_LANDS_SAFE_SETTLEMENTS',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.14'),
    ('POLICY_EDUCATION', 'Ministry responsible for Education', 'Wizara yenye dhamana ya elimu',
     'Ministry', 'Education/Research',
     'Ensure disaster-related issues are incorporated at all levels of education and support scientific research on disaster-management interventions.',
     'Kuhakikisha masuala ya maafa yanajumuishwa katika ngazi zote za elimu na kuendeleza tafiti za kisayansi kuhusu hatua za usimamizi wa maafa.',
     'POLICY_EDUCATION_DRR_CURRICULUM,POLICY_EDUCATION_DRR_RESEARCH',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.16'),
    ('POLICY_COMMUNICATIONS', 'Ministry responsible for Communications', 'Wizara yenye dhamana ya mawasiliano',
     'Ministry', 'Communication/Media',
     'Ensure continuity of communication services during disasters and access to early-warning information through communication systems.',
     'Kuhakikisha mwendelezo wa huduma za mawasiliano wakati wa maafa na upatikanaji wa taarifa za tahadhari kupitia mifumo ya mawasiliano.',
     'POLICY_COMMUNICATION_CONTINUITY,POLICY_WARNING_ACCESS',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.25'),
    ('POLICY_SECURITY_RESPONSE', 'Home Affairs, Defence, Fire, Police and response institutions',
     'Mambo ya Ndani, Ulinzi, Zimamoto, Polisi na taasisi za kukabiliana na maafa',
     'Security and Response Institution', 'Security/Response',
     'Protect people and property, participate in rescue and response operations, and provide specialised response capacity when civilian authorities are overwhelmed.',
     'Kulinda watu na mali, kushiriki katika uokoaji na kukabiliana na maafa, na kutoa uwezo maalumu wa kukabiliana na maafa pale mamlaka za kiraia zinapozidiwa.',
     'POLICY_SECURITY_PROTECTION,POLICY_DEFENCE_RESCUE_SUPPORT',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.19, 5.1.24, 5.1.34-5.1.36'),
    ('POLICY_PARTNERS', 'NGOs, FBOs, private sector, UN agencies and development partners',
     'AZAKi, Taasisi za Dini, Sekta Binafsi, Mashirika ya UN na Wadau wa Maendeleo',
     'Stakeholder', 'Humanitarian/DRR',
     'Provide technical, financial, humanitarian and community mobilisation support for disaster prevention, mitigation, preparedness, response and recovery.',
     'Kutoa msaada wa kitaalamu, kifedha, kibinadamu na uhamasishaji jamii katika kuzuia, kupunguza madhara, kujiandaa, kukabili na kurejesha hali baada ya maafa.',
     'PARTNER_RESOURCE_COMMITMENT,PARTNER_GEOGRAPHIC_COVERAGE,PARTNER_TRAINING_SUPPORT,PARTNER_FY_TCVMP_CONSIDERED',
     'National Disaster Management Policy 2004 (2025 Edition), 5.1.33, 5.1.46-5.1.49')
)
insert into public.institution_policy_roles(role_code, actor_label_en, actor_label_sw, institution_class, sector_tags,
                                            responsibility_en, responsibility_sw, default_indicator_codes,
                                            source_reference, active, created_at, updated_at)
select role_code, actor_label_en, actor_label_sw, institution_class, sector_tags, responsibility_en,
       responsibility_sw, default_indicator_codes, source_reference, true, now(), now()
from roles
on conflict (role_code) do update
set actor_label_en = excluded.actor_label_en,
    actor_label_sw = excluded.actor_label_sw,
    institution_class = excluded.institution_class,
    sector_tags = excluded.sector_tags,
    responsibility_en = excluded.responsibility_en,
    responsibility_sw = excluded.responsibility_sw,
    default_indicator_codes = excluded.default_indicator_codes,
    source_reference = excluded.source_reference,
    active = true,
    updated_at = now();

with seed(code, name, description, domain, disaster_cycle, level, value_type, unit, frequency,
          owner_type, sector, source_module, target_value, direction, sort_order,
          applicable_sectors, applicable_classes, policy_role_code, role_summary) as (
  values
    ('POLICY_STAKEHOLDER_PLATFORM_COORDINATED', 'National disaster-management stakeholder platform coordinated',
     'Whether PMO-DMD coordinated the national stakeholder platform and documented deliberations/actions for the reporting period.',
     'Policy Roles - PMO-DMD', 'preparedness', 'agency', 'boolean', null, 'quarterly', 'agency',
     'Disaster Management Coordination', 'National Disaster Management Policy 2004 (2025 Edition)', 1, 'higher', 1010,
     'Disaster Management Coordination', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'Policy 5.1.1 requires the disaster-management ministry to coordinate all stakeholders, including private sector, NGOs, UN agencies and international institutions.'),
    ('POLICY_PORALG_LGA_DRR_INTEGRATION', 'Regional and LGA plans integrate disaster-management interventions',
     'Share of regional secretariats/LGAs supported to integrate DRR, preparedness plans, risk assessments and budgets into plans and guidelines.',
     'Policy Roles - Regional/LGA Governance', 'prevention_mitigation', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Regional/LGA Governance', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1020,
     'Regional/LGA Governance', 'Ministry,Government Institution', 'POLICY_PORALG',
     'Policy 5.1.2 places the regional/LGA planning integration role under the responsible ministry.'),
    ('POLICY_FINANCE_DRR_FUNDS_AVAILABLE', 'Financial resources facilitated for disaster-management interventions',
     'Availability/execution status of disaster-management financing facilitated by the finance sector.',
     'Policy Roles - Finance', null, 'agency', 'percent', '%', 'quarterly', 'agency',
     'Finance/Risk Financing', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1030,
     'Finance/Risk Financing', 'Ministry,Government Institution', 'POLICY_FINANCE',
     'Policy 5.1.3 requires the finance ministry to facilitate financial resources and their intended use.'),
    ('POLICY_PLANNING_DRR_INTEGRATED', 'Disaster-management issues integrated into national development plans',
     'Extent to which national plans, programmes and projects include disaster-management issues.',
     'Policy Roles - Planning', 'prevention_mitigation', 'agency', 'percent', '%', 'annual', 'agency',
     'National Planning', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1040,
     'National Planning', 'Ministry,Government Institution', 'POLICY_PLANNING',
     'Policy 5.1.4 requires planning authorities to integrate disaster-management issues into national plans and projects.'),
    ('POLICY_HEALTH_MEDICAL_SERVICES', 'Health and medical disaster services coordinated',
     'Health-sector coordination of medical services during disasters in collaboration with stakeholders and community-level service providers.',
     'Policy Roles - Health', 'response', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Health', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1050,
     'Health', 'Ministry,Government Institution', 'POLICY_HEALTH',
     'Policy 5.1.5 assigns disaster health and medical-service coordination to the health ministry.'),
    ('POLICY_HEALTH_OUTBREAK_CONTROL', 'Disease outbreak control readiness',
     'Readiness of the health sector to detect, coordinate and control disease outbreaks during disaster and emergency contexts.',
     'Policy Roles - Health', 'preparedness', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Health', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1060,
     'Health', 'Ministry,Government Institution', 'POLICY_HEALTH',
     'Policy 5.1.5 assigns disease-outbreak control to the health ministry.'),
    ('POLICY_HEALTH_RISK_PLAN_BUDGET', 'Health-sector risk assessment, mitigation plan and budget completed',
     'Whether the health sector completed risk assessments, mitigation strategies, preparedness plans and budget allocation for health hazards.',
     'Policy Roles - Health', 'prevention_mitigation', 'agency', 'boolean', null, 'annual', 'agency',
     'Health', 'National Disaster Management Policy 2004 (2025 Edition)', 1, 'higher', 1070,
     'Health', 'Ministry,Government Institution', 'POLICY_HEALTH',
     'Policy 5.1.5 requires health-sector risk assessment, mitigation strategies, preparedness plans and allocation of funds.'),
    ('POLICY_LIVESTOCK_DISEASE_CONTROL', 'Livestock disease outbreak control coordinated',
     'Coordination of livestock disease-outbreak control and essential water/pasture services around hazard periods.',
     'Policy Roles - Livestock/Fisheries', 'preparedness', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Livestock/Fisheries', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1080,
     'Livestock/Fisheries', 'Ministry,Government Institution', 'POLICY_LIVESTOCK_FISHERIES',
     'Policy 5.1.7 assigns livestock disease-outbreak control and water/pasture services to the livestock/fisheries sector.'),
    ('POLICY_LIVESTOCK_RISK_STRATEGY', 'Livestock and fisheries sector risk mitigation strategy prepared',
     'Whether sector hazard risk assessment and mitigation strategies are prepared through sectoral plans.',
     'Policy Roles - Livestock/Fisheries', 'prevention_mitigation', 'agency', 'boolean', null, 'annual', 'agency',
     'Livestock/Fisheries', 'National Disaster Management Policy 2004 (2025 Edition)', 1, 'higher', 1090,
     'Livestock/Fisheries', 'Ministry,Government Institution', 'POLICY_LIVESTOCK_FISHERIES',
     'Policy 5.1.7 requires livestock/fisheries risk assessments and mitigation strategies.'),
    ('POLICY_AGRICULTURE_FOOD_SECURITY', 'Food security oversight before, during and after disasters',
     'Status of agriculture-sector food-security oversight for preparedness, response and recovery periods.',
     'Policy Roles - Agriculture/Food Security', 'preparedness', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Agriculture/Food Security', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1100,
     'Agriculture/Food Security', 'Ministry,Government Institution', 'POLICY_AGRICULTURE',
     'Policy 5.1.8 assigns food-security oversight before, during and after disasters to the agriculture sector.'),
    ('POLICY_AGRICULTURE_RISK_PLAN_BUDGET', 'Agriculture-sector risk assessment, mitigation plan and budget completed',
     'Whether agriculture-sector hazards are assessed and mitigation strategies, preparedness plans and funding allocations are in place.',
     'Policy Roles - Agriculture/Food Security', 'prevention_mitigation', 'agency', 'boolean', null, 'annual', 'agency',
     'Agriculture/Food Security', 'National Disaster Management Policy 2004 (2025 Edition)', 1, 'higher', 1110,
     'Agriculture/Food Security', 'Ministry,Government Institution', 'POLICY_AGRICULTURE',
     'Policy 5.1.8 requires agriculture risk assessment, mitigation strategies, preparedness plans and funds.'),
    ('POLICY_INFRA_RESILIENT_DESIGN', 'Disaster-resilient infrastructure design and reconstruction applied',
     'Use of standards/guidelines that prevent or mitigate disaster impacts in infrastructure design, rehabilitation and reconstruction.',
     'Policy Roles - Infrastructure/Transport', 'prevention_mitigation', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Infrastructure/Transport', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1120,
     'Infrastructure/Transport', 'Ministry,Government Institution', 'POLICY_WORKS_TRANSPORT',
     'Policy 5.1.9 assigns resilient infrastructure design, rehabilitation and reconstruction to the works sector.'),
    ('POLICY_TRANSPORT_SAFETY_RISK_PLAN', 'Transport safety and sector risk plan strengthened',
     'Status of transport-sector weather information, safety strengthening and risk strategies for air, land and maritime transport.',
     'Policy Roles - Infrastructure/Transport', 'preparedness', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Infrastructure/Transport', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1130,
     'Infrastructure/Transport', 'Ministry,Government Institution', 'POLICY_WORKS_TRANSPORT',
     'Policy 5.1.10 assigns weather information and transport safety strengthening to the transport sector.'),
    ('POLICY_ENVIRONMENT_DRR_EIA', 'Disaster-risk indicators integrated in environmental impact assessments',
     'Whether environmental impact assessments include disaster-risk indicators relevant to the area and sector.',
     'Policy Roles - Environment', 'prevention_mitigation', 'agency', 'boolean', null, 'quarterly', 'agency',
     'Environment/Natural Resources', 'National Disaster Management Policy 2004 (2025 Edition)', 1, 'higher', 1140,
     'Environment/Natural Resources', 'Ministry,Government Institution', 'POLICY_ENVIRONMENT',
     'Policy 5.1.12 and 5.1.45 require disaster-risk indicators in environmental assessments.'),
    ('POLICY_ENVIRONMENT_CLIMATE_INTEGRATION', 'Climate and environmental conservation integrated into disaster management',
     'Extent of integration of environmental conservation and climate-change interventions into disaster-management plans and projects.',
     'Policy Roles - Environment', 'prevention_mitigation', 'agency', 'percent', '%', 'annual', 'agency',
     'Environment/Natural Resources', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1150,
     'Environment/Natural Resources', 'Ministry,Government Institution', 'POLICY_ENVIRONMENT',
     'Policy 5.1.12 assigns climate/environment integration to the environment sector.'),
    ('POLICY_WATER_RESILIENT_INFRA', 'Water infrastructure resilience and safe water response maintained',
     'Status of resilient water infrastructure, post-disaster rehabilitation and safe-water access for disaster victims.',
     'Policy Roles - Water/WASH', 'preparedness', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Water/WASH', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1160,
     'Water/WASH', 'Ministry,Government Institution', 'POLICY_WATER',
     'Policy 5.1.13 assigns resilient water infrastructure, rehabilitation and safe water to the water sector.'),
    ('POLICY_WATER_FLOOD_EARLY_WARNING', 'Flood monitoring and early-warning dissemination strengthened',
     'Functionality of flood monitoring and early-warning dissemination under the water sector mandate.',
     'Policy Roles - Water/WASH', 'preparedness', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Water/WASH', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1170,
     'Water/WASH', 'Ministry,Government Institution', 'POLICY_WATER',
     'Policy 5.1.13 assigns flood monitoring and early-warning dissemination to the water sector.'),
    ('POLICY_LANDS_RISK_IN_LAND_USE', 'Disaster-risk assessment integrated in land-use planning',
     'Whether land-use planning, surveying and urban development processes include disaster-risk assessment.',
     'Policy Roles - Land Use/Urban Planning', 'prevention_mitigation', 'agency', 'boolean', null, 'annual', 'agency',
     'Land Use/Urban Planning', 'National Disaster Management Policy 2004 (2025 Edition)', 1, 'higher', 1180,
     'Land Use/Urban Planning', 'Ministry,Government Institution', 'POLICY_LANDS',
     'Policy 5.1.14 assigns disaster-risk integration in land-use planning and urban development to the lands sector.'),
    ('POLICY_LANDS_SAFE_SETTLEMENTS', 'Safe settlement and village/town planning guidance applied',
     'Extent to which towns and villages are planned in areas protected from disaster impacts.',
     'Policy Roles - Land Use/Urban Planning', 'prevention_mitigation', 'agency', 'percent', '%', 'annual', 'agency',
     'Land Use/Urban Planning', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1190,
     'Land Use/Urban Planning', 'Ministry,Government Institution', 'POLICY_LANDS',
     'Policy 5.1.14 requires safe-area planning for towns and villages.'),
    ('POLICY_EDUCATION_DRR_CURRICULUM', 'Disaster-management issues incorporated at all education levels',
     'Status of disaster-management content integration across education levels.',
     'Policy Roles - Education/Research', 'preparedness', 'agency', 'percent', '%', 'annual', 'agency',
     'Education/Research', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1200,
     'Education/Research', 'Ministry,Government Institution,Academic and Research Institution', 'POLICY_EDUCATION',
     'Policy 5.1.16 assigns disaster-management education integration to the education sector.'),
    ('POLICY_EDUCATION_DRR_RESEARCH', 'Scientific research on disaster-management interventions conducted',
     'Number of research outputs, studies or knowledge products supporting disaster-management interventions.',
     'Policy Roles - Education/Research', 'prevention_mitigation', 'agency', 'count', 'studies', 'annual', 'agency',
     'Education/Research', 'National Disaster Management Policy 2004 (2025 Edition)', null, 'higher', 1210,
     'Education/Research', 'Ministry,Government Institution,Academic and Research Institution', 'POLICY_EDUCATION',
     'Policy 5.1.16 assigns scientific research on disaster-management interventions to education/research actors.'),
    ('POLICY_COMMUNICATION_CONTINUITY', 'Communication service continuity maintained during disasters',
     'Continuity/readiness level of communication services during disaster events.',
     'Policy Roles - Communication/Media', 'response', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Communication/Media', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1220,
     'Communication/Media', 'Ministry,Government Institution,Media', 'POLICY_COMMUNICATIONS',
     'Policy 5.1.25 requires continuity of communication services during disasters.'),
    ('POLICY_WARNING_ACCESS', 'Public access to early-warning information supported',
     'Status of communication systems enabling access to early-warning information.',
     'Policy Roles - Communication/Media', 'preparedness', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Communication/Media', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1230,
     'Communication/Media', 'Ministry,Government Institution,Media', 'POLICY_COMMUNICATIONS',
     'Policy 5.1.25 requires access to early-warning information through communication systems.'),
    ('POLICY_SECURITY_PROTECTION', 'Protection of people and property during disasters strengthened',
     'Readiness/performance of security institutions in protecting people and property during disasters.',
     'Policy Roles - Security/Response', 'response', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Security/Response', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1240,
     'Security/Response', 'Ministry,Government Institution,Security and Response Institution', 'POLICY_SECURITY_RESPONSE',
     'Policy 5.1.19 and 5.1.35 assign protection and security during disasters to home affairs and police institutions.'),
    ('POLICY_DEFENCE_RESCUE_SUPPORT', 'Specialised rescue/response support available',
     'Availability of specialised response support for rescue operations when civilian authorities are overwhelmed.',
     'Policy Roles - Security/Response', 'response', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Security/Response', 'National Disaster Management Policy 2004 (2025 Edition)', 100, 'higher', 1250,
     'Security/Response', 'Ministry,Government Institution,Security and Response Institution', 'POLICY_SECURITY_RESPONSE',
     'Policy 5.1.24 and 5.1.36 assign disaster response/rescue support to defence and specialised response institutions.')
)
insert into public.me_indicator_catalog(code, name, description, domain, disaster_cycle, level, value_type, unit,
                                        frequency, owner_type, sector, source_module, target_value, direction,
                                        sort_order, applicable_sectors, applicable_institution_classes,
                                        policy_role_code, policy_role_source, role_summary, active, created_at, updated_at)
select code, name, description, domain, disaster_cycle, level, value_type, unit, frequency, owner_type, sector,
       source_module, target_value, direction, sort_order, applicable_sectors, applicable_classes,
       policy_role_code, 'National Disaster Management Policy 2004 (2025 Edition)', role_summary,
       true, now(), now()
from seed
on conflict (code) do update
set name = excluded.name,
    description = excluded.description,
    domain = excluded.domain,
    disaster_cycle = excluded.disaster_cycle,
    level = excluded.level,
    value_type = excluded.value_type,
    unit = excluded.unit,
    frequency = excluded.frequency,
    owner_type = excluded.owner_type,
    sector = excluded.sector,
    source_module = excluded.source_module,
    target_value = excluded.target_value,
    direction = excluded.direction,
    sort_order = excluded.sort_order,
    applicable_sectors = excluded.applicable_sectors,
    applicable_institution_classes = excluded.applicable_institution_classes,
    policy_role_code = excluded.policy_role_code,
    policy_role_source = excluded.policy_role_source,
    role_summary = excluded.role_summary,
    active = true,
    updated_at = now();

update public.agencies
   set institution_class = coalesce(institution_class, 'Government Institution'),
       institution_subclass = coalesce(institution_subclass, 'Early-warning sector agency'),
       source_register = coalesce(source_register, 'System baseline'),
       me_required = true,
       sector_tags = case
           when acronym = 'MoH' then coalesce(sector_tags, 'Health')
           when acronym = 'MoW' then coalesce(sector_tags, 'Water/WASH')
           when acronym = 'MoA' then coalesce(sector_tags, 'Agriculture/Food Security')
           when acronym = 'TMA' then coalesce(sector_tags, 'Weather/Climate')
           when acronym = 'GST' then coalesce(sector_tags, 'Geology/Minerals')
           when acronym = 'NEMC' then coalesce(sector_tags, 'Environment/Natural Resources')
           else sector_tags
       end,
       policy_role_code = case
           when acronym = 'MoH' then coalesce(policy_role_code, 'POLICY_HEALTH')
           when acronym = 'MoW' then coalesce(policy_role_code, 'POLICY_WATER')
           when acronym = 'MoA' then coalesce(policy_role_code, 'POLICY_AGRICULTURE')
           when acronym = 'GST' then coalesce(policy_role_code, 'POLICY_SECURITY_RESPONSE')
           when acronym = 'NEMC' then coalesce(policy_role_code, 'POLICY_ENVIRONMENT')
           else policy_role_code
       end,
       role_summary = coalesce(role_summary, mandate_description),
       updated_at = now()
 where acronym in ('MoH','MoW','MoA','TMA','GST','NEMC');

with terms(term_en, term_sw, definition_en, definition_sw, source_reference) as (
  values
    ('One Health', 'Afya Moja', 'A collaborative approach linking human, animal and environmental health sectors.', null, 'Policy/strategy glossary'),
    ('Emergency Services', 'Huduma za Dharura', 'Immediate life-saving assistance provided to disaster-affected persons.', null, 'Policy/strategy glossary'),
    ('Humanitarian Services', 'Huduma za kibinadamu', 'Services provided to save lives and reduce suffering among disaster-affected people.', null, 'Policy/strategy glossary'),
    ('Hazard', 'Janga', 'A dangerous phenomenon or human activity that may cause disaster impacts.', null, 'Policy/strategy glossary'),
    ('Reconstruction', 'Kujenga upya', 'Medium and long-term rebuilding and strengthening of affected systems and infrastructure.', null, 'Policy/strategy glossary'),
    ('Preparedness', 'Kujiandaa na Maafa', 'Actions taken in advance to protect lives, property and systems from disaster impacts.', null, 'Policy/strategy glossary'),
    ('Response', 'Kukabiliana na maafa', 'Actions taken immediately after a disaster to save lives, property and the environment.', null, 'Policy/strategy glossary'),
    ('Rehabilitation', 'Kukarabati', 'Restoration of basic services and needs for disaster-affected communities.', null, 'Policy/strategy glossary'),
    ('Mitigation', 'Kupunguza madhara', 'Measures directed at reducing potential disaster impacts.', null, 'Policy/strategy glossary'),
    ('Recovery', 'Kurejesha hali baada ya maafa', 'Restoring or improving affected livelihoods and systems after disasters.', null, 'Policy/strategy glossary'),
    ('Prevention', 'Kuzuia maafa', 'Actions taken to prevent new risk or reduce existing risk.', null, 'Policy/strategy glossary'),
    ('Disaster', 'Maafa', 'Serious disruption causing deaths, injuries, psychosocial harm, loss or damage.', null, 'Policy/strategy glossary'),
    ('Early Warning System', 'Mfumo wa tahadhari ya mapema ya majanga', 'An integrated system for monitoring, forecasting, risk assessment, communication and preparedness action.', null, 'Policy/strategy glossary'),
    ('Disaster Management Framework', 'Mfumo wa Usimamizi wa Maafa', 'Institutional, policy and legal arrangements for coordinating disaster-risk reduction and humanitarian services.', null, 'Policy/strategy glossary'),
    ('Disaster Management Cycle', 'Mzingo wa Usimamizi wa Maafa', 'The phases of prevention/mitigation, preparedness, response and recovery.', null, 'Policy/strategy glossary'),
    ('Critical Infrastructure', 'Miundombinu Muhimu', 'Infrastructure providing essential social and economic services.', null, 'Policy/strategy glossary'),
    ('Standard Operating Procedures', 'Taratibu za utendaji', 'Guidelines defining activities institutions must perform before, during and after disasters.', null, 'Policy/strategy glossary'),
    ('Disaster Risk Assessment', 'Tathmini ya Hatari ya Maafa', 'Qualitative or quantitative assessment of hazards, exposure, vulnerability and capacity.', null, 'Policy/strategy glossary'),
    ('Technology', 'Teknolojia', 'Modern scientific tools, methods and systems for disaster management.', null, 'Policy/strategy glossary'),
    ('Disaster Risk Reduction', 'Upunguzaji wa Vihatarishi vya maafa', 'Policies and strategies to prevent new risk, reduce existing risk and manage residual risk.', null, 'Policy/strategy glossary'),
    ('Disaster Risk Management', 'Usimamizi wa Hatari ya Maafa', 'Management of resources and responsibilities for preparedness, response and early recovery.', null, 'Policy/strategy glossary'),
    ('Resilience', 'Ustahimilivu dhidi ya majanga', 'The ability of a system or community to withstand, adapt and recover from disaster impacts.', null, 'Policy/strategy glossary'),
    ('Community Participation', 'Ushiriki wa Jamii', 'Community participation in assessment, planning, implementation and monitoring across the disaster cycle.', null, 'Policy/strategy glossary'),
    ('Vulnerability', 'Uwezekano wa kuathirika', 'Conditions that make people, infrastructure or assets susceptible to hazard impacts.', null, 'Policy/strategy glossary'),
    ('Capacity', 'Uwezo', 'The ability of communities, government, private sector and partners to prepare, prevent, mitigate and recover.', null, 'Policy/strategy glossary'),
    ('Stakeholders', 'Wadau', 'Government, private sector, civil society, international, regional, UN and development partner actors involved in policy implementation.', null, 'Policy/strategy glossary')
)
insert into public.disaster_glossary_terms(term_en, term_sw, definition_en, definition_sw, source_reference,
                                           active, created_at, updated_at)
select term_en, term_sw, definition_en, definition_sw, source_reference, true, now(), now()
from terms
on conflict (term_en, term_sw) do update
set definition_en = excluded.definition_en,
    definition_sw = excluded.definition_sw,
    source_reference = excluded.source_reference,
    active = true,
    updated_at = now();

with labels(label_key, group_name, en, sw) as (
  values
    ('glossary_one_health', 'Disaster Glossary', 'One Health', 'Afya Moja'),
    ('glossary_emergency_services', 'Disaster Glossary', 'Emergency Services', 'Huduma za Dharura'),
    ('glossary_humanitarian_services', 'Disaster Glossary', 'Humanitarian Services', 'Huduma za kibinadamu'),
    ('glossary_hazard', 'Disaster Glossary', 'Hazard', 'Janga'),
    ('glossary_preparedness', 'Disaster Glossary', 'Preparedness', 'Kujiandaa na Maafa'),
    ('glossary_response', 'Disaster Glossary', 'Response', 'Kukabiliana na maafa'),
    ('glossary_mitigation', 'Disaster Glossary', 'Mitigation', 'Kupunguza madhara'),
    ('glossary_recovery', 'Disaster Glossary', 'Recovery', 'Kurejesha hali baada ya maafa'),
    ('glossary_prevention', 'Disaster Glossary', 'Prevention', 'Kuzuia maafa'),
    ('glossary_disaster', 'Disaster Glossary', 'Disaster', 'Maafa'),
    ('glossary_early_warning_system', 'Disaster Glossary', 'Early Warning System', 'Mfumo wa tahadhari ya mapema ya majanga'),
    ('glossary_disaster_management_cycle', 'Disaster Glossary', 'Disaster Management Cycle', 'Mzingo wa Usimamizi wa Maafa'),
    ('glossary_critical_infrastructure', 'Disaster Glossary', 'Critical Infrastructure', 'Miundombinu Muhimu'),
    ('glossary_disaster_risk_assessment', 'Disaster Glossary', 'Disaster Risk Assessment', 'Tathmini ya Hatari ya Maafa'),
    ('glossary_disaster_risk_reduction', 'Disaster Glossary', 'Disaster Risk Reduction', 'Upunguzaji wa Vihatarishi vya maafa'),
    ('glossary_disaster_risk_management', 'Disaster Glossary', 'Disaster Risk Management', 'Usimamizi wa Hatari ya Maafa'),
    ('glossary_resilience', 'Disaster Glossary', 'Resilience', 'Ustahimilivu dhidi ya majanga'),
    ('glossary_community_participation', 'Disaster Glossary', 'Community Participation', 'Ushiriki wa Jamii'),
    ('glossary_vulnerability', 'Disaster Glossary', 'Vulnerability', 'Uwezekano wa kuathirika'),
    ('glossary_capacity', 'Disaster Glossary', 'Capacity', 'Uwezo'),
    ('glossary_stakeholders', 'Disaster Glossary', 'Stakeholders', 'Wadau')
)
insert into public.translations(label_key, group_name, en, sw)
select label_key, group_name, en, sw
from labels
on conflict (label_key) do update
set group_name = excluded.group_name,
    en = excluded.en,
    sw = excluded.sw,
    updated_at = now();
