-- V174: Full institutional M&E model (beyond Region / District / LGA)
-- Sources (authoritative, taken as-is then de-duplicated):
--   * ORODHA YA WASHIRIKI.xlsx — WIZARA, TAASISI, NGOS, UN, VYUO, SEKTA BINAFSI, BALOZI, DINI, HABARI, TAWALA
--   * FINAL_DRR_Stakeholders_DATABASE — Departments, Ministries, Training & Research, UN, Media
--   * MKAKATI UTEKELEZAJI SERA 2025–2035 — Sura 6 majukumu + Jedwali Na. 2 viashiria (Mhusika)
--   * DMD indicators.docx — PMO-DMD strategic KPIs (coordination, awareness, capacity, EWS, research, NDMF)
--   * Global DM practice (Sendai Framework, UNDRR multi-stakeholder M&E): resource distribution,
--     country readiness, multi-hazard early warning, partner contribution tracking
--
-- Does NOT re-import entire invitation lists (already in agencies/stakeholders via seeder).
-- Normalises taxonomy, maps policy roles, seeds role-exact indicators + EN/SW glossary.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Taxonomy normalisation (no duplication of institution_class labels)
-- ─────────────────────────────────────────────────────────────────────────────
update public.stakeholders
   set institution_class = case
           when institution_class in ('NGO / Development Partner', 'Development Partner') then 'NGO'
           when institution_class = 'Community Support' then 'Community / Civic Group'
           when institution_class is null or btrim(institution_class) = '' then
               case
                   when type = 'International' and (
                        name ilike '%united nations%' or name ilike 'un %' or name ilike 'un-%'
                        or name ilike '% undp%' or name ilike 'undp%' or name ilike '%unicef%'
                        or name ilike '%wfp%' or name ilike '%who %' or name ilike 'who %'
                        or name ilike '%unhcr%' or name ilike '%unfpa%' or name ilike '%fao%'
                        or name ilike '%iom%' or name ilike '%unesco%' or name ilike '%ilo%'
                        or organization ilike '%united nations%' or organization ilike 'undp%'
                   ) then 'UN Agency'
                   when type = 'International' then 'NGO'
                   when type = 'NGO' then 'NGO'
                   when type = 'Private' then 'Private Sector'
                   when type = 'Community' then 'Community / Civic Group'
                   when type = 'Government' then 'Government Institution'
                   else 'NGO'
               end
           else institution_class
       end,
       me_required = true,
       updated_at = now()
 where coalesce(is_active, true);

update public.agencies
   set institution_class = case
           when institution_class is null or btrim(institution_class) = '' then
               case
                   when agency_type ilike '%lga%' or name ilike 'halmashauri%' or name ilike '%municipal%'
                        or name ilike '%city council%' or name ilike '%town council%'
                        or name ilike '%district council%' then 'Local Government Authority'
                   when name ilike '%mkoa%' or name ilike 'regional%' or name ilike '%ras %'
                        or name ilike 'ofisi ya mkuu wa mkoa%' then 'Regional Administration'
                   when name ilike 'wizara%' or name ilike 'ministry%' or name ilike 'ofisi ya%'
                        or name ilike 'prime minister%' or name ilike 'president%' then 'Ministry'
                   when name ilike '%chuo%' or name ilike '%university%' or name ilike '%institute%'
                        or name ilike '%research%' then 'Academic and Research Institution'
                   when name ilike '%police%' or name ilike '%jwtz%' or name ilike '%zimamoto%'
                        or name ilike '%defence%' or name ilike '%ulinzi%' then 'Security and Response Institution'
                   else 'Government Institution'
               end
           else institution_class
       end,
       me_required = coalesce(me_required, true),
       updated_at = now()
 where coalesce(is_active, true);

-- Canonical technical agencies: policy role + class (MKAKATI 6.2.37–6.2.48)
update public.agencies a
   set policy_role_code = v.role_code,
       institution_class = coalesce(nullif(a.institution_class, ''), v.inst_class),
       sector_tags = coalesce(nullif(a.sector_tags, ''), v.sectors),
       role_summary = coalesce(a.role_summary, v.summary),
       me_required = true,
       updated_at = now()
  from (values
    ('POLICY_PMO_DMD', 'Ministry', 'Disaster Management Coordination',
     'National coordination of disaster management policy, EOCC, NDMF and multi-stakeholder M&E (OWM-SBU / PMO-DMD).',
     array['pmo','dmd','ofisi ya waziri mkuu - sera','prime minister%disaster','owm-sbu','sbu']),
    ('POLICY_PORALG', 'Ministry', 'Regional/LGA Governance',
     'Link regional secretariats and LGAs; integrate DRR into regional and LGA plans (OWM-TAMISEMI / PO-RALG).',
     array['tamisemi','poralg','tawala za mikoa','regional administration and local']),
    ('POLICY_FINANCE', 'Ministry', 'Finance/Risk Financing',
     'Facilitate disaster-management financing and sector DRR budget integration.',
     array['fedha','ministry of finance','mofp','ministry of finance and planning']),
    ('POLICY_PLANNING', 'Ministry', 'National Planning',
     'Integrate disaster management into national development plans and investment.',
     array['mipango','planning and investment','ofisi ya rais - mipango']),
    ('POLICY_HEALTH', 'Ministry', 'Health',
     'Coordinate health/medical services, outbreak control and health-sector risk plans.',
     array['wizara ya afya','ministry of health','moh']),
    ('POLICY_AGRICULTURE', 'Ministry', 'Agriculture/Food Security',
     'Food security oversight and agriculture-sector risk plans before/during/after disasters.',
     array['kilimo','ministry of agriculture']),
    ('POLICY_LIVESTOCK_FISHERIES', 'Ministry', 'Livestock/Fisheries',
     'Livestock disease outbreak control and sector risk strategies.',
     array['mifugo','livestock and fisheries']),
    ('POLICY_WATER', 'Ministry', 'Water/WASH',
     'Resilient water infrastructure, safe water response, flood monitoring.',
     array['wizara ya maji','ministry of water']),
    ('POLICY_ENVIRONMENT', 'Ministry', 'Environment/Natural Resources',
     'Environment conservation and climate integration in disaster management.',
     array['mazingira','environment','omr-muungano','makamu wa rais - muungano']),
    ('POLICY_LANDS', 'Ministry', 'Land Use/Urban Planning',
     'Safe settlements and disaster-risk integration in land-use planning.',
     array['ardhi','ministry of lands','lands, housing']),
    ('POLICY_EDUCATION', 'Ministry', 'Education/Research',
     'DRR in education curricula and scientific research support.',
     array['elimu','ministry of education','education, science']),
    ('POLICY_COMMUNICATIONS', 'Ministry', 'Communication/Media',
     'Communication continuity and early-warning access during disasters.',
     array['mawasiliano','information, culture','habari, mawasiliano','ministry of information']),
    ('POLICY_WORKS_TRANSPORT', 'Ministry', 'Infrastructure/Transport',
     'Resilient infrastructure design and transport safety risk plans.',
     array['ujenzi','uchukuzi','works','transport','ministry of works']),
    ('POLICY_SECURITY_RESPONSE', 'Security and Response Institution', 'Security/Response',
     'Protection, rescue and specialised response support during disasters.',
     array['polisi','police','jwtz','defence','ulinzi','zimamoto','fire and rescue','jeshi la']),
    ('POLICY_TMA', 'Government Institution', 'Weather/Climate',
     'Multi-hazard meteorological monitoring, forecasting and early-warning products (TMA).',
     array['tanzania meteorological','hali ya hewa','tma']),
    ('POLICY_TIRA', 'Government Institution', 'Finance/Risk Financing',
     'Disaster risk insurance market development and community insurance education (TIRA).',
     array['tira','insurance regulatory','mamlaka ya udhibiti wa bima']),
    ('POLICY_EGA', 'Government Institution', 'Digital Government / ICT',
     'Digital early-warning systems, cybersecurity of DM systems, data platforms (eGA).',
     array['e-government','ega','serikali pepe']),
    ('POLICY_NEMC', 'Government Institution', 'Environment/Natural Resources',
     'Environmental impact assessment with disaster-risk indicators (NEMC).',
     array['nemc','hifadhi na usimamizi wa mazingira']),
    ('POLICY_TCRA', 'Government Institution', 'Communication/Media',
     'Telecommunications continuity and public-warning channel readiness (TCRA).',
     array['tcra','communications regulatory','mawasiliano tanzania']),
    ('POLICY_ACADEMIC', 'Academic and Research Institution', 'Education/Research',
     'Disaster-related research, training and knowledge products for national readiness.',
     array['chuo kikuu','university','ardhi university','disaster management training','udom','udsm','muhas','sua','ifakara','nimr','nactvet','veta'])
  ) as v(role_code, inst_class, sectors, summary, patterns)
 where a.policy_role_code is null
   and exists (
        select 1 from unnest(v.patterns) p
         where lower(coalesce(a.name,'')) like '%' || p || '%'
            or lower(coalesce(a.acronym,'')) = replace(p, '%', '')
   );

update public.stakeholders s
   set policy_role_code = case
           when s.institution_class = 'UN Agency' then 'POLICY_UN_AGENCY'
           when s.institution_class = 'NGO' then 'POLICY_NGO'
           when s.institution_class = 'Private Sector' then 'POLICY_PRIVATE'
           when s.institution_class = 'Faith-Based Organization' then 'POLICY_FBO'
           when s.institution_class = 'Media' then 'POLICY_MEDIA'
           when s.institution_class = 'Diplomatic Mission' then 'POLICY_DIPLOMATIC'
           when s.institution_class = 'Community / Civic Group' then 'POLICY_COMMUNITY'
           when s.institution_class = 'Academic and Research Institution' then 'POLICY_ACADEMIC'
           else coalesce(s.policy_role_code, 'POLICY_PARTNERS')
       end,
       me_required = true,
       updated_at = now()
 where coalesce(s.is_active, true)
   and (s.policy_role_code is null or s.policy_role_code = 'POLICY_PARTNERS');

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Expanded policy roles (MKAKATI Sura 6 + partner classes)
-- ─────────────────────────────────────────────────────────────────────────────
with roles(role_code, actor_label_en, actor_label_sw, institution_class, sector_tags,
           responsibility_en, responsibility_sw, default_indicator_codes, source_reference) as (
  values
    ('POLICY_TMA', 'Tanzania Meteorological Authority', 'Mamlaka ya Hali ya Hewa Tanzania (TMA)',
     'Government Institution', 'Weather/Climate',
     'Provide multi-hazard weather/climate monitoring, forecasts and early-warning products that feed national and local anticipatory action.',
     'Kutoa ufuatiliaji, utabiri na bidhaa za tahadhari ya mapema za hali ya hewa/tabianchi zinazosaidia hatua za kitaifa na za mitaa.',
     'TMA_MULTIHAZARD_EWS_FUNCTIONAL,TMA_WARNING_PRODUCTS_ISSUED,TMA_SECTOR_WARNING_REACH',
     'MKAKATI 6.2.37; Jedwali Na. 2 Lengo 5'),
    ('POLICY_TIRA', 'Tanzania Insurance Regulatory Authority', 'Mamlaka ya Udhibiti wa Bima Tanzania (TIRA)',
     'Government Institution', 'Finance/Risk Financing',
     'Strengthen disaster risk insurance uptake and public education on insurance for households and productive sectors.',
     'Kuimarisha matumizi ya bima ya hatari za maafa na elimu ya umma juu ya bima kwa jamii na sekta za uzalishaji.',
     'TIRA_INSURANCE_UPTAKE,TIRA_INSURANCE_EDUCATION_PROGRAMMES',
     'MKAKATI Jedwali Na. 2 Lengo 4 (bima)'),
    ('POLICY_EGA', 'e-Government Authority', 'Mamlaka ya Serikali Pepe (eGA)',
     'Government Institution', 'Digital Government / ICT',
     'Operate and secure digital systems for early warning, disaster data exchange and emergency ICT continuity.',
     'Kuendesha na kulinda mifumo ya kidijitali ya tahadhari, kubadilishana data za maafa na mwendelezo wa TEHAMA wakati wa dharura.',
     'EGA_DIGITAL_EWS_UPTIME,EGA_DM_SYSTEM_SECURITY,EGA_INTEROPERABLE_DATA_SYSTEMS',
     'MKAKATI Jedwali Na. 2 Lengo 1 (mfumo wa kidigitali, eGA)'),
    ('POLICY_NEMC', 'National Environment Management Council', 'Baraza la Taifa la Hifadhi na Usimamizi wa Mazingira (NEMC)',
     'Government Institution', 'Environment/Natural Resources',
     'Integrate disaster-risk indicators into environmental impact assessments and climate/environment programmes.',
     'Kujumuisha viashiria vya hatari za maafa katika tathmini za athari kwa mazingira na programu za mazingira/tabianchi.',
     'POLICY_ENVIRONMENT_DRR_EIA,NEMC_CLIMATE_DM_INTEGRATION',
     'MKAKATI 6.2.49; Jedwali Na. 2 Lengo 10'),
    ('POLICY_TCRA', 'Tanzania Communications Regulatory Authority', 'Mamlaka ya Mawasiliano Tanzania (TCRA)',
     'Government Institution', 'Communication/Media',
     'Ensure telecommunications continuity and regulatory support for public-warning dissemination channels.',
     'Kuhakikisha mwendelezo wa mawasiliano na udhibiti wa njia za usambazaji wa tahadhari kwa umma.',
     'POLICY_COMMUNICATION_CONTINUITY,TCRA_PUBLIC_WARNING_CHANNELS',
     'MKAKATI 6.2.47'),
    ('POLICY_ACADEMIC', 'Education and Research Institutions', 'Taasisi za Elimu na Utafiti',
     'Academic and Research Institution', 'Education/Research',
     'Conduct disaster-related research, deliver specialised training and produce knowledge products that improve national readiness.',
     'Kufanya tafiti za maafa, kutoa mafunzo maalum na kuzalisha maarifa yanayoboresha utayari wa taifa.',
     'ACADEMIC_DRR_RESEARCH_STUDIES,ACADEMIC_DRR_TRAINING_DELIVERED,ACADEMIC_KNOWLEDGE_PRODUCTS',
     'MKAKATI 6.2.48; DMD KPI research studies; FINAL_DRR Training & Research'),
    ('POLICY_UN_AGENCY', 'United Nations agencies', 'Mashirika ya Umoja wa Mataifa',
     'UN Agency', 'Humanitarian/DRR',
     'Provide technical assistance, humanitarian coordination support, risk-informed development finance and multi-hazard early-warning partnership under national leadership.',
     'Kutoa msaada wa kitaalamu, uratibu wa kibinadamu, fedha za maendeleo zinazozingatia hatari na ushirikiano wa tahadhari chini ya uongozi wa taifa.',
     'UN_TECHNICAL_ASSISTANCE,UN_HUMANITARIAN_SUPPORT,UN_CAPACITY_BUILDING,PARTNER_RESOURCE_COMMITMENT',
     'MKAKATI 6.2.51; ORODHA UN AGENCIES; Sendai multi-stakeholder engagement'),
    ('POLICY_NGO', 'Non-Governmental Organisations', 'Asasi zisizo za kiserikali (NGOs)',
     'NGO', 'Humanitarian/DRR',
     'Deliver community preparedness, humanitarian response, recovery support and complementary capacity building aligned to national priorities.',
     'Kutoa utayari wa jamii, msaada wa kibinadamu, urejeshaji na ujenzi wa uwezo sambamba na vipaumbele vya taifa.',
     'NGO_COMMUNITY_PREPAREDNESS,NGO_HUMANITARIAN_ASSISTANCE,NGO_GEOGRAPHIC_COVERAGE,PARTNER_TRAINING_SUPPORT',
     'MKAKATI 6.2.50; ORODHA NGOS'),
    ('POLICY_PRIVATE', 'Private sector', 'Sekta Binafsi',
     'Private Sector', 'Private Sector / Continuity',
     'Protect critical private infrastructure and services, support business continuity, logistics, telecoms and risk-transfer products during disasters.',
     'Kulinda miundombinu na huduma muhimu za kibinafsi, kuendeleza mwendelezo wa biashara, logistiki, mawasiliano na bidhaa za kuhamisha hatari wakati wa maafa.',
     'PRIVATE_BCP_IN_PLACE,PRIVATE_CRITICAL_SERVICE_CONTINUITY,PRIVATE_LOGISTICS_SUPPORT,PRIVATE_RISK_TRANSFER',
     'MKAKATI 6.2.33; ORODHA SEKTA BINAFSI'),
    ('POLICY_FBO', 'Faith-based organisations', 'Taasisi za Dini',
     'Faith-Based Organization', 'Humanitarian/Community',
     'Mobilise communities for preparedness, psychosocial support, shelter and humanitarian assistance in partnership with government.',
     'Kuhamasisha jamii kwa utayari, msaada wa kisaikolojia, makazi na misaada ya kibinadamu kwa ushirikiano na serikali.',
     'FBO_COMMUNITY_MOBILISATION,FBO_HUMANITARIAN_ASSISTANCE,PARTNER_RESOURCE_COMMITMENT',
     'MKAKATI 6.2.50; ORODHA TAASISI ZA DINI'),
    ('POLICY_MEDIA', 'Media institutions', 'Vyombo vya Habari',
     'Media', 'Communication/Media',
     'Disseminate accurate early-warning and public-awareness messages; counter misinformation during emergencies.',
     'Kusambaza tahadhari na ujumbe wa uelewa wa umma kwa usahihi; kupambana na taarifa potofu wakati wa dharura.',
     'MEDIA_WARNING_DISSEMINATION,MEDIA_PUBLIC_AWARENESS_CAMPAIGNS,MEDIA_ACCURACY_PROTOCOLS',
     'MKAKATI 6.2.52; ORODHA VYOMBO VYA HABARI'),
    ('POLICY_DIPLOMATIC', 'Diplomatic missions and bilateral partners', 'Balozi na Washirika wa Nchi Mbili',
     'Diplomatic Mission', 'Development Cooperation',
     'Channel bilateral technical and financial cooperation for disaster risk reduction, preparedness and recovery under national priorities.',
     'Kuwezesha ushirikiano wa nchi mbili wa kitaalamu na kifedha kwa DRR, utayari na urejeshaji chini ya vipaumbele vya taifa.',
     'DIPLOMATIC_COOPERATION_SUPPORT,PARTNER_RESOURCE_COMMITMENT',
     'ORODHA BALOZI; MKAKATI 6.2.51'),
    ('POLICY_COMMUNITY', 'Community and civic groups', 'Jumuiya na Vikundi vya Kiraia',
     'Community / Civic Group', 'Community Participation',
     'Participate in local preparedness, volunteer response and community-based early warning.',
     'Kushiriki katika utayari wa mitaa, uokoaji wa kujitolea na tahadhari ya jamii.',
     'COMMUNITY_PREPAREDNESS_ACTIONS,COMMUNITY_VOLUNTEER_DEPLOYMENT',
     'MKAKATI 6.2.53'),
    ('POLICY_GENDER_SPECIAL', 'Ministry responsible for Community Development, Gender and Special Groups',
     'Wizara yenye dhamana ya Maendeleo ya Jamii, Jinsia na Makundi Maalum',
     'Ministry', 'Gender/Social Protection',
     'Ensure gender and special-groups inclusion in disaster-management guidelines, programmes and participation metrics.',
     'Kuhakikisha ujumuishaji wa jinsia na makundi maalum katika miongozo, programu na viashiria vya ushiriki katika usimamizi wa maafa.',
     'GENDER_INCLUSION_GUIDELINES,SPECIAL_GROUPS_PROGRAMMES,GENDER_PARTICIPATION_RATE',
     'MKAKATI Jedwali Na. 2 Lengo 9'),
    ('POLICY_FOREIGN_AFFAIRS', 'Ministry responsible for Foreign Affairs',
     'Wizara yenye dhamana ya Mambo ya Nje',
     'Ministry', 'Regional/International Cooperation',
     'Coordinate ratified regional and international disaster-management agreements and country participation in external forums.',
     'Kuratibu utekelezaji wa makubaliano ya kikanda/kimataifa yaliyoridhiwa na ushiriki wa nchi katika majukwaa ya nje.',
     'FOREIGN_AGREEMENTS_IMPLEMENTED,FOREIGN_REGIONAL_PARTICIPATION',
     'MKAKATI Jedwali Na. 2 Lengo 8')
)
insert into public.institution_policy_roles(role_code, actor_label_en, actor_label_sw, institution_class, sector_tags,
                                            responsibility_en, responsibility_sw, default_indicator_codes,
                                            source_reference, active, created_at, updated_at)
select role_code, actor_label_en, actor_label_sw, institution_class, sector_tags, responsibility_en,
       responsibility_sw, default_indicator_codes, source_reference, true, now(), now()
from roles
on conflict (role_code) do update
set actor_label_en = excluded.actor_label_en,
    actor_label_sw = excluded.actor_label_sw,
    institution_class = excluded.institution_class,
    sector_tags = excluded.sector_tags,
    responsibility_en = excluded.responsibility_en,
    responsibility_sw = excluded.responsibility_sw,
    default_indicator_codes = excluded.default_indicator_codes,
    source_reference = excluded.source_reference,
    active = true,
    updated_at = now();

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Indicators: PMO/DMD national + MKAKATI role-exact + class-specific partners
-- ─────────────────────────────────────────────────────────────────────────────
with seed(code, name, description, domain, disaster_cycle, level, value_type, unit, frequency,
          owner_type, sector, source_module, target_value, direction, sort_order,
          applicable_sectors, applicable_classes, policy_role_code, role_summary) as (
  values
    -- ── PMO-DMD / OWM-SBU national KPIs (DMD indicators.docx + MKAKATI Lengo 1/4/5/7) ──
    ('PMO_RESPONSE_RECOVERY_COORD_PCT',
     'Response and recovery measures coordinated across major disaster areas',
     'Percentage of response and recovery measures coordinated across all areas affected by major disasters (DMD target to June 2031).',
     'PMO-DMD Strategic KPIs', 'response', 'national', 'percent', '%', 'quarterly', 'pmo-dmd',
     'Disaster Management Coordination', 'DMD indicators.docx', 100, 'higher', 200,
     'Disaster Management Coordination', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'DMD KPI: coordinated response/recovery across affected areas by June 2031.'),
    ('PMO_PUBLIC_AWARENESS_INTERVENTIONS',
     'Public awareness interventions on disaster management coordinated annually',
     'Number of public-awareness interventions on disaster management coordinated and implemented in the reporting year (DMD target: 9/year by 2031).',
     'PMO-DMD Strategic KPIs', 'preparedness', 'national', 'count', 'interventions', 'annual', 'pmo-dmd',
     'Disaster Management Coordination', 'DMD indicators.docx', 9, 'higher', 210,
     'Disaster Management Coordination', 'Ministry,Government Institution,Media', 'POLICY_PMO_DMD',
     'DMD KPI: nine public-awareness interventions annually by June 2031.'),
    ('PMO_CAPACITY_BUILDING_PROGRAMMES',
     'Capacity-building programmes coordinated (prevention to recovery)',
     'Number of capacity-building programmes for prevention, mitigation, preparedness, response and recovery at national, regional and LGA levels (DMD target: 8 by 2031).',
     'PMO-DMD Strategic KPIs', 'preparedness', 'national', 'count', 'programmes', 'annual', 'pmo-dmd',
     'Disaster Management Coordination', 'DMD indicators.docx', 8, 'higher', 220,
     'Disaster Management Coordination', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'DMD KPI: eight capacity-building programmes coordinated by June 2031.'),
    ('PMO_DISTRICT_RVCA_COUNT',
     'District risk, vulnerability and capacity assessments conducted',
     'Number of districts with completed Risk-Vulnerability-Capacity Assessments (RVCA) (DMD target: 30 by 2031).',
     'PMO-DMD Strategic KPIs', 'prevention_mitigation', 'national', 'count', 'districts', 'annual', 'pmo-dmd',
     'Disaster Management Coordination', 'DMD indicators.docx', 30, 'higher', 230,
     'Disaster Management Coordination,Regional/LGA Governance', 'Ministry,Government Institution,Regional Administration,Local Government Authority', 'POLICY_PMO_DMD',
     'DMD KPI: thirty district RVCAs by June 2031.'),
    ('PMO_MULTIHAZARD_EWS_OPERATIONAL',
     'Functional multi-hazard early-warning systems operationalised',
     'Availability/status of functional multi-hazard early-warning systems strengthened and operationalised nationally.',
     'PMO-DMD Strategic KPIs', 'preparedness', 'national', 'percent', '%', 'quarterly', 'pmo-dmd',
     'Disaster Management Coordination', 'DMD indicators.docx', 100, 'higher', 240,
     'Disaster Management Coordination,Weather/Climate', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'DMD KPI: multi-hazard EWS strengthened and operationalised by June 2031.'),
    ('PMO_DRR_STRATEGIES_DEVELOPED',
     'Preparedness/response plans and DRR strategies developed',
     'Count of emergency preparedness and response plans and disaster risk reduction strategies developed under national coordination.',
     'PMO-DMD Strategic KPIs', 'prevention_mitigation', 'national', 'count', 'plans', 'annual', 'pmo-dmd',
     'Disaster Management Coordination', 'DMD indicators.docx', 30, 'higher', 250,
     'Disaster Management Coordination', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'DMD KPI: preparedness/response plans and DRR strategies by June 2031.'),
    ('PMO_RESEARCH_STUDIES_COUNT',
     'Disaster-related research studies conducted',
     'Number of research studies conducted on disaster-related matters (DMD target: 4 by 2031).',
     'PMO-DMD Strategic KPIs', 'prevention_mitigation', 'national', 'count', 'studies', 'annual', 'pmo-dmd',
     'Education/Research', 'DMD indicators.docx', 4, 'higher', 260,
     'Education/Research', 'Ministry,Government Institution,Academic and Research Institution', 'POLICY_PMO_DMD',
     'DMD KPI: four disaster-related research studies by June 2031.'),
    ('PMO_FRAMEWORKS_FORMULATED',
     'Disaster frameworks formulated and reviewed',
     'Number of disaster-management frameworks formulated and reviewed (DMD target: 9 by 2031).',
     'PMO-DMD Strategic KPIs', 'prevention_mitigation', 'national', 'count', 'frameworks', 'annual', 'pmo-dmd',
     'Disaster Management Coordination', 'DMD indicators.docx', 9, 'higher', 270,
     'Disaster Management Coordination', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'DMD KPI: nine disaster frameworks formulated/reviewed by June 2031.'),
    ('PMO_STAKEHOLDER_COORD_MEETINGS',
     'Coordination meetings and workshops with sectors and stakeholders',
     'Number of inception meetings/workshops on disaster management conducted with ministries, sectors and stakeholders.',
     'PMO-DMD Strategic KPIs', 'preparedness', 'national', 'count', 'meetings', 'quarterly', 'pmo-dmd',
     'Disaster Management Coordination', 'DMD indicators.docx', null, 'higher', 280,
     'Disaster Management Coordination', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'DMD KPI: increased multi-sector/stakeholder coordination events.'),
    ('PMO_NDMF_BUDGET_INCREASE',
     'National Disaster Management Fund budget/mobilisation progress',
     'Progress on increasing NDMF through engagement workshops, pledges and national budget allocation.',
     'PMO-DMD Strategic KPIs', null, 'national', 'percent', '%', 'annual', 'pmo-dmd',
     'Finance/Risk Financing', 'DMD indicators.docx', 100, 'higher', 290,
     'Finance/Risk Financing,Disaster Management Coordination', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'DMD KPI: increase budget to NDMF via pledges and country budget.'),
    ('PMO_JOINT_COORDINATION_GUIDELINES',
     'Joint disaster-management coordination guidelines prepared/updated',
     'Number of joint coordination guidelines prepared and updated (MKAKATI Lengo 1 — OWM-SBU).',
     'MKAKATI Policy M&E', 'preparedness', 'national', 'count', 'guidelines', 'annual', 'pmo-dmd',
     'Disaster Management Coordination', 'MKAKATI Jedwali Na. 2 Lengo 1', 1, 'higher', 300,
     'Disaster Management Coordination', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'MKAKATI: Miongozo ya uratibu wa pamoja — Mhusika OWM-SBU.'),
    ('PMO_NATIONAL_CONTINGENCY_PLAN',
     'National emergency contingency plan prepared and executed',
     'Status of national emergency contingency plan preparation and event-level execution reporting (MKAKATI Lengo 4).',
     'MKAKATI Policy M&E', 'preparedness', 'national', 'boolean', null, 'annual', 'pmo-dmd',
     'Disaster Management Coordination', 'MKAKATI Jedwali Na. 2 Lengo 4', 1, 'higher', 310,
     'Disaster Management Coordination', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'MKAKATI: Mpango wa dharura wa kukabiliana na maafa — OWM-SBU.'),

    -- ── Technical government institutions ──
    ('TMA_MULTIHAZARD_EWS_FUNCTIONAL',
     'Multi-hazard meteorological early-warning system functional',
     'Functionality of TMA multi-hazard monitoring, forecasting and warning products serving national DM.',
     'Technical Institution - TMA', 'preparedness', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Weather/Climate', 'MKAKATI 6.2.37 / Lengo 5', 100, 'higher', 1300,
     'Weather/Climate', 'Government Institution', 'POLICY_TMA',
     'TMA mandate: multi-hazard early warning and sector weather products.'),
    ('TMA_WARNING_PRODUCTS_ISSUED',
     'Meteorological / climate warning products issued',
     'Count of official warning/forecast products issued to PMO-DMD, sectors and the public in the period.',
     'Technical Institution - TMA', 'preparedness', 'agency', 'count', 'products', 'quarterly', 'agency',
     'Weather/Climate', 'MKAKATI Jedwali Na. 2 Lengo 5', null, 'higher', 1310,
     'Weather/Climate', 'Government Institution', 'POLICY_TMA',
     'TMA: Idadi ya taarifa za tahadhari zilizotumwa.'),
    ('TMA_SECTOR_WARNING_REACH',
     'Sector and area reach of meteorological warnings',
     'Share of priority sectors/regions receiving actionable meteorological warnings in time.',
     'Technical Institution - TMA', 'preparedness', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Weather/Climate', 'MKAKATI Jedwali Na. 2 Lengo 5', 100, 'higher', 1320,
     'Weather/Climate', 'Government Institution', 'POLICY_TMA',
     'Country readiness depends on last-mile meteorological warning reach.'),
    ('TIRA_INSURANCE_UPTAKE',
     'Disaster risk insurance uptake (community and productive sectors)',
     'Reported progress on insurance use for disaster risk management among communities and productive sectors.',
     'Technical Institution - TIRA', null, 'agency', 'percent', '%', 'annual', 'agency',
     'Finance/Risk Financing', 'MKAKATI Jedwali Na. 2 Lengo 4', 100, 'higher', 1330,
     'Finance/Risk Financing', 'Government Institution', 'POLICY_TIRA',
     'TIRA + private sector: Ongezeko la matumizi ya bima.'),
    ('TIRA_INSURANCE_EDUCATION_PROGRAMMES',
     'Insurance education programmes delivered',
     'Number of programmes educating communities and productive sectors on disaster-related insurance.',
     'Technical Institution - TIRA', 'preparedness', 'agency', 'count', 'programmes', 'annual', 'agency',
     'Finance/Risk Financing', 'MKAKATI Jedwali Na. 2 Lengo 4', null, 'higher', 1340,
     'Finance/Risk Financing', 'Government Institution,Private Sector', 'POLICY_TIRA',
     'TIRA / Sekta Binafsi: elimu juu ya bima.'),
    ('EGA_DIGITAL_EWS_UPTIME',
     'Digital early-warning / DM systems operational uptime',
     'Operational performance of digital early-warning and disaster-management systems under eGA stewardship.',
     'Technical Institution - eGA', 'preparedness', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Digital Government / ICT', 'MKAKATI Jedwali Na. 2 Lengo 1', 99, 'higher', 1350,
     'Digital Government / ICT', 'Government Institution', 'POLICY_EGA',
     'eGA: Taarifa ya utendaji kazi wa mifumo ya kidigitali.'),
    ('EGA_DM_SYSTEM_SECURITY',
     'Cybersecurity of disaster-management systems strengthened',
     'Reduction of cyber-attack impacts / security posture of DM digital systems.',
     'Technical Institution - eGA', 'prevention_mitigation', 'agency', 'percent', '%', 'annual', 'agency',
     'Digital Government / ICT', 'MKAKATI Jedwali Na. 2 Lengo 1', 100, 'higher', 1360,
     'Digital Government / ICT', 'Government Institution', 'POLICY_EGA',
     'eGA + ICT ministry: Usalama wa mifumo dhidi ya mashambulizi ya kimtandao.'),
    ('EGA_INTEROPERABLE_DATA_SYSTEMS',
     'Interoperable disaster data collection and storage systems',
     'Number/status of systems for collection, storage and exchange of disaster-management statistics.',
     'Technical Institution - eGA', 'preparedness', 'agency', 'count', 'systems', 'annual', 'agency',
     'Digital Government / ICT', 'MKAKATI Jedwali Na. 2 Lengo 2', null, 'higher', 1370,
     'Digital Government / ICT', 'Government Institution', 'POLICY_EGA',
     'eGA: mifumo ya ukusanyaji, uhifadhi na uchambuzi wa takwimu za maafa.'),
    ('NEMC_CLIMATE_DM_INTEGRATION',
     'Environment/climate programmes integrating disaster management',
     'Number of environment conservation and climate resilience programmes that integrate disaster-management measures.',
     'Technical Institution - NEMC', 'prevention_mitigation', 'agency', 'count', 'programmes', 'annual', 'agency',
     'Environment/Natural Resources', 'MKAKATI Jedwali Na. 2 Lengo 10', null, 'higher', 1380,
     'Environment/Natural Resources', 'Government Institution,Ministry', 'POLICY_NEMC',
     'NEMC / OMR-Mazingira: ujumuishaji wa usimamizi wa maafa katika afua za mazingira.'),
    ('TCRA_PUBLIC_WARNING_CHANNELS',
     'Public-warning telecommunications channels ready',
     'Readiness of regulated telecom/public-warning channels for emergency dissemination.',
     'Technical Institution - TCRA', 'preparedness', 'agency', 'percent', '%', 'quarterly', 'agency',
     'Communication/Media', 'MKAKATI 6.2.47', 100, 'higher', 1390,
     'Communication/Media', 'Government Institution', 'POLICY_TCRA',
     'TCRA: continuity of communication and public-warning channels.'),

    -- ── Academic / research ──
    ('ACADEMIC_DRR_RESEARCH_STUDIES',
     'Disaster-related research studies completed',
     'Number of peer-reviewed or commissioned research studies on disaster-related matters completed in the period.',
     'Academic and Research', 'prevention_mitigation', 'agency', 'count', 'studies', 'annual', 'agency',
     'Education/Research', 'MKAKATI 6.2.48; DMD research KPI', null, 'higher', 1400,
     'Education/Research', 'Academic and Research Institution', 'POLICY_ACADEMIC',
     'Universities and research institutes feed national readiness with evidence.'),
    ('ACADEMIC_DRR_TRAINING_DELIVERED',
     'Specialised disaster-management training delivered',
     'Number of specialised DM training courses/cohorts delivered (e.g. DMTC/ARU, meteorological colleges, leadership institutes).',
     'Academic and Research', 'preparedness', 'agency', 'count', 'courses', 'annual', 'agency',
     'Education/Research', 'MKAKATI 6.2.48; FINAL_DRR Training & Research', null, 'higher', 1410,
     'Education/Research', 'Academic and Research Institution', 'POLICY_ACADEMIC',
     'Academic institutions build national professional capacity for DM.'),
    ('ACADEMIC_KNOWLEDGE_PRODUCTS',
     'Knowledge products published for disaster management',
     'Number of guidelines, maps, curricula modules or knowledge products supporting disaster management.',
     'Academic and Research', 'prevention_mitigation', 'agency', 'count', 'products', 'annual', 'agency',
     'Education/Research', 'MKAKATI 6.2.48', null, 'higher', 1420,
     'Education/Research', 'Academic and Research Institution', 'POLICY_ACADEMIC',
     'Knowledge products close the science–policy gap for country readiness.'),

    -- ── Gender / special groups ministry ──
    ('GENDER_INCLUSION_GUIDELINES',
     'Guidelines for inclusion of special groups in disaster management prepared',
     'Number of guidelines prepared on inclusion of special groups in disaster-management activities.',
     'Policy Roles - Gender/Social Protection', 'preparedness', 'agency', 'count', 'guidelines', 'annual', 'agency',
     'Gender/Social Protection', 'MKAKATI Jedwali Na. 2 Lengo 9', 1, 'higher', 1430,
     'Gender/Social Protection', 'Ministry,Government Institution', 'POLICY_GENDER_SPECIAL',
     'Wizara ya Maendeleo ya Jamii, Jinsia na Watoto — makundi maalum.'),
    ('SPECIAL_GROUPS_PROGRAMMES',
     'Disaster programmes including special groups',
     'Number of disaster-management programmes that explicitly include special groups.',
     'Policy Roles - Gender/Social Protection', 'preparedness', 'agency', 'count', 'programmes', 'annual', 'agency',
     'Gender/Social Protection', 'MKAKATI Jedwali Na. 2 Lengo 9', null, 'higher', 1440,
     'Gender/Social Protection', 'Ministry,Government Institution', 'POLICY_GENDER_SPECIAL',
     'Inclusion of special groups in DM programmes.'),
    ('GENDER_PARTICIPATION_RATE',
     'Women and men participation rate in disaster-management interventions',
     'Percentage participation of women and men in implementation of disaster-management interventions.',
     'Policy Roles - Gender/Social Protection', null, 'agency', 'percent', '%', 'annual', 'agency',
     'Gender/Social Protection', 'MKAKATI Jedwali Na. 2 Lengo 9', 50, 'higher', 1450,
     'Gender/Social Protection', 'Ministry,Government Institution', 'POLICY_GENDER_SPECIAL',
     'Gender-balanced participation in DM interventions.'),

    -- ── Foreign affairs ──
    ('FOREIGN_AGREEMENTS_IMPLEMENTED',
     'Regional/international DM agreements implemented',
     'Number and status of ratified regional and international disaster-management agreements under implementation.',
     'Policy Roles - International Cooperation', null, 'agency', 'count', 'agreements', 'annual', 'agency',
     'Regional/International Cooperation', 'MKAKATI Jedwali Na. 2 Lengo 8', null, 'higher', 1460,
     'Regional/International Cooperation', 'Ministry,Government Institution', 'POLICY_FOREIGN_AFFAIRS',
     'Wizara ya Mambo ya Nje — makubaliano ya kikanda/kimataifa.'),
    ('FOREIGN_REGIONAL_PARTICIPATION',
     'Country participation in regional/international DM forums',
     'Number of regional/international opportunities, meetings, training or exercises in which the country participated.',
     'Policy Roles - International Cooperation', 'preparedness', 'agency', 'count', 'events', 'annual', 'agency',
     'Regional/International Cooperation', 'MKAKATI Jedwali Na. 2 Lengo 8', null, 'higher', 1470,
     'Regional/International Cooperation', 'Ministry,Government Institution', 'POLICY_FOREIGN_AFFAIRS',
     'Country external engagement for DM capacity and solidarity.'),

    -- ── UN agencies (stakeholder level) ──
    ('UN_TECHNICAL_ASSISTANCE',
     'UN technical assistance packages delivered for disaster risk management',
     'Number of technical assistance packages (policy, EWS, risk assessment, recovery) delivered under national leadership.',
     'Partners - UN Agency', 'prevention_mitigation', 'stakeholder', 'count', 'packages', 'quarterly', 'stakeholder',
     'Humanitarian/DRR', 'ORODHA UN AGENCIES; MKAKATI 6.2.51', null, 'higher', 1500,
     'Humanitarian/DRR', 'UN Agency', 'POLICY_UN_AGENCY',
     'UN agencies: technical assistance under government coordination.'),
    ('UN_HUMANITARIAN_SUPPORT',
     'UN humanitarian assistance value or caseload supported',
     'Scale of humanitarian assistance (beneficiaries or TZS equivalent) channelled in support of national response/recovery.',
     'Partners - UN Agency', 'response', 'stakeholder', 'number', 'TZS/beneficiaries', 'quarterly', 'stakeholder',
     'Humanitarian/DRR', 'MKAKATI 6.2.51; global humanitarian M&E practice', null, 'higher', 1510,
     'Humanitarian/DRR', 'UN Agency', 'POLICY_UN_AGENCY',
     'Tracks UN contribution to resource distribution and life-saving response.'),
    ('UN_CAPACITY_BUILDING',
     'UN-supported capacity-building activities delivered',
     'Number of capacity-building activities for government and local actors supported by the UN agency.',
     'Partners - UN Agency', 'preparedness', 'stakeholder', 'count', 'activities', 'quarterly', 'stakeholder',
     'Humanitarian/DRR', 'Sendai / UNDRR multi-stakeholder practice', null, 'higher', 1520,
     'Humanitarian/DRR', 'UN Agency', 'POLICY_UN_AGENCY',
     'UN contribution to country readiness through capacity building.'),

    -- ── NGOs ──
    ('NGO_COMMUNITY_PREPAREDNESS',
     'Community preparedness activities implemented by NGO',
     'Number of community-level preparedness activities (drills, plans, risk awareness) implemented.',
     'Partners - NGO', 'preparedness', 'stakeholder', 'count', 'activities', 'quarterly', 'stakeholder',
     'Humanitarian/DRR', 'ORODHA NGOS; MKAKATI 6.2.50', null, 'higher', 1530,
     'Humanitarian/DRR', 'NGO', 'POLICY_NGO',
     'NGOs strengthen community readiness complementary to LGA systems.'),
    ('NGO_HUMANITARIAN_ASSISTANCE',
     'Humanitarian assistance delivered by NGO',
     'Beneficiaries reached or assistance value delivered in response/recovery, aligned to national coordination.',
     'Partners - NGO', 'response', 'stakeholder', 'number', 'TZS/beneficiaries', 'quarterly', 'stakeholder',
     'Humanitarian/DRR', 'MKAKATI 6.2.50', null, 'higher', 1540,
     'Humanitarian/DRR', 'NGO', 'POLICY_NGO',
     'NGO contribution to equitable resource distribution.'),
    ('NGO_GEOGRAPHIC_COVERAGE',
     'Geographic coverage of NGO disaster interventions',
     'Number of councils/districts where the NGO delivered disaster-related interventions in the period.',
     'Partners - NGO', null, 'stakeholder', 'count', 'councils', 'quarterly', 'stakeholder',
     'Humanitarian/DRR', 'ORODHA NGOS', null, 'higher', 1550,
     'Humanitarian/DRR', 'NGO', 'POLICY_NGO',
     'Geographic coverage supports fair resource and readiness mapping.'),

    -- ── Private sector ──
    ('PRIVATE_BCP_IN_PLACE',
     'Business continuity / disaster plan in place',
     'Whether the organisation maintains an exercised business continuity or disaster-response plan.',
     'Partners - Private Sector', 'preparedness', 'stakeholder', 'boolean', null, 'annual', 'stakeholder',
     'Private Sector / Continuity', 'MKAKATI 6.2.33', 1, 'higher', 1560,
     'Private Sector / Continuity', 'Private Sector', 'POLICY_PRIVATE',
     'Private sector readiness protects national economic continuity.'),
    ('PRIVATE_CRITICAL_SERVICE_CONTINUITY',
     'Critical private service continuity during emergencies',
     'Measured continuity of critical services (telecoms, banking, energy, logistics) during emergency activations.',
     'Partners - Private Sector', 'response', 'stakeholder', 'percent', '%', 'quarterly', 'stakeholder',
     'Private Sector / Continuity', 'MKAKATI 6.2.33; global critical infrastructure practice', 100, 'higher', 1570,
     'Private Sector / Continuity', 'Private Sector', 'POLICY_PRIVATE',
     'Critical private services are part of national response capacity.'),
    ('PRIVATE_LOGISTICS_SUPPORT',
     'Private logistics or in-kind support committed to response',
     'Value or volume of logistics/in-kind support made available to national or local response.',
     'Partners - Private Sector', 'response', 'stakeholder', 'currency', 'TZS', 'quarterly', 'stakeholder',
     'Private Sector / Continuity', 'MKAKATI 6.2.33', null, 'higher', 1580,
     'Private Sector / Continuity', 'Private Sector', 'POLICY_PRIVATE',
     'Private logistics improve speed of resource distribution.'),
    ('PRIVATE_RISK_TRANSFER',
     'Risk-transfer products offered or placed',
     'Number or uptake of insurance/risk-transfer products supporting disaster resilience.',
     'Partners - Private Sector', 'prevention_mitigation', 'stakeholder', 'count', 'products', 'annual', 'stakeholder',
     'Finance/Risk Financing', 'MKAKATI Lengo 4 (bima); ATI/TBA roles', null, 'higher', 1590,
     'Finance/Risk Financing,Private Sector / Continuity', 'Private Sector', 'POLICY_PRIVATE',
     'Insurance industry contribution to risk financing.'),

    -- ── FBO ──
    ('FBO_COMMUNITY_MOBILISATION',
     'Faith-based community mobilisation for preparedness',
     'Number of community mobilisation sessions for preparedness, warning uptake or recovery.',
     'Partners - Faith-Based', 'preparedness', 'stakeholder', 'count', 'sessions', 'quarterly', 'stakeholder',
     'Humanitarian/Community', 'MKAKATI 6.2.50; ORODHA TAASISI ZA DINI', null, 'higher', 1600,
     'Humanitarian/Community', 'Faith-Based Organization', 'POLICY_FBO',
     'FBOs reach last-mile communities for readiness messaging.'),
    ('FBO_HUMANITARIAN_ASSISTANCE',
     'Faith-based humanitarian assistance delivered',
     'Beneficiaries or value of shelter, food, psychosocial or other assistance delivered.',
     'Partners - Faith-Based', 'response', 'stakeholder', 'number', 'TZS/beneficiaries', 'quarterly', 'stakeholder',
     'Humanitarian/Community', 'MKAKATI 6.2.50', null, 'higher', 1610,
     'Humanitarian/Community', 'Faith-Based Organization', 'POLICY_FBO',
     'FBO assistance complements government humanitarian pipelines.'),

    -- ── Media ──
    ('MEDIA_WARNING_DISSEMINATION',
     'Early-warning messages disseminated via media channels',
     'Number of official early-warning messages disseminated through radio/TV/print/digital channels.',
     'Partners - Media', 'preparedness', 'stakeholder', 'count', 'messages', 'quarterly', 'stakeholder',
     'Communication/Media', 'MKAKATI 6.2.52', null, 'higher', 1620,
     'Communication/Media', 'Media', 'POLICY_MEDIA',
     'Media is critical for last-mile early warning.'),
    ('MEDIA_PUBLIC_AWARENESS_CAMPAIGNS',
     'Public-awareness campaigns on disaster management',
     'Number of public-awareness campaigns on disaster management produced or aired.',
     'Partners - Media', 'preparedness', 'stakeholder', 'count', 'campaigns', 'quarterly', 'stakeholder',
     'Communication/Media', 'DMD public-awareness KPI; MKAKATI 6.2.52', null, 'higher', 1630,
     'Communication/Media', 'Media', 'POLICY_MEDIA',
     'Supports DMD public-awareness annual target.'),
    ('MEDIA_ACCURACY_PROTOCOLS',
     'Emergency information accuracy protocol applied',
     'Whether the outlet applies agreed accuracy/verification protocols for emergency information.',
     'Partners - Media', 'response', 'stakeholder', 'boolean', null, 'annual', 'stakeholder',
     'Communication/Media', 'MKAKATI 6.2.52', 1, 'higher', 1640,
     'Communication/Media', 'Media', 'POLICY_MEDIA',
     'Counters misinformation that undermines response and trust.'),

    -- ── Diplomatic ──
    ('DIPLOMATIC_COOPERATION_SUPPORT',
     'Bilateral technical or financial cooperation for disaster management',
     'Value or number of bilateral cooperation instruments supporting DRR, preparedness or recovery.',
     'Partners - Diplomatic', null, 'stakeholder', 'number', 'TZS/instruments', 'annual', 'stakeholder',
     'Development Cooperation', 'ORODHA BALOZI; MKAKATI 6.2.51', null, 'higher', 1650,
     'Development Cooperation', 'Diplomatic Mission', 'POLICY_DIPLOMATIC',
     'Diplomatic missions channel external resources under national priorities.'),

    -- ── Community ──
    ('COMMUNITY_PREPAREDNESS_ACTIONS',
     'Community preparedness actions completed',
     'Number of community preparedness actions (ward/village plans, drills, risk mapping).',
     'Partners - Community', 'preparedness', 'stakeholder', 'count', 'actions', 'quarterly', 'stakeholder',
     'Community Participation', 'MKAKATI 6.2.53', null, 'higher', 1660,
     'Community Participation', 'Community / Civic Group', 'POLICY_COMMUNITY',
     'Community action is the foundation of local readiness.'),
    ('COMMUNITY_VOLUNTEER_DEPLOYMENT',
     'Community volunteers deployed in response',
     'Number of community volunteers mobilised/deployed during response events.',
     'Partners - Community', 'response', 'stakeholder', 'count', 'volunteers', 'quarterly', 'stakeholder',
     'Community Participation', 'MKAKATI 6.2.32-6.2.53', null, 'higher', 1670,
     'Community Participation', 'Community / Civic Group', 'POLICY_COMMUNITY',
     'Volunteer capacity multiplies local response reach.'),

    -- ── Cross-cutting resource distribution / readiness (region + national already partial) ──
    ('NAT_RESOURCE_DISTRIBUTION_EQUITY',
     'National equity of disaster resource distribution',
     'Composite score of equitable resource allocation across regions/LGAs relative to risk and caseload.',
     'National Readiness & Resources', 'response', 'national', 'percent', '%', 'quarterly', 'pmo-dmd',
     'Disaster Management Coordination', 'Global DM M&E practice (resource equity)', 100, 'higher', 320,
     'Disaster Management Coordination', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'Country readiness requires fair distribution of pre-positioned and response resources.'),
    ('NAT_COUNTRY_READINESS_INDEX',
     'Composite national disaster readiness index',
     'Composite readiness from EOCC, multi-hazard EWS, plans, stock, trained teams and partner coverage (0–100).',
     'National Readiness & Resources', 'preparedness', 'national', 'percent', '%', 'quarterly', 'pmo-dmd',
     'Disaster Management Coordination', 'Global DM readiness practice (Sendai-aligned)', 100, 'higher', 330,
     'Disaster Management Coordination', 'Ministry,Government Institution', 'POLICY_PMO_DMD',
     'Single national readiness signal for PMO leadership.'),

    -- Tag generic partner indicators with all partner classes (keep existing 4; extend classes)
    ('PARTNER_RESOURCE_COMMITMENT',
     'Partner resource commitments',
     'Value of technical, financial or in-kind resources committed for disaster management in the period.',
     'Partners - Cross-cutting', null, 'stakeholder', 'currency', 'TZS', 'quarterly', 'stakeholder',
     'Humanitarian/DRR', 'National Disaster Management Policy 2004 (2025 Edition)', null, 'higher', 1480,
     'Humanitarian/DRR,Development Cooperation,Private Sector / Continuity,Humanitarian/Community',
     'UN Agency,NGO,Private Sector,Faith-Based Organization,Diplomatic Mission,Development Partner',
     'POLICY_PARTNERS',
     'All partners report resource commitments that feed national resource distribution M&E.'),
    ('PARTNER_GEOGRAPHIC_COVERAGE',
     'Partner geographic coverage',
     'Number of councils/districts where the partner delivered disaster-related support.',
     'Partners - Cross-cutting', null, 'stakeholder', 'count', 'councils', 'quarterly', 'stakeholder',
     'Humanitarian/DRR', 'National Disaster Management Policy 2004 (2025 Edition)', null, 'higher', 1485,
     'Humanitarian/DRR', 'UN Agency,NGO,Private Sector,Faith-Based Organization,Diplomatic Mission',
     'POLICY_PARTNERS',
     'Geographic coverage prevents partner concentration and gaps.'),
    ('PARTNER_TRAINING_SUPPORT',
     'Partner training or measure support delivered',
     'Number of training sessions or structural/non-structural measures supported by the partner.',
     'Partners - Cross-cutting', 'preparedness', 'stakeholder', 'count', 'sessions', 'quarterly', 'stakeholder',
     'Humanitarian/DRR', 'National Disaster Management Policy 2004 (2025 Edition)', null, 'higher', 1490,
     'Humanitarian/DRR', 'UN Agency,NGO,Private Sector,Faith-Based Organization,Academic and Research Institution',
     'POLICY_PARTNERS',
     'Partner training multiplies local preparedness capacity.'),
    ('PARTNER_FY_TCVMP_CONSIDERED',
     'Partner FY plan considering Climate Vulnerability Map System (TCVMP)',
     'Whether the partner annual plan considers TCVMP climate vulnerability information.',
     'Partners - Cross-cutting', 'prevention_mitigation', 'stakeholder', 'boolean', null, 'annual', 'stakeholder',
     'Humanitarian/DRR', 'TCVMP integration requirement', 1, 'higher', 1495,
     'Humanitarian/DRR', 'UN Agency,NGO,Private Sector,Faith-Based Organization,Diplomatic Mission',
     'POLICY_PARTNERS',
     'Climate-informed partner planning supports national risk reduction.')
)
insert into public.me_indicator_catalog(code, name, description, domain, disaster_cycle, level, value_type, unit,
                                        frequency, owner_type, sector, source_module, target_value, direction,
                                        sort_order, applicable_sectors, applicable_institution_classes,
                                        policy_role_code, policy_role_source, role_summary, active, created_at, updated_at)
select code, name, description, domain, disaster_cycle, level, value_type, unit, frequency, owner_type, sector,
       source_module, target_value, direction, sort_order, applicable_sectors, applicable_classes,
       policy_role_code,
       'MKAKATI UTEKELEZAJI SERA 2025–2035; DMD indicators.docx; ORODHA YA WASHIRIKI; FINAL_DRR Stakeholders',
       role_summary, true, now(), now()
from seed
on conflict (code) do update
set name = excluded.name,
    description = excluded.description,
    domain = excluded.domain,
    disaster_cycle = excluded.disaster_cycle,
    level = excluded.level,
    value_type = excluded.value_type,
    unit = excluded.unit,
    frequency = excluded.frequency,
    owner_type = excluded.owner_type,
    sector = excluded.sector,
    source_module = excluded.source_module,
    target_value = excluded.target_value,
    direction = excluded.direction,
    sort_order = excluded.sort_order,
    applicable_sectors = excluded.applicable_sectors,
    applicable_institution_classes = excluded.applicable_institution_classes,
    policy_role_code = excluded.policy_role_code,
    policy_role_source = excluded.policy_role_source,
    role_summary = excluded.role_summary,
    active = true,
    updated_at = now();

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Glossary expansion (MKAKATI TAFSIRI YA MANENO + system UI language)
-- ─────────────────────────────────────────────────────────────────────────────
with terms(term_en, term_sw, definition_en, definition_sw, source_reference) as (
  values
    ('National Disaster Management Fund', 'Mfuko wa Taifa wa Usimamizi wa Maafa',
     'National financing instrument for disaster preparedness, response and recovery interventions.',
     'Chombo cha ufadhili wa taifa kwa hatua za utayari, kukabiliana na kurejesha hali baada ya maafa.',
     'MKAKATI / DMD NDMF'),
    ('Emergency Operations and Communication Centre', 'Kituo cha Operesheni na Mawasiliano ya Dharura',
     'Facility for coordinating emergency operations, communications and multi-agency response.',
     'Kituo cha kuratibu operesheni za dharura, mawasiliano na majibu ya sekta mbalimbali.',
     'MKAKATI Lengo 1'),
    ('Multi-hazard Early Warning System', 'Mfumo wa Tahadhari ya Mapema wa Majanga Mbalimbali',
     'Integrated system covering monitoring, forecasting, warning dissemination and preparedness action for multiple hazards.',
     'Mfumo shirikishi wa ufuatiliaji, utabiri, usambazaji wa tahadhari na hatua za utayari kwa majanga mbalimbali.',
     'DMD indicators; Sendai Target G'),
    ('Risk Vulnerability Capacity Assessment', 'Tathmini ya Hatari, Uwezekano wa Kuathirika na Uwezo',
     'Assessment of hazards, exposure, vulnerability and capacity at area level to guide plans and investment.',
     'Tathmini ya majanga, mfiduo, uwezekano wa kuathirika na uwezo katika eneo ili kuongoza mipango na uwekezaji.',
     'DMD indicators (RVCA)'),
    ('Business Continuity Plan', 'Mpango wa Mwendelezo wa Biashara',
     'Plan ensuring critical organisational functions continue during and after a disaster.',
     'Mpango unaohakikisha shughuli muhimu za taasisi zinaendelea wakati na baada ya maafa.',
     'Private sector DRR practice'),
    ('Resource Distribution', 'Ugawaji wa Rasilimali',
     'Allocation and delivery of relief, equipment and financial resources according to needs, risk and equity.',
     'Mgao na uwasilishaji wa misaada, vifaa na rasilimali fedha kulingana na mahitaji, hatari na usawa.',
     'Global DM M&E practice'),
    ('Country Readiness', 'Utayari wa Taifa',
     'National ability to anticipate, prepare for, respond to and recover from disasters across institutions and levels.',
     'Uwezo wa taifa wa kutarajia, kujiandaa, kukabiliana na kurejesha hali baada ya maafa katika taasisi na ngazi zote.',
     'Global DM readiness practice'),
    ('Stakeholder Platform', 'Jukwaa la Wadau',
     'Formal multi-actor forum coordinating government, UN, NGOs, private sector, FBOs, academia and communities for disaster management.',
     'Jukwaa rasmi la wadau wengi linaloratibu serikali, UN, NGOs, sekta binafsi, taasisi za dini, vyuo na jamii katika usimamizi wa maafa.',
     'MKAKATI 6.2.30'),
    ('Public Awareness', 'Uelewa wa Umma',
     'Activities that increase public understanding of hazards, warnings and protective actions.',
     'Shughuli zinazoongeza uelewa wa umma kuhusu majanga, tahadhari na hatua za kujilinda.',
     'DMD public-awareness KPI'),
    ('Capacity Building', 'Ujenzi wa Uwezo',
     'Training, exercises and institutional strengthening that improve disaster-management performance.',
     'Mafunzo, mazoezi na uimarishaji wa kitaasisi unaoboresha utendaji wa usimamizi wa maafa.',
     'DMD capacity-building KPI'),
    ('Anticipatory Action', 'Hatua za Kutarajia',
     'Actions triggered by forecasts or warnings before hazard impact to reduce losses.',
     'Hatua zinazochukuliwa kwa msingi wa utabiri au tahadhari kabla ya athari za janga ili kupunguza hasara.',
     'Global EWS / anticipatory action practice'),
    ('Build Back Better', 'Kujenga Upya kwa Ubora',
     'Recovery and reconstruction that reduces future risk and improves resilience.',
     'Urejeshaji na ujenzi upya unaopunguza hatari za baadaye na kuimarisha ustahimilivu.',
     'MKAKATI glossary - Kujenga upya'),
    ('Special Groups', 'Makundi Maalum',
     'Persons requiring specific attention in disaster management (children, elderly, persons with disabilities, etc.).',
     'Watu wanaohitaji umakini maalum katika usimamizi wa maafa (watoto, wazee, wenye ulemavu n.k.).',
     'MKAKATI Lengo 9'),
    ('Gender Mainstreaming', 'Ujumuishaji wa Jinsia',
     'Integration of gender perspectives into disaster policies, plans and interventions.',
     'Kujumuisha mitazamo ya jinsia katika sera, mipango na afua za usimamizi wa maafa.',
     'MKAKATI Lengo 9'),
    ('Development Partner', 'Mshirika wa Maendeleo',
     'Bilateral or multilateral actor providing technical or financial support for disaster risk management.',
     'Mshirika wa nchi mbili au kimataifa anayetoa msaada wa kitaalamu au kifedha kwa usimamizi wa hatari za maafa.',
     'ORODHA / MKAKATI 6.2.51'),
    ('Local Government Authority', 'Mamlaka ya Serikali za Mitaa',
     'Council-level authority responsible for local disaster committees, plans, budgets and first response.',
     'Mamlaka ya ngazi ya halmashauri inayohusika na kamati, mipango, bajeti na majibu ya awali ya maafa.',
     'MKAKATI 6.2.2 / 6.2.31'),
    ('Regional Secretariat', 'Sekretarieti ya Mkoa',
     'Regional administrative structure coordinating disaster management across districts and councils.',
     'Muundo wa kiutawala wa mkoa unaoratibu usimamizi wa maafa katika wilaya na halmashauri.',
     'MKAKATI 6.2.31'),
    ('Monitoring and Evaluation', 'Ufuatiliaji na Tathmini',
     'Systematic tracking of policy implementation indicators, results and learning for disaster management.',
     'Ufuatiliaji wa utaratibu wa viashiria vya utekelezaji wa sera, matokeo na mafunzo katika usimamizi wa maafa.',
     'MKAKATI Sura 7')
)
insert into public.disaster_glossary_terms(term_en, term_sw, definition_en, definition_sw, source_reference,
                                           active, created_at, updated_at)
select term_en, term_sw, definition_en, definition_sw, source_reference, true, now(), now()
from terms
on conflict (term_en, term_sw) do update
set definition_en = excluded.definition_en,
    definition_sw = excluded.definition_sw,
    source_reference = excluded.source_reference,
    active = true,
    updated_at = now();

-- Optional UI labels for institution classes (EN/SW)
create table if not exists public.me_institution_class_labels (
    institution_class varchar(120) primary key,
    label_en varchar(180) not null,
    label_sw varchar(180) not null,
    registry varchar(20) not null default 'both', -- agency | stakeholder | both
    sort_order integer not null default 100,
    active boolean not null default true
);

insert into public.me_institution_class_labels(institution_class, label_en, label_sw, registry, sort_order) values
    ('Ministry', 'Ministries / Offices', 'Wizara / Ofisi', 'agency', 10),
    ('Government Institution', 'Government institutions & agencies', 'Taasisi na mamlaka za serikali', 'agency', 20),
    ('Government Directorate', 'Government directorates', 'Idara za serikali', 'agency', 25),
    ('Regional Administration', 'Regional administration', 'Tawala za mikoa', 'agency', 30),
    ('Local Government Authority', 'Local Government Authorities (LGAs)', 'Mamlaka za Serikali za Mitaa', 'agency', 40),
    ('Security and Response Institution', 'Security & response institutions', 'Vyombo vya ulinzi na uokoaji', 'agency', 50),
    ('Academic and Research Institution', 'Academic & research institutions', 'Vyuo na taasisi za utafiti', 'agency', 60),
    ('UN Agency', 'UN agencies', 'Mashirika ya Umoja wa Mataifa', 'stakeholder', 70),
    ('NGO', 'NGOs / civil society', 'NGOs / asasi za kiraia', 'stakeholder', 80),
    ('Private Sector', 'Private sector', 'Sekta binafsi', 'stakeholder', 90),
    ('Faith-Based Organization', 'Faith-based organisations', 'Taasisi za dini', 'stakeholder', 100),
    ('Media', 'Media', 'Vyombo vya habari', 'stakeholder', 110),
    ('Diplomatic Mission', 'Diplomatic missions', 'Balozi', 'stakeholder', 120),
    ('Community / Civic Group', 'Community & civic groups', 'Jumuiya na vikundi vya kiraia', 'stakeholder', 130),
    ('Development Partner', 'Development partners', 'Washirika wa maendeleo', 'stakeholder', 140)
on conflict (institution_class) do update
set label_en = excluded.label_en,
    label_sw = excluded.label_sw,
    registry = excluded.registry,
    sort_order = excluded.sort_order,
    active = true;
