-- R5 Dispatch console + warehouse operations read models.
-- Source migrations mirrored: 2026_03_24 dispatch_approvals, 2026_04_07 movement tracking +
-- flexible warehouse references, 2025_09_19 stock_taking_records, 2025_06_03 agency_resources.
-- Production-safe: additive IF NOT EXISTS only; existing rows are never rewritten.

-- ── Dispatch approvals: a warehouse manager's yes/no gate before stock leaves a store ──
create table if not exists public.dispatch_approvals (
    id                    bigint generated by default as identity primary key,
    allocated_resource_id bigint not null references public.allocated_resources(id) on delete cascade,
    source_type           varchar(255) not null,            -- 'Warehouse' | 'Temporary Warehouse'
    source_id             bigint not null,                  -- id in warehouses / temporary_warehouses
    quantity              numeric(12,2) not null,
    requested_by          bigint references public.users(id) on delete set null,
    approved_by           bigint references public.users(id) on delete set null,
    approved_at           timestamptz,
    rejected_by           bigint references public.users(id) on delete set null,
    rejected_at           timestamptz,
    rejection_reason      text,
    status                varchar(255) not null default 'Pending', -- Pending | Approved | Rejected
    notes                 text,
    deleted_at            timestamptz,                      -- soft delete (cancel keeps the audit row)
    created_at            timestamptz not null default now(),
    updated_at            timestamptz not null default now()
);
create index if not exists idx_dispatch_approvals_alloc_status on public.dispatch_approvals(allocated_resource_id, status);
create index if not exists idx_dispatch_approvals_source on public.dispatch_approvals(source_type, source_id);
create index if not exists idx_dispatch_approvals_status_created on public.dispatch_approvals(status, created_at);

-- ── inventory_items: flexible warehouse references + intake metadata (live stock ledger) ──
alter table public.inventory_items
    add column if not exists temporary_warehouse_id bigint references public.temporary_warehouses(id) on delete set null,
    add column if not exists current_status varchar(50),
    add column if not exists supplier_donor varchar(255),
    add column if not exists received_date date,
    add column if not exists notes text,
    add column if not exists last_audited timestamptz;
alter table public.inventory_items alter column warehouse_id drop not null;

-- ── stock_movements: movement tracking + temporary-warehouse endpoints ──
alter table public.stock_movements
    add column if not exists inventory_item_id bigint references public.inventory_items(id) on delete set null,
    add column if not exists reason varchar(100),
    add column if not exists warehouse_type varchar(20),
    add column if not exists from_temporary_warehouse_id bigint references public.temporary_warehouses(id) on delete set null,
    add column if not exists to_temporary_warehouse_id bigint references public.temporary_warehouses(id) on delete set null;

-- Source bug: code writes 'Removal'/'Deduction'/'Deployment' but the production CHECK
-- omitted them. The local table has no CHECK yet, so install the corrected full set.
alter table public.stock_movements drop constraint if exists stock_movements_movement_type_check;
alter table public.stock_movements add constraint stock_movements_movement_type_check
    check (movement_type in ('Intake','Transfer','Dispatch','Adjustment_Increase',
                             'Adjustment_Decrease','Deduction','Removal','Deployment'));

-- ── Stock taking: periodic physical count vs book quantity, with adjustments ──
create table if not exists public.stock_taking_records (
    id                 bigint generated by default as identity primary key,
    warehouse_id       bigint not null references public.warehouses(id) on delete cascade,
    stock_taking_date  date not null,
    inventory_item_id  bigint not null references public.inventory_items(id) on delete cascade,
    item_code          varchar(255),
    unit_of_measure    varchar(255) not null,
    quantity_on_record integer not null,
    quantity_counted   integer not null,
    difference         integer not null,
    condition          varchar(20) not null check (condition in ('good','damaged','expired')),
    remarks            text,
    verified_by        bigint not null references public.users(id) on delete restrict,
    approved_by        bigint references public.users(id) on delete set null,
    approved_at        timestamptz,
    created_at         timestamptz not null default now(),
    updated_at         timestamptz not null default now()
);
create index if not exists idx_stock_taking_date on public.stock_taking_records(stock_taking_date);
create index if not exists idx_stock_taking_warehouse on public.stock_taking_records(warehouse_id);

-- ── Agency-held stock offered as a dispatch source ──
create table if not exists public.agency_resources (
    id                      bigint generated by default as identity primary key,
    agency_id               bigint not null references public.agencies(id) on delete cascade,
    resource_id             bigint not null references public.resources(id) on delete restrict,
    quantity                numeric(10,2) not null,
    condition_status        varchar(255) not null,
    location_description    text not null,
    latitude                numeric(10,7),
    longitude               numeric(10,7),
    availability_notes      text,
    last_updated_by_user_id bigint references public.users(id) on delete cascade,
    created_at              timestamptz not null default now(),
    updated_at              timestamptz not null default now()
);
create index if not exists idx_agency_resources_resource on public.agency_resources(resource_id);
