-- R6 Stakeholder bidding & donations read models.
-- Source migrations mirrored: 2026_03_24 stakeholder_resource_bids, 2025_09_19 ndmf_donations.
-- Production-safe: additive IF NOT EXISTS only.

-- ── Stakeholder offers against a published allocation ──
-- One table serves two source screens: the per-allocation "bidding pool" and the
-- global "stakeholder donations" queue (the Laravel StakeholderDonation model is
-- just an alias over this same table).
create table if not exists public.stakeholder_resource_bids (
    id                    bigint generated by default as identity primary key,
    allocated_resource_id bigint references public.allocated_resources(id) on delete set null,
    stakeholder_id        bigint not null references public.stakeholders(id) on delete cascade,
    resource_id           bigint references public.resources(id) on delete set null,
    quantity_offered      numeric(12,2) not null,
    unit_price            numeric(12,2) not null,
    delivery_date         date not null,
    -- Pending | Accepted | Rejected | Withdrawn | Received (set when goods arrive)
    status                varchar(255) not null default 'Pending',
    notes                 text,
    deleted_at            timestamptz,
    created_at            timestamptz not null default now(),
    updated_at            timestamptz not null default now()
);
create index if not exists idx_srb_stakeholder_status on public.stakeholder_resource_bids(stakeholder_id, status);
create index if not exists idx_srb_allocation_status on public.stakeholder_resource_bids(allocated_resource_id, status);
create index if not exists idx_srb_status_created on public.stakeholder_resource_bids(status, created_at);

-- Source links each stakeholder organisation to its portal user account; bid-result
-- notifications are addressed to that account (additive — coordinated in manual D2).
alter table public.stakeholders
    add column if not exists user_id bigint references public.users(id) on delete set null;

-- ── NDMF cash donations registry (recordDonation in the inventory screens) ──
create table if not exists public.ndmf_donations (
    id               bigint generated by default as identity primary key,
    donor_name       varchar(255) not null,
    amount           numeric(15,2) not null,
    currency         varchar(3) not null default 'TZS',
    donation_date    date not null,
    reference_number varchar(255) not null unique,
    purpose          text,
    status           varchar(20) not null default 'pending'
                     check (status in ('pending','received','acknowledged')),
    recorded_by      bigint not null references public.users(id) on delete restrict,
    acknowledged_by  bigint references public.users(id) on delete set null,
    acknowledged_at  timestamptz,
    notes            text,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now()
);
create index if not exists idx_ndmf_donations_status on public.ndmf_donations(status);
