-- R8 Task management read models: the activity log and dependency graph
-- behind incident_tasks (created in V22). Source migrations mirrored.

create table if not exists public.task_updates (
    id         bigint generated by default as identity primary key,
    task_id    bigint not null references public.incident_tasks(id) on delete cascade,
    user_id    bigint references public.users(id) on delete set null,
    message    varchar(500) not null,
    details    text,
    created_at timestamptz not null default now()
);
create index if not exists idx_task_updates_task on public.task_updates(task_id);

create table if not exists public.task_dependencies (
    id                 bigint generated by default as identity primary key,
    task_id            bigint not null references public.incident_tasks(id) on delete cascade,
    depends_on_task_id bigint not null references public.incident_tasks(id) on delete cascade,
    created_at         timestamptz not null default now(),
    unique (task_id, depends_on_task_id)
);
create index if not exists idx_task_dependencies_on on public.task_dependencies(depends_on_task_id);
