-- R11b: Anticipatory Action Plans — the per-area preparedness backbone.
-- Faithful port of the Laravel source schema: base table (2025_09_17) + the SRS
-- enhancement columns (2025_09_28). These are the "preparedness plans activated as per
-- specific areas forecasted to have impact" the Command Post surfaces during anticipatory
-- (forecast-triggered) activation. Production-safe additive; demo rows seeded in the local seeder.
create table if not exists public.anticipatory_action_plans (
    id                          bigint generated by default as identity primary key,
    hazard_type                 varchar(100) not null,
    hazard_id                   varchar(100),                 -- Floods/Drought/Cyclone/Sea level rise/other
    publication_date            date,
    district_council            varchar(255) not null,
    coverage_location           text,                         -- specific wards/areas covered
    affected_people             integer,
    budget                      numeric(15,2),
    description                 text,
    status                      varchar(20) not null default 'draft'
                                check (status in ('draft','pending','active','archived')),
    -- SRS enhancement fields (forecast trigger + per-activity planning)
    trigger                     text,                         -- forecast data that triggers the plan
    activation_window           integer,                      -- forecast lead time, days
    activation_start            date,
    activation_end              date,
    geographical_scope          json,                         -- National/Regional/District (multi)
    action_activities_type      json,                         -- [temporary shelter, channel cleaning, relocation,…]
    responsible_actor           json,                         -- [LGAs, District/Regional Disaster Coordinator,…]
    allocated_budget_per_activity json,                       -- {activity: TZS}
    kpi_activities              json,                         -- KPIs per activity
    focal_point_name            varchar(255),
    focal_point_contact         varchar(100),
    focal_point_agency          varchar(255),
    communication_channel       json,                         -- [SMS, Radio/TV, WhatsApp, Community meeting]
    funding_source              varchar(100),                 -- Government/Non-government/others
    funding_source_other        varchar(255),
    closure_criteria            text,                         -- hazard period passes / risk reduced / completed
    created_by                  bigint references public.users(id) on delete set null,
    approved_by                 bigint references public.users(id) on delete set null,
    approval_date               timestamptz,
    created_at                  timestamptz not null default now(),
    updated_at                  timestamptz not null default now()
);
create index if not exists idx_aap_hazard_status on public.anticipatory_action_plans(hazard_type, status);
create index if not exists idx_aap_district on public.anticipatory_action_plans(district_council);
