-- R11b: the institutional layer the Disaster Management Act No. 6 of 2022 requires —
-- formal disaster declarations (the Act's headline instruments) and the statutory committee
-- hierarchy. Neither exists in the Laravel source; both are net-new, faithful to the Act.

-- ── Formal declarations: s.32 Disaster Area (Minister) / s.33 State of Emergency (President) ──
create table if not exists public.disaster_declarations (
    id                bigint generated by default as identity primary key,
    declaration_type  varchar(30) not null check (declaration_type in ('disaster_area','state_of_emergency')),
    authority         varchar(30) not null check (authority in ('Minister','President')),
    legal_basis       varchar(80),                 -- 'DM Act 2022 s.32' / 's.33 + Emergency Powers Act Cap 221'
    activation_id     bigint references public.response_activations(id) on delete set null,
    incident_id       bigint references public.incidents(id) on delete set null,
    hazard            varchar(255),
    area_scope        text not null,               -- declared area(s)
    justification     text,
    gazette_reference varchar(120),                -- Government Gazette notice (s.32)
    -- the Act's escalation chain: National Technical -> National Steering -> declaring authority
    status            varchar(30) not null default 'proposed'
                      check (status in ('proposed','technical_review','steering_endorsed','declared','expired','revoked')),
    effective_from    date,
    effective_until   date,                        -- s.32: up to 3 months, extendable
    is_simulation     boolean not null default false,
    proposed_by       bigint references public.users(id) on delete set null,
    declared_by       bigint references public.users(id) on delete set null,
    declared_at       timestamptz,
    revoked_at        timestamptz,
    revocation_reason text,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);
create index if not exists idx_declarations_status on public.disaster_declarations(status);
create index if not exists idx_declarations_activation on public.disaster_declarations(activation_id);

-- audit trail of the declaration chain (who endorsed/declared/revoked, when, note)
create table if not exists public.declaration_events (
    id             bigint generated by default as identity primary key,
    declaration_id bigint not null references public.disaster_declarations(id) on delete cascade,
    action         varchar(40) not null,           -- proposed / technical_reviewed / steering_endorsed / declared / extended / revoked / expired
    actor_role     varchar(120),                   -- committee / office that acted (per the Act)
    user_id        bigint references public.users(id) on delete set null,
    note           text,
    created_at     timestamptz not null default now()
);
create index if not exists idx_declaration_events on public.declaration_events(declaration_id);

-- ── Statutory committee hierarchy (DM Act 2022 ss.7–26) — reference data ──
create table if not exists public.disaster_committees (
    id             bigint generated by default as identity primary key,
    level          varchar(20) not null,           -- national/regional/district/ward/village/mtaa
    committee_type varchar(20) not null,           -- steering / technical / community
    name           varchar(160) not null,
    chair_title    varchar(160) not null,
    secretary_title varchar(160),
    legal_basis    varchar(80),
    sort_order     int not null default 0,
    created_at     timestamptz not null default now()
);

insert into public.disaster_committees (level, committee_type, name, chair_title, secretary_title, legal_basis, sort_order)
select * from (values
    ('national','steering','National Disaster Management Steering Committee (NSCDM)','Minister of State, PMO','Permanent Secretary, PMO','DM Act 2022 ss.7–8', 1),
    ('national','technical','National Disaster Management Technical Committee (NTCDM)','Permanent Secretary, PMO','Director, Disaster Management Division','DM Act 2022 ss.9–10', 2),
    ('national','community','National Disaster Management Stakeholders Platform','Director, DMD','Assistant Director (Planning & Research), DMD','DM Act 2022 ss.11–12', 3),
    ('regional','steering','Regional Disaster Management Steering Committee (= Regional Security Committee)','Regional Commissioner','RAS','DM Act 2022 s.13 (Cap 61)', 4),
    ('regional','technical','Regional Disaster Management Technical Committee (RTCDM)','Regional Administrative Secretary (RAS)','Assistant Administrative Secretary (Coordination & Planning)','DM Act 2022 s.15', 5),
    ('district','steering','District Disaster Management Steering Committee (= District Security Committee)','District Commissioner','DAS','DM Act 2022 s.17 (Cap 61)', 6),
    ('district','technical','Council Disaster Management Technical Committee (CTCDM)','Council Executive Director','Head of Council Planning Department','DM Act 2022 s.19', 7),
    ('ward','community','Ward Disaster Management Committee (= Ward Development Committee)','Ward Councillor','Ward Executive Officer','DM Act 2022 ss.22–23 (Cap 287)', 8),
    ('village','community','Village Disaster Management Committee (= Village Council)','Village Chairperson','Village Executive Officer','DM Act 2022 s.24 (Cap 287)', 9),
    ('mtaa','community','Mtaa Disaster Management Committee','Mtaa Chairperson','Mtaa Executive Officer','DM Act 2022 s.25 (Cap 288)', 10)
) as v(level, committee_type, name, chair_title, secretary_title, legal_basis, sort_order)
where not exists (select 1 from public.disaster_committees);
