-- System Settings → Roles & Permissions. The SRS used a Spatie-style permission model; this is the
-- read-model port: a permission catalogue grouped by functional area, and the role→permission
-- pivot. The Spring backend currently authorizes by ROLE (hasAnyRole), so these rows document and
-- govern the access model (and can drive finer enforcement later) — the matrix is the single place
-- the "who-can-do-what" policy is captured. Production-safe additive; seeded by PermissionLocalSeeder.
create table if not exists public.permissions (
    id          bigint generated by default as identity primary key,
    name        varchar(120) not null unique,   -- e.g. 'incidents.approve'  (module.action)
    module      varchar(60)  not null,          -- functional area / module label
    action      varchar(40)  not null,          -- view | create | update | approve | …
    label       varchar(160) not null,          -- human label for the matrix cell
    guard_name  varchar(40)  not null default 'web',
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now()
);
create index if not exists idx_permissions_module on public.permissions(module);

-- Spatie-compatible pivot (permission_id, role_id).
create table if not exists public.role_has_permissions (
    permission_id bigint not null references public.permissions(id) on delete cascade,
    role_id       bigint not null references public.roles(id) on delete cascade,
    primary key (permission_id, role_id)
);

-- roles carries a description for the registry (Spatie's roles table has only name/guard).
alter table public.roles add column if not exists description varchar(255);
