-- Connectivity + missing-blocks: let responders triage citizen hazard reports (close the loop
-- from the public "Report Hazard" wizard into the Response module), and add Contingency Plans
-- (the strategic sibling of Anticipatory Action Plans — present in the Laravel source, not yet ported).

-- ── 1) Triage columns on the citizen-report table (written by the public portal) ──
alter table public.public_hazard_reports
    add column if not exists status varchar(20) not null default 'new'
        check (status in ('new','reviewing','converted','dismissed')),
    add column if not exists reviewed_by bigint references public.users(id) on delete set null,
    add column if not exists review_notes text,
    add column if not exists linked_incident_id bigint references public.incidents(id) on delete set null,
    add column if not exists reviewed_at timestamptz;
create index if not exists idx_phr_status on public.public_hazard_reports(status);

-- ── 2) Contingency Plans (source: contingency_plans) ──
create table if not exists public.contingency_plans (
    id               bigint generated by default as identity primary key,
    publication_date date,
    hazard_type      varchar(120) not null,
    timeframe        varchar(120),                 -- e.g. "2026 rainy season", "5-year"
    coverage_regions json,                         -- regions covered (multi)
    sectors          json,                         -- sectors/DRFs engaged (multi)
    budget           numeric(15,2),
    description      text,
    document_path    varchar(255),
    status           varchar(20) not null default 'draft'
                     check (status in ('draft','pending','active','archived')),
    created_by       bigint references public.users(id) on delete set null,
    approved_by      bigint references public.users(id) on delete set null,
    approval_date    timestamptz,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now()
);
create index if not exists idx_contingency_hazard_status on public.contingency_plans(hazard_type, status);
