-- Recovery sub-modules (Relief Distribution, Recovery Programs, Reconstruction/Strategic Projects,
-- Knowledge Repository / Lessons Learned) + SMS Management log. Ports the Laravel source tables.
-- Production-safe: CREATE/ALTER ... IF NOT EXISTS only.

-- ── 1) Relief Distribution (source: relief_distributions) ──
create table if not exists public.relief_distributions (
    id                        bigint generated by default as identity primary key,
    incident_id               bigint references public.incidents(id) on delete set null,
    damage_assessment_id      bigint references public.damage_assessments(id) on delete set null,
    distribution_date         date not null default current_date,
    location_name             varchar(255) not null,
    district_name             varchar(120),
    region_name               varchar(120),
    resource_id               bigint references public.resources(id),
    quantity_distributed      numeric(12,2) not null default 0,
    unit_of_measure           varchar(50),
    beneficiary_name_or_group varchar(255) not null,
    beneficiary_contact       varchar(120),
    beneficiary_identifier    varchar(120),
    distributing_agency_id    bigint references public.agencies(id) on delete set null,
    distributed_by_user_id    bigint references public.users(id) on delete set null,
    confirmation_status       varchar(40) not null default 'Pending Verification'
                              check (confirmation_status in ('Pending Verification','Confirmed','Disputed')),
    notes                     text,
    created_at                timestamptz not null default now(),
    updated_at                timestamptz not null default now()
);
create index if not exists idx_relief_status on public.relief_distributions(confirmation_status);

-- ── 2) Recovery Programs (source: recovery_programs) ──
create table if not exists public.recovery_programs (
    id                       bigint generated by default as identity primary key,
    program_name             varchar(255) not null unique,
    description              text,
    incident_id              bigint references public.incidents(id) on delete set null,
    program_type             varchar(120) not null,
    status                   varchar(40) not null default 'Planning'
                             check (status in ('Planning','Ongoing','Completed','Suspended','Cancelled')),
    start_date               date,
    expected_completion_date date,
    actual_completion_date   date,
    total_budget_allocated   numeric(16,2),
    currency                 varchar(10) default 'TZS',
    lead_agency_id           bigint references public.agencies(id) on delete set null,
    focal_point_user_id      bigint references public.users(id) on delete set null,
    geographic_scope         text,
    key_objectives_outcomes  text,
    created_at               timestamptz not null default now(),
    updated_at               timestamptz not null default now()
);
create index if not exists idx_recovery_program_status on public.recovery_programs(status);

-- ── 3) Reconstruction / Strategic Projects ──
-- Base table (id, entry_id, project_name, project_category, project_sector, project_status) was
-- created by V13. Here we ADD the SRS columns the Recovery screen needs — additively, never recreating.
create table if not exists public.strategic_projects (
    id           bigint generated by default as identity primary key,
    entry_id     varchar(60) unique,
    project_name varchar(255) not null,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now()
);
alter table public.strategic_projects
    add column if not exists project_category   varchar(40) default 'Government',
    add column if not exists project_sector     varchar(40) default 'Other',
    add column if not exists project_status     varchar(40) default 'Mobilization',
    add column if not exists location           json,
    add column if not exists project_coverage   varchar(120),
    add column if not exists risk_hazard_type   varchar(40),
    add column if not exists risk_hazard_names  json,
    add column if not exists impacts_identified json,
    add column if not exists has_management_plan boolean default false,
    add column if not exists elements_at_risk   text,
    add column if not exists challenges         text,
    add column if not exists action_taken       text,
    add column if not exists budget             numeric(16,2),
    add column if not exists created_by         bigint,
    add column if not exists stakeholder_id     bigint;
create index if not exists idx_strategic_project_status on public.strategic_projects(project_status);

-- ── 4) Knowledge Repository / Lessons Learned ──
-- V13 created a MINIMAL disaster_knowledge_repositories (content_title/content_type/description/
-- visibility_level). Add every column the Lessons Learned screen reads/writes — additive, IF NOT EXISTS.
alter table public.disaster_knowledge_repositories
    add column if not exists title varchar(255),
    add column if not exists content_title varchar(255),
    add column if not exists description text,
    add column if not exists content_type varchar(40),
    add column if not exists document_type varchar(60),
    add column if not exists hazard_type varchar(80),
    add column if not exists disaster_date date,
    add column if not exists date_of_publication date,
    add column if not exists location varchar(160),
    add column if not exists region varchar(120),
    add column if not exists contributor varchar(160),
    add column if not exists contributor_organization varchar(200),
    add column if not exists uploader_name varchar(255),
    add column if not exists uploader_institution varchar(255),
    add column if not exists visibility_level varchar(20) default 'public',
    add column if not exists status varchar(20) default 'draft',
    add column if not exists approval_status varchar(20) not null default 'Pending',
    add column if not exists approval_date timestamptz,
    add column if not exists downloads_count integer not null default 0,
    add column if not exists version integer not null default 1;

-- ── 5) SMS Management log (source: sms_logs) ──
create table if not exists public.sms_logs (
    id                bigint generated by default as identity primary key,
    notification_type varchar(40),
    notification_id   bigint,
    recipient_phone   varchar(20) not null,
    message           text not null,
    status            varchar(20) not null default 'pending'
                      check (status in ('pending','sent','failed','delivered')),
    response_data     text,
    external_id       varchar(120),
    error_message     text,
    sent_at           timestamptz,
    delivered_at      timestamptz,
    retry_count       integer not null default 0,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);
create index if not exists idx_sms_status_created on public.sms_logs(status, created_at);
