-- Phase 2: generated EW bulletin products — each generated 722E_4 PDF stored + anchored to its
-- geography so it can be listed, appended on a map, viewed and downloaded. Additive; the Python
-- engine that PRODUCES the PDF is untouched (Angular uploads the returned blob here).
create table if not exists public.ew_generated_products (
    id            bigint generated by default as identity primary key,
    title         varchar(255),
    bulletin_type varchar(30) not null default '722E_4',
    warning_code  varchar(50),
    issue_date    date,
    issue_time    varchar(10),
    severity      varchar(30),              -- highest level across the product (ADVISORY/WARNING/MAJOR_WARNING)
    regions       json,                     -- region names covered (for the map + chips)
    envelope      json,                     -- full areas+levels+delineations (the build-on-push payload)
    centroid_lat  double precision,
    centroid_lng  double precision,
    pdf_path      varchar(255),             -- relative to storage/public, e.g. ew-products/<uuid>.pdf
    file_name     varchar(255),
    generated_by  bigint references public.users(id) on delete set null,
    generated_at  timestamptz not null default now(),
    created_at    timestamptz not null default now()
);
create index if not exists idx_ew_product_date on public.ew_generated_products(issue_date);
create index if not exists idx_ew_product_severity on public.ew_generated_products(severity);
