-- Cross-agency Early Warning integration bus (native re-platform of the Python file-bus
-- `ew/output/bridge/latest_<agency>.json`). Every warning entity (TMA, MoW, GST, MoH, MoA, NEMC)
-- SUBMITS its bulletin/assessment here; every other entity can READ each other's latest (interlinking,
-- e.g. MoW reads TMA rainfall for flood forecasting); PMO-DMD reads ALL and overlays them into one
-- realistic bulletin. Additive read-model; the Python authoring pages are untouched.
create table if not exists public.ew_agency_submissions (
    id            bigint generated by default as identity primary key,
    agency        varchar(12) not null,        -- tma | mow | gst | moh | moa | nemc
    bridge_ts     timestamptz not null default now(),   -- server stamp (mirrors _bridge_ts)
    issue_date    date,
    issue_time    varchar(16),
    report_period varchar(24),                 -- MoA only (Weekly/Bi-weekly/Monthly/Seasonal)
    payload       json not null,               -- the full agency envelope `data` (per-agency shape)
    regions       json,                        -- denormalised region names (for overlays/reference)
    districts     json,                        -- denormalised district names (for overlays/consolidation)
    hazard_types  json,                        -- denormalised hazard/disease/event types
    alert_summary json,                        -- {major_warning:n, warning:n, advisory:n}
    top_alert     varchar(16),                 -- highest level across the submission
    item_count    integer not null default 0,  -- hazards/events/outbreaks/assessments count
    submitted_by  bigint references public.users(id) on delete set null,
    is_latest     boolean not null default true,  -- the current latest per agency
    created_at    timestamptz not null default now()
);
create index if not exists idx_ew_sub_agency on public.ew_agency_submissions(agency);
create index if not exists idx_ew_sub_latest on public.ew_agency_submissions(agency, is_latest);
create index if not exists idx_ew_sub_ts on public.ew_agency_submissions(agency, bridge_ts desc);
