-- Boundary support for the Streamlit EW Monitoring page (faithful port of the Laravel
-- 2026_03_26_100001_create_ew_focal_point_reports_table migration + the bits BulletinIngestion needs).
-- The Streamlit engine is untouched; this just lets its /api/ew/* calls land in Spring as they did in Laravel.
create table if not exists public.ew_focal_point_reports (
    id                   bigint generated by default as identity primary key,
    bulletin_number      varchar(30),
    warning_code         varchar(50),
    focal_point_name     varchar(255) not null,
    phone                varchar(20),
    location             varchar(255),
    role                 varchar(50),
    status               varchar(30) not null default 'awaiting',
    report_details       text,
    actions_taken        text,
    actions_planned      text,
    bulletin_received    boolean not null default false,
    impact_verified      boolean not null default false,
    people_affected      integer,
    households_evacuated integer,
    reported_by          bigint references public.users(id) on delete set null,
    created_at           timestamptz not null default now(),
    updated_at           timestamptz not null default now()
);
create index if not exists idx_ew_fpr_bulletin on public.ew_focal_point_reports(bulletin_number, created_at);
create index if not exists idx_ew_fpr_code on public.ew_focal_point_reports(warning_code);

-- The Laravel Warning model carries created_by/updated_by/attachments; the DMIS read-model warnings table
-- is slimmer. The bulletin-ingest dedup keys on created_by, so add it (+ attachments) additively.
alter table public.warnings add column if not exists created_by  bigint references public.users(id) on delete set null;
alter table public.warnings add column if not exists updated_by  bigint references public.users(id) on delete set null;
alter table public.warnings add column if not exists attachments json;
