-- NDMF cash-OUT ledger: the National Disaster Management Fund was a one-way inbox (ndmf_donations
-- only). This adds disbursements so money flows donor -> NDMF balance -> a training (sets the
-- training's source_of_fund) or procurement (intakes goods into the warehouse via the normal stock
-- path). Balance is derived per currency = received donations - paid disbursements; the cash-out and
-- the training/allocation links both live here, so no other table is altered.
create table if not exists public.ndmf_disbursements (
    id                     bigint generated by default as identity primary key,
    reference_number       varchar(255) not null unique,
    purpose_type           varchar(20)  not null,
    amount                 numeric(15,2) not null check (amount > 0),
    currency               varchar(3)   not null,
    disbursement_date      date         not null,
    status                 varchar(20)  not null default 'paid' check (status in ('paid','voided')),
    training_plan_id       bigint references public.training_plans(id) on delete set null,
    allocated_resource_id  bigint references public.allocated_resources(id) on delete set null,
    resource_id            bigint references public.resources(id) on delete set null,
    quantity               numeric(15,2),
    warehouse_id           bigint references public.warehouses(id) on delete set null,
    temporary_warehouse_id bigint references public.temporary_warehouses(id) on delete set null,
    payee                  varchar(255),
    notes                  text,
    disbursed_by           bigint not null references public.users(id) on delete restrict,
    voided_by              bigint references public.users(id) on delete set null,
    voided_at              timestamptz,
    created_at             timestamptz not null default now(),
    updated_at             timestamptz not null default now(),
    constraint ndmf_disb_purpose_chk    check (purpose_type in ('training','procurement')),
    constraint ndmf_disb_training_link  check (purpose_type <> 'training' or training_plan_id is not null),
    constraint ndmf_disb_proc_link      check (purpose_type <> 'procurement' or resource_id is not null)
);
create index if not exists idx_ndmf_disb_status_currency on public.ndmf_disbursements(status, currency);
create index if not exists idx_ndmf_disb_training on public.ndmf_disbursements(training_plan_id);
create index if not exists idx_ndmf_disb_alloc on public.ndmf_disbursements(allocated_resource_id);
-- One paid disbursement per training — never double-fund the same training.
create unique index if not exists uq_ndmf_disb_training_paid on public.ndmf_disbursements(training_plan_id)
    where status = 'paid' and training_plan_id is not null;
