import { Component, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { DatePipe } from '@angular/common';
import { PageHeaderComponent } from '../../shell/page-header.component';
import { StatCardComponent } from '../../shell/stat-card.component';

interface Product {
  id: number; title: string; bulletin_type: string; warning_code: string | null;
  issue_date: string; issue_time: string; severity: string; regions: string[]; hazard_type: string | null;
  pdf_url: string; generated_at: string; description?: string | null;
  is_published: boolean; published_at?: string | null; show_on_map: boolean; on_publications: boolean;
}

const SEV: Record<string, { label: string; color: string }> = {
  ADVISORY: { label: 'Advisory', color: '#FFD000' },
  WARNING: { label: 'Warning', color: '#FFA500' },
  MAJOR_WARNING: { label: 'Major Warning', color: '#FF0000' },
};
// exact engine hazard icons (same set as the authoring map)
const HAZ_ICON_FILE: Record<string, string> = {
  HEAVY_RAIN: 'heavy_rain.png', LARGE_WAVES: 'large_waves.png', STRONG_WIND: 'strong_wind.png',
  EXTREME_TEMPERATURE: 'extreme_temperature.png', FLOODS: 'floods.png', EARTHQUAKE: 'earthquake.png',
  LANDSLIDES: 'landslides.png', VOLCANO: 'volcano.png', DISEASE_OUTBREAK: 'disease_outbreak.png',
  DROUGHT: 'drought.png', AIR_POLLUTION: 'air_pollution.png',
};
const HAZ_ICON = (type: string | null) => '/ew-icons/' + (HAZ_ICON_FILE[type ?? ''] ?? 'heavy_rain.png');

/**
 * EOCC Bulletin — a storage registry of bulletin PDFs: the 722E_4 products generated by the EW engine
 * and any manually-uploaded bulletins, listed newest-first for viewing and download. Authoring lives in
 * the EW module; this screen only stores and serves the finished PDFs.
 */
@Component({
  selector: 'page-generated-bulletins',
  standalone: true,
  imports: [PageHeaderComponent, StatCardComponent, DatePipe],
  template: `
    <dmis-page-header title="EOCC Bulletin" icon="fa-file-pdf"
      [breadcrumbs]="[{label:'Home', url:'/home'}, {label:'Preparedness'}, {label:'Early Warning Systems', url:'/m/preparedness/early-warnings'}, {label:'EOCC Bulletin'}]">
      <label class="up-btn" [class.busy]="uploading()">
        <i class="fas" [class.fa-upload]="!uploading()" [class.fa-spinner]="uploading()" [class.fa-spin]="uploading()"></i>
        {{ uploading() ? 'Uploading…' : 'Upload PDF' }}
        <input type="file" accept="application/pdf,.pdf" hidden [disabled]="uploading()" (change)="upload($any($event.target).files)">
      </label>
    </dmis-page-header>
    @if (uploadError()) { <div class="up-error"><i class="fas fa-triangle-exclamation"></i> {{ uploadError() }}</div> }

    <div class="stats-row">
      <dmis-stat-card [value]="stats()['total'] ?? 0" label="Bulletins" icon="fa-file-pdf" color="#0d6efd" />
      <dmis-stat-card [value]="stats()['major'] ?? 0" label="Major Warning" icon="fa-triangle-exclamation" color="#FF0000" />
      <dmis-stat-card [value]="stats()['warning'] ?? 0" label="Warning" icon="fa-bell" color="#FFA500" />
      <dmis-stat-card [value]="stats()['advisory'] ?? 0" label="Advisory" icon="fa-circle-info" color="#d4a900" />
      <dmis-stat-card [value]="stats()['today'] ?? 0" label="Issued today" icon="fa-calendar-day" color="#059669" />
    </div>

    <div class="gb-list">
      <div class="gb-list-head"><i class="fas fa-layer-group"></i> {{ products().length }} bulletin(s)</div>
      <div class="gb-grid">
        @for (p of products(); track p.id) {
          <div class="gb-card">
            <div class="gb-card-top">
              <span class="gb-haz" [style.border-color]="sevColor(p.severity)"><img [src]="hazIcon(p.hazard_type)" alt=""></span>
              <span class="gb-sev" [style.background]="sevColor(p.severity)">{{ sevLabel(p.severity) }}</span>
              <span class="gb-pub" [class.on]="p.is_published">{{ p.is_published ? 'Published' : 'Draft' }}</span>
              <span class="gb-date">{{ p.issue_date | date:'dd MMM' }}</span>
            </div>
            <div class="gb-title">{{ p.title }}</div>
            @if (p.description) { <div class="gb-desc">{{ p.description }}</div> }
            <div class="gb-regions">
              @for (r of p.regions; track r) { <span class="gb-region">{{ r }}</span> }
            </div>
            @if (p.on_publications || p.show_on_map) {
              <div class="gb-targets">
                @if (p.on_publications) { <span class="gb-tgt"><i class="fas fa-book"></i> Publications</span> }
                @if (p.show_on_map) { <span class="gb-tgt"><i class="fas fa-map-location-dot"></i> Map</span> }
              </div>
            }
            <div class="gb-actions">
              <a class="gb-btn view" [href]="p.pdf_url" target="_blank"><i class="fas fa-eye"></i> View</a>
              <button class="gb-btn pub" (click)="openPublish(p)">
                <i class="fas fa-globe"></i> {{ p.is_published ? 'Manage publishing' : 'Publish' }}
              </button>
            </div>
            <button class="gb-btn disseminate" (click)="openDisseminate(p)">
              <i class="fas fa-tower-broadcast"></i> Disseminate to affected areas
            </button>
          </div>
        }
      </div>
      @if (!products().length) {
        <div class="gb-empty">No bulletins yet. Bulletins generated by the EW engine are stored here for viewing and download.</div>
      }
    </div>

    <!-- publish targets dialog -->
    @if (publishing(); as p) {
      <div class="pb-overlay" (click)="closePublish()">
        <div class="pb-modal" (click)="$event.stopPropagation()">
          <div class="pb-head"><i class="fas fa-globe"></i> Publish bulletin</div>
          <div class="pb-title">{{ p.title }}</div>
          <p class="pb-hint">Choose where this bulletin appears for the public. Clear both to unpublish it.</p>
          <label class="pb-opt">
            <input type="checkbox" [checked]="tgtPublications()" (change)="tgtPublications.set($any($event.target).checked)">
            <span><b>Publications library</b><br><small>Listed and downloadable on the public Publications page (as a Bulletin).</small></span>
          </label>
          <label class="pb-opt">
            <input type="checkbox" [checked]="tgtMap()" (change)="tgtMap.set($any($event.target).checked)">
            <span><b>Portal map</b><br><small>Shown on the public early-warning map.</small></span>
          </label>
          @if (publishError()) { <div class="up-error">{{ publishError() }}</div> }
          <div class="pb-actions">
            <button class="gb-btn" (click)="closePublish()">Cancel</button>
            <button class="gb-btn pub" [disabled]="saving()" (click)="confirmPublish()">
              {{ saving() ? 'Saving…' : (tgtPublications() || tgtMap() ? 'Publish' : 'Unpublish') }}
            </button>
          </div>
        </div>
      </div>
    }

    <!-- disseminate dialog — wires the bulletin into the Communication Center -->
    @if (disseminating(); as p) {
      <div class="pb-overlay" (click)="closeDisseminate()">
        <div class="pb-modal dm" (click)="$event.stopPropagation()">
          <div class="pb-head"><i class="fas fa-tower-broadcast"></i> Disseminate bulletin</div>
          <div class="pb-title">{{ p.title }}</div>
          @if (!dResult()) {
            <p class="pb-hint">Send this early warning to people in the affected areas. SMS &amp; email go through the Communication Center, where every send is logged.</p>

            <div class="dm-sec">Audience</div>
            <label class="dm-chk"><input type="checkbox" [checked]="dAudArea()" (change)="dAudArea.set($any($event.target).checked)"> People &amp; stakeholders in the affected areas</label>
            <label class="dm-chk"><input type="checkbox" [checked]="dAudHazard()" (change)="dAudHazard.set($any($event.target).checked)"> Subscribers for this hazard (any area)</label>
            <label class="dm-chk"><input type="checkbox" [checked]="dAudCoord()" (change)="dAudCoord.set($any($event.target).checked)"> Area coordinators (RAS / DAS / DC)</label>

            <div class="dm-sec">Channels</div>
            <label class="dm-chk"><input type="checkbox" [checked]="dSms()" (change)="dSms.set($any($event.target).checked)"> SMS — short message</label>
            <label class="dm-chk"><input type="checkbox" [checked]="dEmail()" (change)="dEmail.set($any($event.target).checked)"> Email — with the bulletin PDF</label>

            @if (dSms()) {
              <div class="dm-sec">SMS text <span class="dm-count">{{ dSmsMsg().length }}/450</span></div>
              <textarea class="dm-ta" rows="3" maxlength="450" [value]="dSmsMsg()" (input)="dSmsMsg.set($any($event.target).value)"></textarea>
            }
            @if (dEmail()) {
              <div class="dm-sec">Email</div>
              <input class="dm-in" [value]="dEmailSubject()" (input)="dEmailSubject.set($any($event.target).value)" placeholder="Subject">
              <textarea class="dm-ta" rows="3" [value]="dEmailBody()" (input)="dEmailBody.set($any($event.target).value)"></textarea>
              <label class="dm-chk"><input type="checkbox" [checked]="dAttachPdf()" (change)="dAttachPdf.set($any($event.target).checked)"> Attach the bulletin PDF</label>
            }

            @if (dError()) { <div class="up-error">{{ dError() }}</div> }
            <div class="pb-actions">
              <button class="gb-btn" (click)="closeDisseminate()">Cancel</button>
              <button class="gb-btn disseminate" [disabled]="dSending() || (!dSms() && !dEmail()) || (!dAudArea() && !dAudHazard() && !dAudCoord())" (click)="confirmDisseminate()">
                {{ dSending() ? 'Sending…' : 'Send' }}
              </button>
            </div>
          } @else {
            <div class="dm-result">
              <div class="dm-ok"><i class="fas fa-circle-check"></i> Dissemination sent.</div>
              <ul>
                <li>SMS: {{ dResult().sms?.valid ?? dResult().sms?.attempted ?? 0 }} sent@if (dResult().sms?.invalid) { · {{ dResult().sms.invalid }} invalid }</li>
                <li>Email: {{ dResult().email?.sent ?? 0 }} sent@if (dResult().email?.failed) { · {{ dResult().email.failed }} failed }</li>
                <li>In-app to coordinators: {{ dResult().inApp?.coordinators ?? 0 }}</li>
              </ul>
              @if (!(dResult().recipients?.sms) && !(dResult().recipients?.email)) {
                <div class="dm-note">No recipients matched the affected areas yet — add area subscribers/stakeholders, or seed coordinator locations.</div>
              }
              <a class="dm-link" href="/m/content-management/communication-center" target="_blank"><i class="fas fa-arrow-up-right-from-square"></i> Open Communication Center</a>
            </div>
            <div class="pb-actions"><button class="gb-btn" (click)="closeDisseminate()">Close</button></div>
          }
        </div>
      </div>
    }
  `,
  styles: [`
    .gb-list { background: #fff; border: 1px solid var(--border); border-radius: 16px; padding: 1rem; }
    .gb-list-head { font-weight: 700; color: var(--text-dark); margin-bottom: 0.8rem; font-size: 0.86rem; display: flex; align-items: center; gap: 0.4rem; }
    .gb-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(290px, 1fr)); gap: 0.7rem; }
    .gb-card { border: 1px solid var(--border); border-radius: 12px; padding: 0.7rem 0.8rem; }
    .gb-card-top { display: flex; align-items: center; gap: 0.4rem; margin-bottom: 0.3rem; }
    .gb-haz { width: 28px; height: 28px; border-radius: 7px; border: 2px solid; background: #fff; display: inline-flex; align-items: center; justify-content: center; padding: 2px; flex-shrink: 0; }
    .gb-haz img { width: 100%; height: 100%; object-fit: contain; }
    .gb-sev { color: #fff; font-size: 0.66rem; font-weight: 800; padding: 0.12rem 0.5rem; border-radius: 20px; }
    .gb-pub { font-size: 0.62rem; font-weight: 700; padding: 0.1rem 0.45rem; border-radius: 20px; background: #e2e8f0; color: #475569; text-transform: uppercase; letter-spacing: 0.3px; }
    .gb-pub.on { background: #d1fae5; color: #065f46; }
    .gb-date { margin-left: auto; font-size: 0.72rem; color: var(--text-light); }
    .gb-btn.pub { background: rgba(13,110,253,0.07); color: #0d6efd; border-color: rgba(13,110,253,0.2); cursor: pointer; font-family: inherit; }
    .gb-btn.pub:disabled { opacity: 0.6; cursor: default; }
    .gb-targets { display: flex; gap: 0.35rem; margin-bottom: 0.45rem; }
    .gb-tgt { font-size: 0.66rem; font-weight: 700; color: #065f46; background: #d1fae5; border-radius: 6px; padding: 0.1rem 0.45rem; }
    .pb-overlay { position: fixed; inset: 0; background: rgba(15,23,42,0.45); display: flex; align-items: center; justify-content: center; z-index: 1000; }
    .pb-modal { background: #fff; border-radius: 14px; padding: 1.2rem 1.3rem; width: min(440px, 92vw); box-shadow: 0 12px 40px rgba(0,0,0,0.25); }
    .pb-head { font-weight: 800; color: var(--primary, #003366); display: flex; align-items: center; gap: 0.45rem; font-size: 0.95rem; }
    .pb-title { font-weight: 600; margin: 0.5rem 0 0.2rem; color: var(--text-dark); }
    .pb-hint { font-size: 0.78rem; color: var(--text-mid); margin: 0 0 0.8rem; }
    .pb-opt { display: flex; gap: 0.6rem; align-items: flex-start; border: 1px solid var(--border); border-radius: 10px; padding: 0.6rem 0.7rem; margin-bottom: 0.5rem; cursor: pointer; }
    .pb-opt small { color: var(--text-mid); }
    .pb-actions { display: flex; justify-content: flex-end; gap: 0.5rem; margin-top: 0.6rem; }
    .up-btn { display: inline-flex; align-items: center; gap: 0.4rem; cursor: pointer; background: var(--primary, #003366); color: #fff; border-radius: 8px; padding: 0.4rem 0.9rem; font-size: 0.82rem; font-weight: 600; }
    .up-btn.busy { opacity: 0.7; cursor: default; }
    .up-error { background: #fee2e2; color: #991b1b; border-radius: 8px; padding: 0.5rem 0.8rem; margin: 0.6rem 0; font-size: 0.8rem; }
    .gb-title { font-weight: 600; font-size: 0.82rem; color: var(--text-dark); margin-bottom: 0.35rem; }
    .gb-desc { font-size: 0.74rem; color: var(--text-mid); line-height: 1.45; margin-bottom: 0.4rem; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; }
    .gb-regions { display: flex; flex-wrap: wrap; gap: 0.25rem; margin-bottom: 0.45rem; }
    .gb-region { background: rgba(0,0,0,0.05); border-radius: 6px; padding: 0.1rem 0.4rem; font-size: 0.68rem; color: var(--text-mid); }
    .gb-actions { display: flex; gap: 0.4rem; }
    .gb-btn { flex: 1; text-align: center; border-radius: 7px; padding: 0.3rem; font-size: 0.72rem; font-weight: 600; text-decoration: none; border: 1px solid var(--border); color: var(--text-dark); }
    .gb-btn.view { background: rgba(0,51,102,0.06); color: var(--primary); border-color: rgba(0,51,102,0.15); }
    .gb-btn.dl { background: rgba(5,150,105,0.08); color: #059669; border-color: rgba(5,150,105,0.2); }
    .gb-btn.disseminate { width: 100%; margin-top: 0.4rem; background: rgba(5,150,105,0.09); color: #047857; border-color: rgba(5,150,105,0.25); cursor: pointer; font-family: inherit; display: inline-flex; align-items: center; justify-content: center; gap: 0.4rem; }
    .gb-btn.disseminate:disabled { opacity: 0.55; cursor: default; }
    .gb-empty { font-size: 0.8rem; color: var(--text-mid); padding: 1rem; }
    .pb-modal.dm { width: min(520px, 94vw); max-height: 88vh; overflow-y: auto; }
    .dm-sec { font-size: 0.74rem; font-weight: 800; color: var(--text-dark); text-transform: uppercase; letter-spacing: 0.3px; margin: 0.7rem 0 0.35rem; }
    .dm-sec .dm-count { float: right; font-weight: 600; color: var(--text-light); text-transform: none; letter-spacing: 0; }
    .dm-chk { display: flex; align-items: center; gap: 0.5rem; font-size: 0.8rem; color: var(--text-dark); padding: 0.28rem 0; cursor: pointer; }
    .dm-ta, .dm-in { width: 100%; border: 1px solid var(--border); border-radius: 8px; padding: 0.5rem 0.6rem; font-family: inherit; font-size: 0.8rem; color: var(--text-dark); box-sizing: border-box; }
    .dm-ta { resize: vertical; margin-bottom: 0.4rem; }
    .dm-in { margin-bottom: 0.4rem; }
    .dm-result { font-size: 0.85rem; color: var(--text-dark); }
    .dm-result .dm-ok { font-weight: 700; color: #047857; display: flex; align-items: center; gap: 0.4rem; }
    .dm-result ul { margin: 0.5rem 0 0.5rem 1.1rem; padding: 0; font-size: 0.8rem; color: var(--text-mid); }
    .dm-note { background: #fffbeb; color: #92400e; border-radius: 8px; padding: 0.5rem 0.7rem; font-size: 0.76rem; margin-bottom: 0.5rem; }
    .dm-link { display: inline-flex; align-items: center; gap: 0.4rem; font-size: 0.82rem; color: #0d6efd; text-decoration: none; font-weight: 600; }
  `],
})
export class GeneratedBulletinsComponent {
  private http = inject(HttpClient);

  products = signal<Product[]>([]);
  stats = signal<Record<string, number>>({});
  uploading = signal(false);
  uploadError = signal('');
  publishing = signal<Product | null>(null);
  tgtPublications = signal(false);
  tgtMap = signal(false);
  saving = signal(false);
  publishError = signal('');

  // dissemination dialog state
  disseminating = signal<Product | null>(null);
  dAudArea = signal(true);
  dAudHazard = signal(true);
  dAudCoord = signal(true);
  dSms = signal(true);
  dEmail = signal(true);
  dSmsMsg = signal('');
  dEmailSubject = signal('');
  dEmailBody = signal('');
  dAttachPdf = signal(true);
  dSending = signal(false);
  dError = signal('');
  dResult = signal<any | null>(null);

  constructor() { this.reload(); }

  sevColor(s: string): string { return SEV[s]?.color ?? '#64748b'; }
  sevLabel(s: string): string { return SEV[s]?.label ?? s; }
  hazIcon(type: string | null): string { return HAZ_ICON(type); }

  reload(): void {
    this.http.get<any>('/api/v1/ew/products').subscribe(r => {
      this.products.set(r.products ?? []);
      this.stats.set(r.stats ?? {});
    });
  }

  /** Upload a standalone bulletin PDF into the registry (stored as Draft until published). */
  upload(files: FileList | null): void {
    const file = files?.[0];
    if (!file) { return; }
    this.uploadError.set('');
    this.uploading.set(true);
    const form = new FormData();
    form.append('pdf', file);
    form.append('title', file.name.replace(/\.pdf$/i, ''));
    this.http.post<any>('/api/v1/ew/products/upload', form).subscribe({
      next: () => { this.uploading.set(false); this.reload(); },
      error: err => {
        this.uploading.set(false);
        this.uploadError.set(err?.error?.detail ?? err?.error?.message ?? 'Could not upload the bulletin. Please try a valid PDF.');
      },
    });
  }

  /** Open the publish-targets dialog, pre-filled with the bulletin's current targets. */
  openPublish(p: Product): void {
    this.publishError.set('');
    this.tgtPublications.set(p.on_publications);
    this.tgtMap.set(p.show_on_map);
    this.publishing.set(p);
  }

  closePublish(): void { this.publishing.set(null); }

  /** Apply the chosen targets (Publications and/or Map); clearing both unpublishes the bulletin. */
  confirmPublish(): void {
    const p = this.publishing();
    if (!p) { return; }
    this.saving.set(true);
    this.publishError.set('');
    this.http.patch<any>(`/api/v1/ew/products/${p.id}/publish`,
      { publications: this.tgtPublications(), map: this.tgtMap() }).subscribe({
      next: () => { this.saving.set(false); this.publishing.set(null); this.reload(); },
      error: err => {
        this.saving.set(false);
        this.publishError.set(err?.error?.detail ?? err?.error?.message ?? 'Could not update the bulletin.');
      },
    });
  }

  /** Open the dissemination dialog, pre-filling an SMS short-message + email defaults from the bulletin. */
  openDisseminate(p: Product): void {
    this.dError.set('');
    this.dResult.set(null);
    this.dAudArea.set(true); this.dAudHazard.set(true); this.dAudCoord.set(true);
    this.dSms.set(true); this.dEmail.set(true); this.dAttachPdf.set(true);
    this.dSmsMsg.set(this.buildSms(p));
    this.dEmailSubject.set(p.title || 'Early Warning Bulletin');
    this.dEmailBody.set(this.buildEmail(p));
    this.disseminating.set(p);
  }

  closeDisseminate(): void { this.disseminating.set(null); this.dResult.set(null); }

  /** Send the bulletin to the affected areas through the Communication Center (SMS + email + in-app). */
  confirmDisseminate(): void {
    const p = this.disseminating();
    if (!p) { return; }
    const audiences: string[] = [];
    if (this.dAudArea()) { audiences.push('area'); }
    if (this.dAudHazard()) { audiences.push('hazard'); }
    if (this.dAudCoord()) { audiences.push('coordinators'); }
    const channels: string[] = [];
    if (this.dSms()) { channels.push('sms'); }
    if (this.dEmail()) { channels.push('email'); }
    this.dSending.set(true);
    this.dError.set('');
    this.http.post<any>(`/api/v1/ew/products/${p.id}/disseminate`, {
      audiences, channels,
      sms_message: this.dSmsMsg(),
      email_subject: this.dEmailSubject(),
      email_message: this.dEmailBody(),
      attach_pdf: this.dAttachPdf(),
    }).subscribe({
      next: res => { this.dSending.set(false); this.dResult.set(res); },
      error: err => {
        this.dSending.set(false);
        this.dError.set(err?.error?.detail ?? err?.error?.message ?? 'Could not disseminate the bulletin. Check your permissions and the gateway.');
      },
    });
  }

  private buildSms(p: Product): string {
    const area = (p.regions ?? []).slice(0, 4).join(', ') || 'maeneo husika';
    const sev = SEV[p.severity]?.label ?? p.severity;
    const hz = p.hazard_type ? ' — ' + p.hazard_type : '';
    const code = p.warning_code ? ' #' + p.warning_code : '';
    return `ONYO LA MAAFA${code}: ${sev}${hz}. Maeneo: ${area}. Chukua tahadhari. (e-MAAFA)`;
  }

  private buildEmail(p: Product): string {
    const area = (p.regions ?? []).join(', ') || 'the affected areas';
    const sev = SEV[p.severity]?.label ?? p.severity;
    return `An early-warning bulletin has been issued${p.warning_code ? ' (' + p.warning_code + ')' : ''}.\n\n`
      + `Severity: ${sev}\n${p.hazard_type ? 'Hazard: ' + p.hazard_type + '\n' : ''}Areas: ${area}\n\n`
      + `Please see the attached bulletin and take appropriate precautions.`;
  }
}
